Alter Session Set NLS_DATE_FORMAT = 'DD-MM-YYYY';

----------------------------------------------------------------------------------------------------

Insert into Mng_Curn (Id, Num, Name, Code, Rate, Status_Id, Rem) values (1, 1, '1 - Syrian Pound', 'SYP', 1  , 1, null);
Insert into Mng_Curn (Id, Num, Name, Code, Rate, Status_Id, Rem) values (2, 2, '2 - US Dolar'    , 'USD', 500, 1, null);
Insert into Mng_Curn (Id, Num, Name, Code, Rate, Status_Id, Rem) values (3, 3, '3 - Euro'        , 'EUR', 650, 1, null);

----------------------------------------------------------------------------------------------------

