Alter Session Set NLS_DATE_FORMAT = 'DD-MM-YYYY';

----------------------------------------------------------------------------------------------------

Insert into Acc_Cost (Id, Num, Name, Type_Id, Status_Id, Rem) VALUES (0, 0, 0, 1, 1, null);

----------------------------------------------------------------------------------------------------

Insert into Acc_Acc (Id, Num, Name, Type_Id, Status_Id, DBCR_Id, Close_Id, Rem) VALUES (0, 0, 0, 1, 1, 1, 0, null);
