-- Ported from Oracle: db/01-Admin/0000_PhS_0400_Packages.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_admin


-- TODO(port): context is not supported on postgres (source line 1).
-- Original Oracle statement:
--   DROP   CONTEXT PhCTX;

-- TODO(port): context is not supported on postgres (source line 2).
-- Original Oracle statement:
--   CREATE CONTEXT PhCTX USING PhContext ACCESSED GLOBALLY;

-- TODO(port): package is not supported on postgres (source line 3).
-- Original Oracle statement:
--   Create OR Replace Package PhContext AS
--     Procedure Set_Lang(nLangId IN NUMBER);
--     Procedure Set_User(nUserId IN NUMBER);
--     Procedure Set_Period(nPeriodId IN NUMBER);
--   End PhContext;

-- TODO(port): package is not supported on postgres (source line 10).
-- Original Oracle statement:
--   Create OR Replace Package Body PhContext AS
--     Procedure Set_Lang(nLangId IN NUMBER) IS
--     Begin
--       IF nLangId NOT IN (1, 2) THEN
--         RAISE_APPLICATION_ERROR(-20001, 'Invalid LANG_Id');
--       END IF;
--       DBMS_SESSION.SET_CONTEXT('PhCTX', 'LANG_ID', nLangId);
--     END;
--   
--     Procedure set_User(nUserId IN NUMBER) IS
--     Begin
--       DBMS_SESSION.SET_CONTEXT('PhCTX', 'USER_ID', nUserId);
--     End;
--   
--     Procedure set_Period(nPeriodId IN NUMBER) IS
--     Begin
--       DBMS_SESSION.SET_CONTEXT('PhCTX', 'PERIOD_ID', nPeriodId);
--     End;
--   End PhContext;

-- TODO(port): grant is not supported on postgres (source line 31).
-- Original Oracle statement:
--   GRANT EXECUTE ON PhContext TO C##erpCopy;

-- TODO(port): grant is not supported on postgres (source line 33).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpDemo;

-- TODO(port): grant is not supported on postgres (source line 34).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpClinic;

-- TODO(port): grant is not supported on postgres (source line 35).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpNSCC;

-- TODO(port): grant is not supported on postgres (source line 36).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##NSCC;

-- TODO(port): grant is not supported on postgres (source line 37).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpUN;

-- TODO(port): grant is not supported on postgres (source line 38).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##UN;

-- TODO(port): grant is not supported on postgres (source line 39).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpEpona;

-- TODO(port): grant is not supported on postgres (source line 40).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpNIG;

-- TODO(port): grant is not supported on postgres (source line 41).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpELcom;

-- TODO(port): grant is not supported on postgres (source line 42).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpFarkad;

-- TODO(port): grant is not supported on postgres (source line 43).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpHashemia;

-- TODO(port): grant is not supported on postgres (source line 44).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpLRGC;

-- TODO(port): grant is not supported on postgres (source line 45).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpiCloud;

-- TODO(port): grant is not supported on postgres (source line 46).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpOLEK;

-- TODO(port): grant is not supported on postgres (source line 47).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpTrans;

-- TODO(port): grant is not supported on postgres (source line 48).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpDEC;

-- TODO(port): grant is not supported on postgres (source line 49).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpDECB;

-- TODO(port): grant is not supported on postgres (source line 50).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpAlTaqi;

-- TODO(port): grant is not supported on postgres (source line 51).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpAlmasa;

-- TODO(port): grant is not supported on postgres (source line 52).
-- Original Oracle statement:
--   Grant EXECUTE ON PhContext To C##erpSabbagh;
