-- Ported from Oracle: db/01-Copy/0010_Notif_0800_Init.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


INSERT INTO Notif_Table (Id,Status_Id,Name,Dname,Rem) VALUES (1,1,'Emp_Leave_Request','Leave Request',null);

INSERT INTO Notif_Table (Id,Status_Id,Name,Dname,Rem) VALUES (2,1,'SDesk_Ticket','Ticket',null);

INSERT INTO Notif_Table (Id,Status_Id,Name,Dname,Rem) VALUES (3,1,'SDesk_Ticket_Change_Status','Ticket Change Status',null);

INSERT INTO Notif_Table_Fld (Id,Table_Id,Kind_Id,Name,Dname,Rem) VALUES (1,1,2,'Emp_Id','Employee name',null);

INSERT INTO Notif_Table_Fld (Id,Table_Id,Kind_Id,Name,Dname,Rem) VALUES (2,2,1,'Subject','Subject',null);

INSERT INTO Notif_Table_Fld (Id,Table_Id,Kind_Id,Name,Dname,Rem) VALUES (3,3,2,'nStatus_Id','new Status',null);

INSERT INTO Notif_Table_Fld (Id,Table_Id,Kind_Id,Name,Dname,Rem) VALUES (4,2,2,'Id','number',null);

INSERT INTO Notif_Table_Eevnt (Id,Table_Id,Event_Id,Type_Id,Status_Id,Title,Color,Icon,Rem) VALUES (1,1,1,2,1,'Title1','#ccc','bi bi-bell',null);

INSERT INTO Notif_Table_Eevnt (Id,Table_Id,Event_Id,Type_Id,Status_Id,Title,Color,Icon,Rem) VALUES (2,2,1,2,1,'Title2','#ccc','bi bi-bell',null);

INSERT INTO Notif_Table_Eevnt (Id,Table_Id,Event_Id,Type_Id,Status_Id,Title,Color,Icon,Rem) VALUES (3,3,1,2,1,'Title3','#ccc','bi bi-bell',null);

INSERT INTO Notif_Table_Event_Action (Id,Tevent_Id,Field_Id,Name,Dname,Api,Icon,Rem) VALUES (1,1,1,'approve','approve name','ApproveLeaveRequest',null,null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (1,1,null,1,1,'تم طلب إجازة من قبل الموظف ',null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (2,1,1,2,2,null,null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (3,2,null,1,1,'تم فتح بطاقة جديدة بعنوان ',null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (4,2,2,2,2,null,null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (5,2,null,1,3,'يرجى الاستلام بأسرع وقت',null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (6,3,null,1,1,'تم تغيير حالة البطاقة ذات الرقم ',null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (7,3,4,2,2,null,null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (8,3,null,1,3,'إلى',null);

INSERT INTO Notif_Table_Event_Descr (Id,Tevent_Id,Field_Id,Type_Id,Norder,Value,Rem) VALUES (9,3,3,2,4,null,null);
