-- Ported from Oracle: db/01-Copy/0010_CPY_0610_TRIG.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


-- REVIEW(port): trigger translated mechanically; verify before use.

DELIMITER $$
CREATE TRIGGER
  Cpy_TBID_Cod_Unit
  Before Insert
  On Cpy_Cod_Unit
  For Each Row
BEGIN
  If NEW.Id IS NULL Then
    Select /* TODO(port): Cpy_Cod_Unit_Seq.NEXTVAL - use AUTO_INCREMENT */ NULL
      Into NEW.Id;
  End If;
END$$
DELIMITER ;

-- REVIEW(port): trigger translated mechanically; verify before use.

DELIMITER $$
CREATE TRIGGER
  Cpy_TBID_Cod_Doc
  Before Insert
  On Cpy_Cod_Doc
  For Each Row
BEGIN
  If NEW.Id IS NULL Then
    Select /* TODO(port): Cpy_Cod_Doc_Seq.NEXTVAL - use AUTO_INCREMENT */ NULL
      Into NEW.Id;
  End If;
END$$
DELIMITER ;

-- REVIEW(port): trigger translated mechanically; verify before use.

DELIMITER $$
CREATE TRIGGER
  Cpy_TBID_Perm
  Before Insert
  On Cpy_Perm
  For Each Row
BEGIN
  If NEW.Id IS NULL Then
    Select /* TODO(port): Cpy_Perm_Seq.NEXTVAL - use AUTO_INCREMENT */ NULL
      Into NEW.Id;
  End If;
END$$
DELIMITER ;

-- REVIEW(port): trigger translated mechanically; verify before use.

DELIMITER $$
CREATE TRIGGER
  Cpy_TBID_PermPriv
  Before Insert
  On Cpy_PermPriv
  For Each Row
BEGIN
  If NEW.Id IS NULL Then
    Select /* TODO(port): Cpy_PermPriv_Seq.NEXTVAL - use AUTO_INCREMENT */ NULL
      Into NEW.Id;
  End If;
END$$
DELIMITER ;

-- REVIEW(port): trigger translated mechanically; verify before use.

DELIMITER $$
CREATE TRIGGER
  Cpy_TBID_User
  Before Insert
  On Cpy_User
  For Each Row
BEGIN
  If NEW.Id IS NULL Then
    Select /* TODO(port): Cpy_User_Seq.NEXTVAL - use AUTO_INCREMENT */ NULL
      Into NEW.Id;
  End If;
END$$
DELIMITER ;
