-- Ported from Oracle: db/01-Copy/0010_CPY_0120_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
SET SESSION sql_mode = CONCAT(@@sql_mode, ',NO_AUTO_VALUE_ON_ZERO,PIPES_AS_CONCAT');
USE phsoftme_erp_demo;


Create Table Cpy_SList	                  -- جدول القوائم الخاصة
( Id         BIGINT NOT NULL AUTO_INCREMENT,			            -- مفتاح رئيسي
  SPrv_Id    BIGINT NOT NULL,		              -- الصلاحية
  Name       VARCHAR(100) NOT NULL,			    -- اسم القائمة
  Rem        VARCHAR(100),			            -- ملاحظات
  Ins_User   MEDIUMINT,      Ins_Date DATETIME,
  Upd_User   MEDIUMINT,      Upd_Date DATETIME,
  CONSTRAINT CpySList_PK          PRIMARY KEY (Id),
  CONSTRAINT CpySList_UK          UNIQUE      (SPrv_Id, Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO Cpy_SList (Id, SPrv_Id, Name) VALUES (0, 0, '-');

Create Table Cpy_TList                 -- جدول القوائم الخاصة
( Id         BIGINT NOT NULL AUTO_INCREMENT,			            -- مفتاح رئيسي
  SList_Id   BIGINT NOT NULL,		              -- الصلاحية
  Rel_Id     BIGINT NOT NULL,		              -- المفتاح المرتبط
  Rem        VARCHAR(100),			            -- ملاحظات
  Ins_User   MEDIUMINT,      Ins_Date DATETIME,
  Upd_User   MEDIUMINT,      Upd_Date DATETIME,
  CONSTRAINT CpyTList_PK           PRIMARY KEY (Id),
  CONSTRAINT CpyTList_UK           UNIQUE      (SList_Id, Rel_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_PGrp			            -- جدول مجموعات الصلاحيات
( Id          BIGINT NOT NULL AUTO_INCREMENT,                   -- مفتاح رئيسي
  PStatus_Id  BIGINT  Default 2,		              -- حالة فترة العمل
  Status_Id   BIGINT Default 1 NOT NULL,         -- حالة الخيار 1 فعال 2 غير فعال
  Name        VARCHAR(30) NOT NULL,			      -- اسم الفئة
  Rem         VARCHAR(100),			              -- ملاحظات
  Ins_User    MEDIUMINT,       Ins_Date DATETIME,
  Upd_User    MEDIUMINT,       Upd_Date DATETIME,
  CONSTRAINT  CpyPGrp_PK          PRIMARY KEY (Id  ),
  CONSTRAINT  CpyPGrp_Name_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_Perm			                  -- جدول صلاحيات فئات المستخدمين
( Id         BIGINT NOT NULL AUTO_INCREMENT,			            -- مفتاح رئيسي
  PGrp_Id    BIGINT Default 0,	                -- فئة المستخدمين
  MPrg_Id    BIGINT Default 0,	              -- البرنامج
  VPeriod    SMALLINT Default 9999,	            -- الفترة
  IPeriod    SMALLINT Default 9999,	            -- الفترة
  Range_Id   BIGINT Default 0,		              -- مجال الرؤية 0 ضمن المجموعة 1 يرى نفسه فقط
  OK         TINYINT Default 1,		              -- السماحية
  Ins_User   MEDIUMINT,       Ins_Date DATETIME,
  Upd_User   MEDIUMINT,       Upd_Date DATETIME,
  CONSTRAINT CpyPerm_PK       PRIMARY KEY (Id),
  CONSTRAINT CpyPerm_UK       UNIQUE      (PGrp_Id, MPrg_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_PermPriv		        -- جدول بنود صلاحيات فئات المستخدمين
( Id           BIGINT NOT NULL AUTO_INCREMENT,			          -- مفتاح رئيسي
  Perm_Id      BIGINT NOT NULL,		            -- مفتاح الأب
  Prv_Id       BIGINT NOT NULL,		            -- الصلاحية
  OK           TINYINT Default 1,		            -- حالة الصلاحية
  Ins_User     MEDIUMINT,       Ins_Date DATETIME,
  Upd_User     MEDIUMINT,       Upd_Date DATETIME,
  CONSTRAINT   CpyPPrv_PK        PRIMARY KEY (Id),
  CONSTRAINT   CpyPPrv_UK        UNIQUE      (Perm_Id, Prv_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_PermSPriv		    -- جدول بنود صلاحيات فئات المستخدمين
( Id         BIGINT NOT NULL AUTO_INCREMENT,			            -- مفتاح رئيسي
  Perm_Id    BIGINT NOT NULL,		              -- مفتاح الأب
  SPrv_Id    BIGINT NOT NULL,		              -- الصلاحية
  SList_Id   BIGINT NOT NULL,		              -- القائمة
  Status_Id  BIGINT Default 0,	                -- حالة التخصيص 0 غير مخصص(عام) / 1 الموجود في القائمة / -1 عدا الموجود في القائمة
  Ins_User   MEDIUMINT,      Ins_Date DATETIME,
  Upd_User   MEDIUMINT,      Upd_Date DATETIME,
  CONSTRAINT CpyPSPrv_PK        PRIMARY KEY (Id),
  CONSTRAINT CpyPSPrv_UK        UNIQUE      (Perm_Id, SList_Id, Status_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_Dash_Perm		      -- جدول صلاحيات لوحة التحكم
( Id        	 BIGINT NOT NULL AUTO_INCREMENT,			        -- مفتاح رئيسي
  PGrp_Id      BIGINT Default 0,	            -- فئة المستخدمين
  Dashboard_Id BIGINT NOT NULL,			        -- كتلة لوحة التحكم
  OK           TINYINT Default 1,		          -- السماحية
  CONSTRAINT   CpyDashPerm_PK      PRIMARY KEY (Id),
  CONSTRAINT   CpyDashPerm_UK      UNIQUE      (PGrp_Id, Dashboard_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_User                        -- جدول المستخدمين
( Id          BIGINT NOT NULL AUTO_INCREMENT,              -- مفتاح رئيسي
  Bran_Id     BIGINT Default 0,             -- الفرع
  UGrp_Id     BIGINT Default 1,             -- فئة المستخدم
  PGrp_Id     BIGINT Default 1 NOT NULL,    -- مجموعة الصلاحيات
  Gender_Id   BIGINT Default 1 NOT NULL,    -- الجنس
  Status_Id   BIGINT Default 1 NOT NULL,    -- الحالة
  Verified_Id BIGINT Default 2 NOT NULL,    -- حالة التدقيق
  Logon       VARCHAR(30) NOT NULL,      -- اسم الدخول
  Pass        VARCHAR(256) NOT NULL,     -- كلمة المرور
  Name        VARCHAR(200) NOT NULL,     -- الأسم
  Picture     VARCHAR(255),              -- ملف الصورة
  Rem         VARCHAR(200),              -- ملاحظات
  Ins_User    MEDIUMINT, Ins_Date DATETIME,
  Upd_User    MEDIUMINT, Upd_Date DATETIME,
  CONSTRAINT  CpyUser_PK          PRIMARY KEY (Id    ),
  CONSTRAINT  CpyUser_Logon_UK    UNIQUE      (Logon ),
  CONSTRAINT  CpyUser_Name_UK     UNIQUE      (Name  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Cpy_User Add CONSTRAINT CpyUser_Bran_FK Foreign Key (Bran_Id) References Cpy_Bran(Id);

Create Table Cpy_SpecPerm	                -- جدول صلاحيات خاصة
( Id         BIGINT NOT NULL AUTO_INCREMENT,			            -- مفتاح رئيسي
  Perm_Id    BIGINT NOT NULL,		              -- مفتاح الأب
  Rel_Id     BIGINT Default 0,			          -- المفتاح المرتبط
  Rem        VARCHAR(250),			            -- البيان
  Ins_User   MEDIUMINT, Ins_Date DATETIME,
  Upd_User   MEDIUMINT, Upd_Date DATETIME,
  CONSTRAINT CpySpecPerm_PK       PRIMARY KEY (Id),
  CONSTRAINT CpySpecPerm_UK       UNIQUE      (Perm_Id, Rel_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_Token			                                  -- جدول أرقام جلسات الاتصال
( Id           BIGINT NOT NULL AUTO_INCREMENT,			                        -- مفتاح رئيسي
  GId          VARCHAR(50) Default (REPLACE(UUID(),'-','')) NOT NULL,		-- المفتاح
  CFront_Id    BIGINT Default 0 NOT NULL,	                  -- واجهة النسخة
  User_Id      BIGINT Default 0 NOT NULL,			              -- المستخدم
  Period_Id    BIGINT Default 0 NOT NULL,			              -- الفترة المالية
  Status       MEDIUMINT Default 1 NOT NULL,	                  -- الحالة 1 فعال - 2 غير فعال - 3 ملغى
  SDate        DATETIME DEFAULT (NOW()) NOT NULL,                   -- تاريخ ووقت بداية الجلسة
  EDate        DATETIME Default (DATE_ADD(NOW(), INTERVAL 1 DAY)) NOT NULL,               -- تاريخ ووقت نهاية الجلسة
  ADate        DATETIME DEFAULT (NOW()) NOT NULL,                   -- تاريخ ووقت آخر نشاط
  Gender       TINYINT,                                       -- الجنس
  PGrp         MEDIUMINT,                                       -- مجموعة الصلاحيات
  Role         TINYINT,                                       -- فئة المستخدم
  Copy         VARCHAR(25),                               -- النسخة
  Name         VARCHAR(100),                              -- الاسم
  Login        VARCHAR(100),                              -- اسم الدخول
  Picture      VARCHAR(100),                              -- الصورة
  PvKey        VARCHAR(3072),                             -- Private Key
  PbKey        VARCHAR(3072),                             -- Publice Key
  vIP          VARCHAR(100),                              -- IP
  vPort        VARCHAR(100),                              -- Port
  vHost        VARCHAR(100),                              -- Host
  CONSTRAINT   CpyToken_PK       PRIMARY KEY (Id ),
  CONSTRAINT   CpyToken_Token_UK UNIQUE      (GId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE Cpy_UDevice                           -- دليل أجهزة مستخدم
( Id         BIGINT NOT NULL AUTO_INCREMENT,                     -- مفتاح رئيسي
  User_Id    BIGINT NOT NULL,                      -- المستخدم المرتبط
  Serial     VARCHAR(100) NOT NULL,             -- الرقم التسلسلي للجهاز
  Name       VARCHAR(100) NOT NULL,             -- الاسم
  OS         VARCHAR(100) NOT NULL,             -- نظام التشغيل
  Token      VARCHAR(512) NOT NULL,             -- Token
  Ins_Date   DATETIME DEFAULT (NOW()),
  CONSTRAINT Cpy_UDevice_PK      PRIMARY KEY (Id),
  CONSTRAINT Cpy_UDevice_UK      UNIQUE      (User_Id, Serial)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE Cpy_RCode                         -- دليل أكواد استرجاع كلمة المرور
( Id         BIGINT NOT NULL AUTO_INCREMENT,                     -- مفتاح رئيسي
  User_Id    BIGINT NOT NULL,                      -- المستخدم
  Code       VARCHAR(6),          				      -- الرمز
  Ins_Date   DATETIME DEFAULT (NOW()),
  CONSTRAINT Cpy_RCode_PK      PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Cpy_Cod_Notifs
(
  Id           BIGINT          NOT NULL AUTO_INCREMENT,
  Status_Id    BIGINT          Default 1 NOT NULL,
  Code         VARCHAR(50)  NOT NULL,
  IName        VARCHAR(100) NOT NULL, -- English Name
  LName        VARCHAR(100) NOT NULL, -- Arabic Name
  Rem          VARCHAR(100),
  Ins_User     BIGINT,         Ins_Date DATETIME,
  Upd_User     BIGINT,         Upd_Date DATETIME,
  
  CONSTRAINT Cpy_Cod_Notif_PK        PRIMARY KEY (Id),
  CONSTRAINT Cpy_Cod_Notif_Code_UK   UNIQUE (Code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into Cpy_Cod_Notifs (Id,Status_Id,Code,Iname,Lname) values (1,1,'POINTS_ADDED'   ,'Points Added'   ,'إضافة نقاط');

Insert into Cpy_Cod_Notifs (Id,Status_Id,Code,Iname,Lname) values (2,1,'POINTS_DEDUCTED','Points Deducted','خصم نقاط' );

Create Table Cpy_User_Notif
(
  Id             BIGINT     NOT NULL AUTO_INCREMENT,
  User_Id        BIGINT      NOT NULL,
  Notif_Id       BIGINT      NOT NULL,
  Status_Id      BIGINT      Default 1 NOT NULL,
  Rem            VARCHAR(255),
  Ins_User       BIGINT,     Ins_Date DATETIME,
  Upd_User       BIGINT,     Upd_Date DATETIME,
  
  CONSTRAINT Cpy_User_Notif_Pref_PK     PRIMARY KEY (Id),
  CONSTRAINT Cpy_User_Notif_Pref_UK     UNIQUE (User_Id, Notif_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
