-- Ported from Oracle: db/01-Copy/0020_MNG_0133_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


Create Table MNG_Cod_Grp                                -- جدول ترميز فئات التصنيف
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  FColor     VARCHAR(100),                           -- لون النص
  BColor     VARCHAR(100),                           -- لون الخلفية
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT MNG_Cod_Grp_PK        PRIMARY KEY (Id  ),
  CONSTRAINT MNG_Cod_Grp_UK        UNIQUE      (Name),
  CONSTRAINT MNG_Cod_Grp_Status_Fk Foreign Key (Status_Id) References Phs_Cod_Status(Id),
  CONSTRAINT MNG_Cod_Grp_Ins_FK    Foreign Key (Ins_User ) References Cpy_User      (Id),
  CONSTRAINT MNG_Cod_Grp_Upd_FK    Foreign Key (Upd_User ) References Cpy_User      (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into MNG_Cod_Grp (Id,Name) values (0,'-');

Create Table MNG_Cod_Itm                                 -- جدول ترميز بنود التصنيف
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Grp_Id     BIGINT Default 1,                          -- مجموعة الترميز
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT MNG_Cod_Itm_PK        PRIMARY KEY (Id  ),
  CONSTRAINT MNG_Cod_Itm_UK        UNIQUE      (Name),
  CONSTRAINT MNG_Cod_Itm_Group_Fk  Foreign Key (Grp_Id   ) References MNG_Cod_Grp   (Id),
  CONSTRAINT MNG_Cod_Itm_Status_Fk Foreign Key (Status_Id) References Phs_Cod_Status(Id),
  CONSTRAINT MNG_Cod_Itm_Ins_FK    Foreign Key (Ins_User ) References Cpy_User      (Id),
  CONSTRAINT MNG_Cod_Itm_Upd_FK    Foreign Key (Upd_User ) References Cpy_User      (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into MNG_Cod_Itm (Id,Grp_Id,Name) values (0,0,'-');

Create Table MNG_Supp                                   -- دليل المتعاملين
( Id         BIGINT AUTO_INCREMENT,                                    -- مفتاح رئيسي
  Cont_Id    BIGINT,                                    -- مفتاح المتعامل
  Num        VARCHAR(15),                            -- الرقم
  Title      VARCHAR(50),                            -- Title
  LName      VARCHAR(200) NOT NULL,                  -- الاسم محلي
  IName      VARCHAR(200),                           -- الاسم الدولي
  Owner      VARCHAR(200),                           -- اسم المالك
  Contact    VARCHAR(200),                           -- اسم شخص الاتصال
  Status_Id  BIGINT Default 1,                          -- الحالة
  SDate      DATETIME,                                         -- تاريخ بداية الإسناد للمندوب
  EDate      DATETIME,                                         -- تاريخ نهاية الإسناد للمندوب
  Phone      VARCHAR(50),                            -- الهاتف
  Phone1     VARCHAR(50),                            -- 1الهاتف
  Mobile     VARCHAR(50),                            -- الموبايل
  Fax        VARCHAR(50),                            -- الفاكس
  POBox      VARCHAR(50),                            -- صندوق البريد
  PCode      VARCHAR(50),                            -- الرمز البريدي
  Email      VARCHAR(50),                            -- البريد الالكتروني
  Website    VARCHAR(50),                            -- الموقع الالكتروني
  Address    VARCHAR(200),                           -- العنوان
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT MNG_Supp_PK         PRIMARY KEY (Id ),
  CONSTRAINT MNG_Supp_Num_UK     Unique      (Num),
  CONSTRAINT MNG_Supp_Name_UK    Unique      (LName    ),
  CONSTRAINT MNG_Supp_Cont_UK    Unique      (Cont_Id  ),
  CONSTRAINT MNG_Supp_Phone_UK   Unique      (Phone    ),
  CONSTRAINT MNG_Supp_Status_FK  Foreign Key (Status_Id) References Phs_Cod_Status(Id),
  CONSTRAINT MNG_Supp_Ins_FK     Foreign Key (Ins_User ) References Cpy_User      (Id),
  CONSTRAINT MNG_Supp_Upd_FK     Foreign Key (Upd_User ) References Cpy_User      (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO MNG_Supp (Id, Num, LName) VALUES (0, '-', '-');

Create Table MNG_Supp_Class                    -- تصنيف المتعاملين
( Id         BIGINT AUTO_INCREMENT,                                    -- مفتاح رئيسي    
  Supp_Id    BIGINT NOT NULL,                           -- المتعامل
  Grp_Id     BIGINT NOT NULL,                           -- المجموعة
  Itm_Id     BIGINT NOT NULL,                           -- البند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT MNG_Supp_Class_PK       PRIMARY KEY (Id),
  CONSTRAINT MNG_Supp_Class_UK       Unique      (Supp_Id, Grp_Id, Itm_Id),
  CONSTRAINT MNG_Supp_Class_Cont_FK  Foreign Key (Supp_Id ) References MNG_Supp   (Id),
  CONSTRAINT MNG_Supp_Class_Group_FK Foreign Key (Grp_Id  ) References MNG_Cod_Grp(Id),
  CONSTRAINT MNG_Supp_Class_Item_FK  Foreign Key (Itm_Id  ) References MNG_Cod_Itm(Id),
  CONSTRAINT MNG_Supp_Class_Ins_FK   Foreign Key (Ins_User) References Cpy_User   (Id),
  CONSTRAINT MNG_Supp_Class_Upd_FK   Foreign Key (Upd_User) References Cpy_User   (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table MNG_Supp_Cont                           -- جهات اتصال المتعاملين
( Id         BIGINT AUTO_INCREMENT,                                    -- مفتاح رئيسي    
  Supp_Id    BIGINT NOT NULL,                           -- المتعامل
  Gender_Id  BIGINT Default 1,                          -- الجنس
  LName      VARCHAR(200),                           -- الاسم محلي
  IName      VARCHAR(200),                           -- الاسم العالمي
  Position   VARCHAR(100),                           -- المنصب
  Title      VARCHAR(50),                            -- الصفة  
  Phone      VARCHAR(50),                            -- الهاتف
  Mobile     VARCHAR(50),                            -- الموبايل
  Fax        VARCHAR(50),                            -- الفاكس
  Email      VARCHAR(50),                            -- البريد الالكتروني
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT MNG_Supp_Cont_PK        PRIMARY KEY (Id),
  CONSTRAINT MNG_Supp_Cont_Name_UK   Unique      (Supp_Id, LName),
  CONSTRAINT MNG_Supp_Cont_Cont_FK   Foreign Key (Supp_Id  ) References MNG_Supp      (Id),
  CONSTRAINT MNG_Supp_Cont_Gender_FK Foreign Key (Gender_Id) References Phs_Cod_Gender(Id),
  CONSTRAINT MNG_Supp_Cont_Ins_FK    Foreign Key (Ins_User ) References Cpy_User      (Id),
  CONSTRAINT MNG_Supp_Cont_Upd_FK    Foreign Key (Upd_User ) References Cpy_User      (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table MNG_Supp_Bran                           -- فروع المتعاملين
( Id         BIGINT AUTO_INCREMENT,                                    -- مفتاح رئيسي
  Supp_Id    BIGINT NOT NULL,                           -- المتعامل
  LName      VARCHAR(100),                           -- الاسم محلي
  IName      VARCHAR(100),                           -- الاسم العالمي
  Phone      VARCHAR(50),                            -- الهاتف
  Mobile     VARCHAR(50),                            -- الموبايل
  Fax        VARCHAR(50),                            -- الفاكس
  POBox      VARCHAR(50),                            -- صندوق البريد
  PCode      VARCHAR(50),                            -- الرمز البريدي
  Email      VARCHAR(50),                            -- البريد الالكتروني
  Address    VARCHAR(200),                           -- العنوان
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT MNG_Supp_Bran_PK      PRIMARY KEY (Id),
  CONSTRAINT MNG_Supp_Bran_Name_UK Unique      (Supp_Id, LName),
  CONSTRAINT MNG_Supp_Bran_Cont_FK Foreign Key (Supp_Id ) References MNG_Supp(Id),
  CONSTRAINT MNG_Supp_Bran_Ins_FK  Foreign Key (Ins_User) References Cpy_User(Id),
  CONSTRAINT MNG_Supp_Bran_Upd_FK  Foreign Key (Upd_User) References Cpy_User(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
