-- Ported from Oracle: db/01-Copy/0020_MNG_0530_TRIG.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
SET SESSION sql_mode = CONCAT(@@sql_mode, ',NO_AUTO_VALUE_ON_ZERO,PIPES_AS_CONCAT');
USE phsoftme_erp_demo;


-- REVIEW(port): trigger translated mechanically; verify before use.

DELIMITER $$
CREATE TRIGGER
  Mng_TBID_Curn
  Before Insert
  On Mng_Curn
  For Each Row
BEGIN
  If NEW.Id IS NULL Then
    Select /* TODO(port): Mng_Curn_Seq.NEXTVAL - use AUTO_INCREMENT */ NULL, NOW()
      Into NEW.Id, NEW.HDate;
  End If;
END$$
DELIMITER ;

-- REVIEW(port): trigger translated mechanically; verify before use.

DELIMITER $$
CREATE TRIGGER
  Mng_TBID_CurnHist
  Before Insert
  On Mng_CurnHist
  For Each Row
BEGIN
  If NEW.Id IS NULL Then
    Select /* TODO(port): Mng_CurnHist_Seq.NEXTVAL - use AUTO_INCREMENT */ NULL
      Into NEW.Id;
  End If;
  UPDATE Mng_Curn Set Rate=NEW.Rate, HDate=NEW.HDate, Upd_Date=NOW(), Upd_User=NEW.Ins_User WHERE Id=NEW.Curn_Id;
END$$
DELIMITER ;
