-- Ported from Oracle: db/01-Copy/0201_STOR_0101_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


Create Table Stor_Item_Cat                            -- جدول تصانيف المواد
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Vat        DECIMAL(6,2) Default 0,                        -- نسبة VAT
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Image      VARCHAR(100),                           -- الصورة
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT Stor_Item_Cat_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Stor_Item_Cat_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into Stor_Item_Cat (Id,Name) values (0,'-');

Create Table Stor_Item                                    -- دليل المواد
( Id         BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Num        VARCHAR(15) NOT NULL,                   -- رقم المادة
  Part       VARCHAR(15),                            -- الرقم لدى المورد
  LName      VARCHAR(100) NOT NULL,                  -- اسم المادة
  IName      VARCHAR(100) NOT NULL,                  -- اسم المادة
  Status_Id  BIGINT Default 1,                          -- الحالة
  Type_Id    BIGINT Default 1,                          -- النوع
  Method_Id  BIGINT Default 1,                          -- طريقة التعامل
  MCost_Id   BIGINT Default 1,                          -- طريقة التكليف
  Unit_Id    BIGINT Default 1,                          -- الوحدة
  Cat_Id     BIGINT Default 0,                          -- تصنيف المادة
  InSale_Id  BIGINT Default 2 NOT NULL,                 -- هل المادة مشمولة ضمن التنزيلات
  Season_Id  BIGINT Default 2 NOT NULL,                 -- هل المادة ضمن مواد فروع التخفيضات
  Spc1_Id    BIGINT Default 0,   	                     -- تصنيف 1
  Spc2_Id    BIGINT Default 0,                          -- تصنيف 2
  Spc3_Id    BIGINT Default 0,   	                     -- تصنيف 3
  Spc4_Id    BIGINT Default 0,   	                     -- تصنيف 4
  Spc5_Id    BIGINT Default 0,   	                     -- تصنيف 5
  Spc6_Id    BIGINT Default 0,   	                     -- تصنيف 6
  Spc7_Id    BIGINT Default 0,                          -- تصنيف 7
  Spc8_Id    BIGINT Default 0,   	                     -- تصنيف 8
  Spc9_Id    BIGINT Default 0,   	                     -- تصنيف 9
  Spc0_Id    BIGINT Default 0,   	                     -- تصنيف 0
  DWarnty    SMALLINT Default 0 NOT NULL,                 -- أيام الضمان
  NofP       SMALLINT Default 0 NOT NULL,                 -- عدد مرات التسعير
  Vat        DECIMAL(6,2) Default 0,                        -- نسبة VAT
  FQnt       DECIMAL(10,3) Default 1 NOT NULL,              -- كمية المعادلة
  Min_Unit   DECIMAL(10,3) Default 1 NOT NULL,              -- أصغر جزء
  Box        DECIMAL(10,3) Default 1 NOT NULL,              -- سعة الصندوق
  CPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- Current Market سعر السوق الحالي المستهلك
  NPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- Normal سغر المبيع
  DPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- Discount سعر التخفيضات
  SPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- Sale سعر المواسم
  WPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- Wholesale سعر المبيع جملة
  RPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- Retail سعر المبيع مفرق
  HPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- HalfWhole سعر المبيع نصف الجملة
  MPrice     DECIMAL(10,3) Default 0 NOT NULL,              -- Media السعر في مواقع التواصل الاجتماعي كبار العملاء
  CBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- Current Market سعر السوق الحالي المستهلك للصندوق
  NBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- Normal سغر المبيع للصندوق
  DBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- Discount سعر التخفيضات للصندوق
  SBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- Sale سعر المواسم للصندوق
  WBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- Wholesale سعر المبيع جملة للصندوق
  RBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- Retail سعر المبيع مفرق للصندوق
  HBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- HalfWhole سعر المبيع نصف الجملة للصندوق
  MBoxPrice  DECIMAL(10,3) Default 0 NOT NULL,              -- Media السعر في مواقع التواصل الاجتماعي كبار العملاء للصندوق
  Image      VARCHAR(100),                           -- الصورة
  Descr      VARCHAR(1024),                          -- الوصف
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Stor_Item_PK           PRIMARY KEY (Id       ),
  CONSTRAINT Stor_Item_Num_UK       Unique      (Num      ),
  CONSTRAINT Stor_Item_LName_UK     Unique      (LName    ),
  CONSTRAINT Stor_Item_IName_UK     Unique      (IName    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_Item_Class                             -- تصانيف المواد
( Id         BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي    
  Item_Id    BIGINT NOT NULL,                           -- المادة
  Grp_Id     BIGINT NOT NULL,                           -- المجموعة
  Itm_Id     BIGINT NOT NULL,                           -- البند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Stor_Item_Class_PK       PRIMARY KEY (Id),
  CONSTRAINT Stor_Item_Class_UK       Unique      (Item_Id, Grp_Id, Itm_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_Itm_Form                             -- دليل تركيب المواد
( Id         BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Item_Id    BIGINT NOT NULL,                           -- المادة المركبة
  Item_RId   BIGINT NOT NULL,                           -- المادة الداخلة في التركيب
  Qnt        DECIMAL(10,3) Default 0 NOT NULL,              -- الكمية
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Stor_Itm_Form_PK       PRIMARY KEY (Id),
  CONSTRAINT Stor_Itm_Form_Num_UK   Unique      (Item_Id, Item_RId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_Item_Spec                       -- مواصفات المواد
( Id         BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي    
  Item_Id    BIGINT NOT NULL,                           -- المادة
  vTitle     VARCHAR(100) NOT NULL,                       -- العنوان
  vValue     VARCHAR(1024) NOT NULL,                      -- القيمة
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Stor_Item_Spec_PK       PRIMARY KEY (Id),
  CONSTRAINT Stor_Item_Spec_UK       Unique      (Item_Id, vTitle)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_Store                                   -- دليل المخازن
( Id          BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  LName       VARCHAR(100),                          -- اسم المخزن
  IName       VARCHAR(100),                          -- اسم المخزن
  Rem         VARCHAR(100),                          -- ملاحظات
  Status_Id   BIGINT Default 1,                         -- الحالة
  Cost_Id     BIGINT NOT NULL,                          -- مركز الكلفة
  Acc_Id      BIGINT NOT NULL,                          -- حساب المخزن
  CstAcc_Id   BIGINT DEFAULT 0,                         -- حساب التكلفة
  RevAcc_Id   BIGINT DEFAULT 0,                         -- حساب الإيراد
  PVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المشتريات
  SVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المبيعات
  Emp_Id      BIGINT Default 0,                         -- أمين المستودع
  Type_Id     BIGINT Default 2,                         -- نوع المخزن
  Own_Id      BIGINT Default 1,                         -- حالة الملكية 1 ملك الشركة \ 2 إيجار
  Sale_Id     BIGINT Default 2,                         -- هل المستودع مستودع مبيعات أم لا
  SDate       DATETIME,                                        -- تاريخ بداية الوضع بالخدمة أو الإيجار
  EDate       DATETIME,                                        -- تاريخ نهاية الإيجار
  Descr       VARCHAR(512),                          -- توصيف المخزن
  Address     VARCHAR(512),                          -- عنوان المخزن
  Ins_User    BIGINT, Ins_Date     DATETIME,
  Upd_User    BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  Stor_Store_PK         PRIMARY KEY (Id),
  CONSTRAINT  Stor_Store_LName_UK   Unique      (LName     ),
  CONSTRAINT  Stor_Store_IName_UK   Unique      (IName     )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_SMat                        -- دليل مواد مخزن
( Id           BIGINT AUTO_INCREMENT,                                  -- مفتاح رئيسي
  Stor_Id      BIGINT NOT NULL,                         -- المخزن
  Item_Id      BIGINT NOT NULL,                         -- المادة
  Status_Id    BIGINT Default 1,                        -- الحالة
  Loc1_Id      BIGINT Default 0,                        -- مكان تخزين 1
  Loc2_Id      BIGINT DEfault 0,                        -- مكان تخزين 2
  Loc3_Id      BIGINT Default 0,                        -- مكان تخزين 3
  Vat          DECIMAL(6,2) Default 0,                      -- نسبة VAT
  CQnt         DECIMAL(25,3) Default 0,                     -- كمية حالية
  BQnt         DECIMAL(25,3) Default 0,                     -- كمية محجوزة
  CWQnt        DECIMAL(25,3) Default 0,                     -- الوزن الحالي
  CAmt         DECIMAL(25,3) Default 0,                     -- قيمة كمية حالية
  CBAmt        DECIMAL(25,3) Default 0,                     -- قيمة كمية حالية حسب عملة الأساس
  Req_Limit    DECIMAL(25,3) Default 0,                     -- حد الطلب السنوي
  Min_Limit    DECIMAL(25,3) Default 0,                     -- الحد الأدنى السنوي
  Max_Limit    DECIMAL(25,3) Default 0,                     -- الحد الأعلى السنوي
  Ins_User     BIGINT, Ins_Date     DATETIME,
  Upd_User     BIGINT, Upd_Date     DATETIME,
  CONSTRAINT   Stor_SMat_PK         PRIMARY KEY (Id),
  CONSTRAINT   Stor_SMat_UK         Unique      (Stor_Id, Item_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_Acc                                 -- الحسابات الافتراضية
( Id          BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  TrnTyp_Id   BIGINT NOT NULL,                          -- نوع الحركة
  CstAcc_Id   BIGINT NOT NULL,                          -- حساب الكلفة
  RevAcc_Id   BIGINT NOT NULL,                          -- حساب الإيراد
  ComAcc_Id   BIGINT NOT NULL,                          -- حساب العمولة
  DisAcc_Id   BIGINT NOT NULL,                          -- حساب الحسم
  PVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المشتريات
  SVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المبيعات
  Rem         VARCHAR(100),                          -- ملاحظات
  Ins_User    BIGINT, Ins_Date     DATETIME,
  Upd_User    BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  Stor_Acc_PK         PRIMARY KEY (Id  ),
  CONSTRAINT  Stor_Acc_UK         Unique      (TrnTyp_Id )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_Str_Acc                           -- حسابات مستودع
( Id          BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Stor_Id     BIGINT NOT NULL,                          -- المخزن
  TrnTyp_Id   BIGINT NOT NULL,                          -- نوع الحركة
  CstAcc_Id   BIGINT NOT NULL,                          -- حساب الكلفة
  RevAcc_Id   BIGINT NOT NULL,                          -- حساب الإيراد
  ComAcc_Id   BIGINT NOT NULL,                          -- حساب العمولة
  DisAcc_Id   BIGINT NOT NULL,                          -- حساب الحسم
  PVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المشتريات
  SVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المبيعات
  Rem         VARCHAR(100),                          -- ملاحظات
  Ins_User    BIGINT, Ins_Date     DATETIME,
  Upd_User    BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  Stor_Str_Acc_PK         PRIMARY KEY (Id  ),
  CONSTRAINT  Stor_Str_Acc_UK         Unique      (Stor_Id, TrnTyp_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_Cat_Acc                      -- حسابات التصانيف
( Id          BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Cat_Id      BIGINT Default 0,                         -- تصنيف 1
  TrnTyp_Id   BIGINT NOT NULL,                          -- نوع الحركة
  CstAcc_Id   BIGINT NOT NULL,                          -- حساب الكلفة
  RevAcc_Id   BIGINT NOT NULL,                          -- حساب الإيراد
  ComAcc_Id   BIGINT NOT NULL,                          -- حساب العمولة
  DisAcc_Id   BIGINT NOT NULL,                          -- حساب الحسم
  PVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المشتريات
  SVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المبيعات
  Rem         VARCHAR(100),                          -- ملاحظات
  Ins_User    BIGINT, Ins_Date     DATETIME,
  Upd_User    BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  Stor_Cat_Acc_PK         PRIMARY KEY (Id),
  CONSTRAINT  Stor_Cat_Acc_UK         Unique      (Cat_Id, TrnTyp_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_SMat_Acc               -- حسابات مادة في مخزن
( Id          BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Stor_Id     BIGINT NOT NULL,                          -- المخزن
  Item_Id     BIGINT NOT NULL,                          -- المخزن
  TrnTyp_Id   BIGINT NOT NULL,                          -- نوع الحركة
  CstAcc_Id   BIGINT NOT NULL,                          -- حساب الكلفة
  RevAcc_Id   BIGINT NOT NULL,                          -- حساب الإيراد
  ComAcc_Id   BIGINT NOT NULL,                          -- حساب العمولة
  DisAcc_Id   BIGINT NOT NULL,                          -- حساب الحسم
  PVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المشتريات
  SVatAcc_Id  BIGINT DEFAULT 0,                         -- حساب VAT المبيعات
  Rem         VARCHAR(100),                          -- ملاحظات
  Ins_User    BIGINT, Ins_Date     DATETIME,
  Upd_User    BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  Stor_SMat_Acc_PK         PRIMARY KEY (Id  ),
  CONSTRAINT  Stor_SMat_Acc_UK         Unique      (Stor_Id, Item_Id, TrnTyp_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_ICS                      -- دليل الباركود - تصنيف المواد
( Id          BIGINT AUTO_INCREMENT,                                  -- مفتاح رئيسي
  Item_Id     BIGINT NOT NULL,                          -- مفتاح المادة
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  BQnt        DECIMAL(25,3) Default 0,                      -- كمية محجوزة
  CQnt        DECIMAL(25,3) Default 0,                      -- الكمية الحالية
  CCst        DECIMAL(25,3) Default 0,                      -- الكلفة الحالية
  CBCst       DECIMAL(25,3) Default 0,                      -- الكلفة الحالية بعملة الأساس
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  BWQnt       DECIMAL(25,3) Default 0,                      -- الوزن المحجوز
  CWQnt       DECIMAL(25,3) Default 0,                      -- الوزن الحالي
  CPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Current Market سعر السوق الحالي
  NPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Normal سغر المبيع
  DPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Discount سعر التخفيضات
  SPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Sale سعر المواسم
  WPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Wholesale سعر المبيع جملة
  RPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Retail سعر المبيع مفرق
  HPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- HalfWhole سعر المبيع نصف الجملة
  MPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Media السعر في مواقع التواصل الاجتماعي
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  CONSTRAINT  Stor_ICS_PK       PRIMARY KEY (Id),
  CONSTRAINT  Stor_ICS_UK       UNIQUE      (Barcode),
  CONSTRAINT  Stor_ICS_ICS_UK   UNIQUE      (Item_Id, LotSer, Unit_Id, Model_Id, Size_Id, Color_Id, nLength, nWidth, nHeight)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_SICS                 -- دليل تصنيف مواد مستودع
( Id          BIGINT AUTO_INCREMENT,                                  -- مفتاح رئيسي
  Stor_Id     BIGINT NOT NULL,                          -- مفتاح المستودع
  Item_Id     BIGINT NOT NULL,                          -- مفتاح المادة
  ICS_Id      BIGINT NOT NULL,                         -- مفتاح الباركود 
  Loc1_Id     BIGINT Default 0,                         -- الموقع 1
  Loc2_Id     BIGINT Default 0,                         -- الموقع 2
  Loc3_Id     BIGINT Default 0,                         -- الموقع 3
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  BQnt        DECIMAL(25,3) Default 0,                      -- كمية محجوزة
  CQnt        DECIMAL(25,3) Default 0,                      -- الكمية الحالية
  CCst        DECIMAL(25,3) Default 0,                      -- الكلفة الحالية
  CBCst       DECIMAL(25,3) Default 0,                      -- الكلفة الحالية بعملة الأساس
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  BWQnt       DECIMAL(25,3) Default 0,                      -- الوزن المحجوز
  CWQnt       DECIMAL(25,3) Default 0,                      -- الوزن الحالي
  CPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Current Market سعر السوق الحالي
  NPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Normal سغر المبيع
  DPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Discount سعر التخفيضات
  SPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Sale سعر المواسم
  WPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Wholesale سعر المبيع جملة
  RPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Retail سعر المبيع مفرق
  HPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- HalfWhole سعر المبيع نصف الجملة
  MPrice      DECIMAL(25,2) Default 0 NOT NULL,             -- Media السعر في مواقع التواصل الاجتماعي
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  CONSTRAINT  Stor_SICS_PK       PRIMARY KEY (Id  ),
  CONSTRAINT  Stor_SICS_SICS_UK  UNIQUE      (Stor_Id, Item_Id, ICS_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_ActMst                            -- ترويسة الجرد الفعلي
( Id          BIGINT NOT NULL AUTO_INCREMENT,                         -- مفتاح رئيسي
  Period_Id   BIGINT NOT NULL,                          -- فترة العمل
  Stor_Id     BIGINT NOT NULL,                          -- المخزن
  Doc_Id      BIGINT Default 0 NOT NULL,                -- نوع المستند
  Num         INT NOT NULL,                          -- رقم الوثيقة
  dDate       DATETIME,                                        -- التاريخ
  DocN        VARCHAR(15),                                -- رقم المستند
  DocD        DATETIME,                                        -- تاريخ المستند
  Responsible VARCHAR(250),                                -- المسؤول
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  CONSTRAINT  Stor_ActMst_PK        PRIMARY KEY (Id),
  CONSTRAINT  Stor_ActMst_UK        Unique      (Period_Id, Stor_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_ActTrn                             -- بنود الجرد الفعلي
( Id          BIGINT NOT NULL AUTO_INCREMENT,                         -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_ActTrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_InOrdMst                     -- ترويسة أوامر الادخال
( Id         BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Src_Id     BIGINT Default 0 NOT NULL,                 -- أصل الأمر
  TrnTyp_Id  BIGINT NOT NULL,                           -- نوع الحركة
  Status_Id  BIGINT Default 0 NOT NULL,                 -- الحالة
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  Stor_Id    BIGINT NOT NULL,                           -- المخزن
  Cont_Id    BIGINT NOT NULL,                           -- المتعامل
  Doc_Id     BIGINT Default 0 NOT NULL,                 -- نوع المستند
  Curn_Id    BIGINT Default 1,                          -- العملة
  Curn_Rate  DECIMAL(25,8) Default 1,                       -- سعر الصرف
  BCurn_Id   BIGINT Default 1,                          -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                       -- سعر الصرف
  Rel_Id     BIGINT,                                   -- مفتاح مرتبط هو مفتاح الوثيقة التي شكلت الأمر مثل أمر تصنيع إدخال منتج أو مشتريات أو مردود مبيعات
  Fin_Id     BIGINT,                                   -- مفتاح الورقة المالية
  Num        INT NOT NULL,                           -- رقم الوثيقة
  dDate      DATETIME NOT NULL,                                -- التاريخ
  DocN       VARCHAR(15),                                 -- رقم المستند
  DocD       DATETIME,                                         -- تاريخ المستند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT Stor_InOrdMst_PK        PRIMARY KEY (Id),
  CONSTRAINT Stor_InOrdMst_UK        Unique      (Period_Id, Stor_Id, TrnTyp_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Stor_InOrdMst Add CONSTRAINT Stor_InOrdMst_Fin_FK Foreign Key (Fin_Id) References Fin_MCrd(Id);

Create Table Stor_InOrdTrn                      -- بنود أوامر الادخال
( Id          BIGINT AUTO_INCREMENT,                                  -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  Rel_Id      BIGINT,                                  -- مفتاح مرتبط
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  CQnt        DECIMAL(25,3) Default 0,                      -- الكمية الحالية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  CWQnt       DECIMAL(25,3) Default 0,                      -- الوزن الحالي
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price       DECIMAL(25,2) Default 0,                      -- افرادي
  CAmt        DECIMAL(25,2) Default 0,                      -- القيمة قطع
  Amt         DECIMAL(25,2) Default 0,                      -- القيمة
  Cst         DECIMAL(25,2) Default 0,                      -- الكلفة
  BAmt        DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  BCst        DECIMAL(25,2) Default 0,                      -- الكلفة بعملة الأساس
  Vat_Perc    DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value   DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_InOrdTrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_OuOrdMst                    -- ترويسة أوامر الاخراج
( Id         BIGINT NOT NULL AUTO_INCREMENT,                          -- مفتاح رئيسي
  Src_Id     BIGINT Default 0 NOT NULL,                 -- أصل الأمر
  TrnTyp_Id  BIGINT NOT NULL,                           -- نوع الحركة
  Status_Id  BIGINT Default 0 NOT NULL,                 -- الحالة
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  Stor_Id    BIGINT NOT NULL,                           -- المخزن
  Cont_Id    BIGINT NOT NULL,                           -- المتعامل
  Doc_Id     BIGINT Default 0 NOT NULL,                 -- نوع المستند
  Curn_Id    BIGINT Default 1,                          -- العملة
  Curn_Rate  DECIMAL(25,8) Default 1,                       -- سعر الصرف
  BCurn_Id   BIGINT Default 1,                          -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                       -- سعر الصرف
  Rel_Id     BIGINT,                                   -- مفتاح مرتبط هو مفتاح الوثيقة التي شكلت الأمر مثل أمر تصنيع مردود منتج أو مردود مشتريات أو مبيعات
  Fin_Id     BIGINT,                                   -- مفتاح الورقة المالية
  Num        INT NOT NULL,                           -- رقم الوثيقة
  dDate      DATETIME NOT NULL,                                -- التاريخ
  DocN       VARCHAR(15),                                 -- رقم المستند
  DocD       DATETIME,                                         -- تاريخ المستند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT Stor_OuOrdMst_PK        PRIMARY KEY (Id),
  CONSTRAINT Stor_OuOrdMst_UK        Unique      (Period_Id, Stor_Id, TrnTyp_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Stor_OuOrdMst Add CONSTRAINT Stor_OuOrdMst_Fin_FK Foreign Key (Fin_Id) References Fin_MDbt(Id);

Create Table Stor_OuOrdTrn                     -- بنود أوامر الإخراج
( Id          BIGINT NOT NULL AUTO_INCREMENT,                         -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  Rel_Id      BIGINT,                                  -- مفتاح مرتبط
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  CQnt        DECIMAL(25,3) Default 0,                      -- الكمية الحالية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  CWQnt       DECIMAL(25,3) Default 0,                      -- الوزن الحالي
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price       DECIMAL(25,2) Default 0,                      -- افرادي
  CAmt        DECIMAL(25,2) Default 0,                      -- القيمة قطع
  Amt         DECIMAL(25,2) Default 0,                      -- القيمة
  Cst         DECIMAL(25,2) Default 0,                      -- الكلفة
  BAmt        DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  BCst        DECIMAL(25,2) Default 0,                      -- الكلفة بعملة الأساس
  Vat_Perc    DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value   DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_OuOrdTrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_EIMst                   -- ترويسة الادخال
( Id         BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  TrnTyp_Id  BIGINT Default 105,                        -- نوع الحركة
  Status_Id  BIGINT Default 0 NOT NULL,                 -- الحالة
  Stor_Id    BIGINT NOT NULL,                           -- المخزن
  Cont_Id    BIGINT NOT NULL,                           -- المتعامل
  Doc_Id     BIGINT Default 0 NOT NULL,                 -- نوع المستند
  Curn_Id    BIGINT Default 1,                          -- العملة
  Curn_Rate  DECIMAL(25,8) Default 1,                       -- سعر الصرف
  BCurn_Id   BIGINT Default 1,                          -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                       -- سعر الصرف
  Ord_Id     BIGINT,                                   -- مفتاح الأمر
  Fin_Id     BIGINT,                                   -- مفتاح الورقة المالية
  Num        INT NOT NULL,                           -- رقم الوثيقة
  dDate      DATETIME NOT NULL,                                -- التاريخ
  DocN       VARCHAR(15),                                 -- رقم المستند
  DocD       DATETIME,                                         -- تاريخ المستند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT Stor_EIMst_PK        PRIMARY KEY (Id),
  CONSTRAINT Stor_EIMst_UK        Unique      (Period_Id, Stor_Id, TrnTyp_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Stor_EIMst Add CONSTRAINT Stor_EIMst_Fin_FK Foreign Key (Fin_Id) References Fin_MCrd(Id);

Create Table Stor_EITrn                    -- بنود الادخال
( Id          BIGINT AUTO_INCREMENT,                                  -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  TOrd_Id     BIGINT NOT NULL,                         -- مفتاح بند الأمر
  ICS_Id      BIGINT,                                  -- مفتاح الباركود 
  SICS_Id     BIGINT,                                  -- مفتاح الباركود في المستودع
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price       DECIMAL(25,2) Default 0,                      -- افرادي
  CAmt        DECIMAL(25,2) Default 0,                      -- القيمة قطع
  Amt         DECIMAL(25,2) Default 0,                      -- القيمة
  Cst         DECIMAL(25,2) Default 0,                      -- الكلفة
  BAmt        DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  BCst        DECIMAL(25,2) Default 0,                      -- الكلفة بعملة الأساس
  Vat_Perc    DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value   DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_EITrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_EOMst                  -- ترويسة الاخراج
( Id         BIGINT NOT NULL AUTO_INCREMENT,                          -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  TrnTyp_Id  BIGINT Default 205,                        -- نوع الحركة
  Status_Id  BIGINT Default 0 NOT NULL,                 -- الحالة
  Stor_Id    BIGINT NOT NULL,                           -- المخزن
  Cont_Id    BIGINT NOT NULL,                           -- المتعامل
  Doc_Id     BIGINT Default 0 NOT NULL,                 -- نوع المستند
  Curn_Id    BIGINT Default 1,                          -- العملة
  Curn_Rate  DECIMAL(25,8) Default 1,                       -- سعر الصرف
  BCurn_Id   BIGINT Default 1,                          -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                       -- سعر الصرف
  Ord_Id     BIGINT,                                   -- مفتاح الأمر
  Fin_Id     BIGINT,                                   -- مفتاح الورقة المالية
  Num        INT NOT NULL,                           -- رقم الوثيقة
  dDate      DATETIME NOT NULL,                                -- التاريخ
  DocN       VARCHAR(15),                                 -- رقم المستند
  DocD       DATETIME,                                         -- تاريخ المستند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT Stor_EOMst_PK        PRIMARY KEY (Id),
  CONSTRAINT Stor_EOMst_UK        Unique      (Period_Id, TrnTyp_Id, Stor_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Stor_EOMst Add CONSTRAINT Stor_EOMst_Fin_FK Foreign Key (Fin_Id) References Fin_MDbt(Id);

Create Table Stor_EOTrn                   -- بنود الإخراج
( Id          BIGINT NOT NULL AUTO_INCREMENT,                         -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  TOrd_Id     BIGINT NOT NULL,                         -- مفتاح بند الأمر
  ICS_Id      BIGINT,                                  -- مفتاح الباركود 
  SICS_Id     BIGINT,                                  -- مفتاح الباركود في المستودع
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price       DECIMAL(25,2) Default 0,                      -- افرادي
  CAmt        DECIMAL(25,2) Default 0,                      -- القيمة قطع
  Amt         DECIMAL(25,2) Default 0,                      -- القيمة
  Cst         DECIMAL(25,2) Default 0,                      -- الكلفة
  BAmt        DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  BCst        DECIMAL(25,2) Default 0,                      -- الكلفة بعملة الأساس
  Vat_Perc    DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value   DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_EOTrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_InMst                           -- ترويسة الادخال
( Id         BIGINT AUTO_INCREMENT,                                   -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  TrnTyp_Id  BIGINT Default 100,                        -- نوع الحركة
  Stor_Id    BIGINT NOT NULL,                           -- المخزن
  Cont_Id    BIGINT NOT NULL,                           -- المتعامل
  Doc_Id     BIGINT Default 0 NOT NULL,                 -- نوع المستند
  Curn_Id    BIGINT Default 1,                          -- العملة
  Curn_Rate  DECIMAL(25,8) Default 1,                       -- سعر الصرف
  BCurn_Id   BIGINT Default 1,                          -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                       -- سعر الصرف
  Fin_Id     BIGINT,                                   -- مفتاح الورقة المالية
  Num        INT NOT NULL,                           -- رقم الوثيقة
  dDate      DATETIME NOT NULL,                                -- التاريخ
  DocN       VARCHAR(15),                                 -- رقم المستند
  DocD       DATETIME,                                         -- تاريخ المستند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT Stor_InMst_PK        PRIMARY KEY (Id),
  CONSTRAINT Stor_InMst_UK        Unique      (Period_Id, Stor_Id, TrnTyp_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Stor_InMst Add CONSTRAINT Stor_InMst_Fin_FK Foreign Key (Fin_Id) References Fin_MCrd(Id);

Create Table Stor_InTrn                            -- بنود الادخال
( Id          BIGINT AUTO_INCREMENT,                                  -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  ICS_Id      BIGINT,                                  -- مفتاح الباركود 
  SICS_Id     BIGINT,                                  -- مفتاح الباركود في المستودع
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price       DECIMAL(25,2) Default 0,                      -- افرادي
  CAmt        DECIMAL(25,2) Default 0,                      -- القيمة قطع
  Amt         DECIMAL(25,2) Default 0,                      -- القيمة
  Cst         DECIMAL(25,2) Default 0,                      -- الكلفة
  BAmt        DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  BCst        DECIMAL(25,2) Default 0,                      -- الكلفة بعملة الأساس
  Vat_Perc    DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value   DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_InTrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_OuMst                          -- ترويسة الاخراج
( Id         BIGINT NOT NULL AUTO_INCREMENT,                          -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  TrnTyp_Id  BIGINT Default 200,                        -- نوع الحركة
  Stor_Id    BIGINT NOT NULL,                           -- المخزن
  Cont_Id    BIGINT NOT NULL,                           -- المتعامل
  Doc_Id     BIGINT Default 0 NOT NULL,                 -- نوع المستند
  Curn_Id    BIGINT Default 1,                          -- العملة
  Curn_Rate  DECIMAL(25,8) Default 1,                       -- سعر الصرف
  BCurn_Id   BIGINT Default 1,                          -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                       -- سعر الصرف
  Ord_Id     BIGINT,                                   -- مفتاح الأمر
  Fin_Id     BIGINT,                                   -- مفتاح الورقة المالية
  Num        INT NOT NULL,                           -- رقم الوثيقة
  dDate      DATETIME NOT NULL,                                -- التاريخ
  DocN       VARCHAR(15),                                 -- رقم المستند
  DocD       DATETIME,                                         -- تاريخ المستند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT Stor_OuMst_PK        PRIMARY KEY (Id),
  CONSTRAINT Stor_OuMst_UK        Unique      (Period_Id, Stor_Id, TrnTyp_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Stor_OuMst Add CONSTRAINT Stor_OuMst_Fin_FK Foreign Key (Fin_Id) References Fin_MDbt(Id);

Create Table Stor_OuTrn                           -- بنود الإخراج
( Id          BIGINT NOT NULL AUTO_INCREMENT,                         -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  ICS_Id      BIGINT,                                  -- مفتاح الباركود 
  SICS_Id     BIGINT,                                  -- مفتاح الباركود في المستودع
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price       DECIMAL(25,2) Default 0,                      -- افرادي
  CAmt        DECIMAL(25,2) Default 0,                      -- القيمة قطع
  Amt         DECIMAL(25,2) Default 0,                      -- القيمة
  Cst         DECIMAL(25,2) Default 0,                      -- الكلفة
  BAmt        DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  BCst        DECIMAL(25,2) Default 0,                      -- الكلفة بعملة الأساس
  Vat_Perc    DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value   DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_OuTrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_TrMst                          -- ترويسة الترحيل
( Id         BIGINT NOT NULL AUTO_INCREMENT,                          -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  TrnTypF_Id BIGINT Default 250,                        -- نوع الحركة
  TrnTypT_Id BIGINT Default 150,                        -- نوع الحركة
  StorF_Id   BIGINT NOT NULL,                           -- المخزن المرحل منه
  StorT_Id   BIGINT NOT NULL,                           -- المخزن المرحل إليه
  Fin_Id     BIGINT,                                   -- مفتاح الورقة المالية
  Doc_Id     BIGINT Default 0 NOT NULL,                 -- نوع المستند
  Curn_Id    BIGINT Default 1,                          -- العملة
  Curn_Rate  DECIMAL(25,8) Default 1,                       -- سعر الصرف
  BCurn_Id   BIGINT Default 1,                          -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                       -- سعر الصرف
  Num        INT NOT NULL,                           -- رقم الوثيقة
  dDate      DATETIME NOT NULL,                                -- التاريخ
  DocN       VARCHAR(15),                                 -- رقم المستند
  DocD       DATETIME,                                         -- تاريخ المستند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT Stor_TrMst_PK         PRIMARY KEY (Id),
  CONSTRAINT Stor_TrMst_UK         Unique      (Period_Id, StorF_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Alter Table Stor_TrMst Add CONSTRAINT Stor_TrMst_Fin_FK Foreign Key (Fin_Id) References Fin_MDbt(Id);

Create Table Stor_TrTrn                           -- بنود الترحيل
( Id          BIGINT NOT NULL AUTO_INCREMENT,                         -- مفتاح رئيسي
  Mst_Id      BIGINT NOT NULL,                         -- مفتاح الأب
  Item_Id     BIGINT NOT NULL,                          -- المادة
  ICS_Id      BIGINT,                                  -- مفتاح الباركود 
  Sics_Fid    BIGINT,                                  -- مفتاح الباركود في المستودع
  SICS_TId    BIGINT,                                  -- مفتاح الباركود في المستودع
  Unit_Id     BIGINT Default 0,                         -- الوحدة
  Model_Id    BIGINT Default 0,                         -- الموديل
  Color_Id    BIGINT Default 0,                         -- اللون 
  Size_Id     BIGINT Default 0,                         -- القياس 
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  Qnt         DECIMAL(25,3) Default 0,                      -- الكمية
  CQnt        DECIMAL(25,3) Default 0,                      -- الكمية الحالية
  SQnt        DECIMAL(25,3) Default 0,                      -- الكمية بوحدة التخزين
  WQnt        DECIMAL(25,3) Default 0,                      -- الوزن
  CWQnt       DECIMAL(25,3) Default 0,                      -- الوزن الحالي
  SWQnt       DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price       DECIMAL(25,2) Default 0,                      -- افرادي
  CAmt        DECIMAL(25,2) Default 0,                      -- القيمة قطع
  Amt         DECIMAL(25,2) Default 0,                      -- القيمة
  Cst         DECIMAL(25,2) Default 0,                      -- الكلفة
  BAmt        DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  BCst        DECIMAL(25,2) Default 0,                      -- الكلفة بعملة الأساس
  Vat_Perc    DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value   DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  nLength     DECIMAL(25,2) Default 0,                      -- الطول
  nWidth      DECIMAL(25,2) Default 0,                      -- العرض
  nHeight     DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode     VARCHAR(50),                           -- مسطرة الترميز
  LotSer      VARCHAR(50) Default '_',               -- طبخة/مسلسل
  SDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ بداية
  EDate       DATETIME DEFAULT (STR_TO_DATE('01-01-1900', '%d-%m-%Y')) NOT NULL,-- تاريخ نهاية
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Stor_TrTrn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_ChLocMst                   -- ترويسة تعديل موقع مادة في مستودع
( Id         BIGINT Not Null AUTO_INCREMENT,                           -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                           -- فترة العمل
  Stor_Id    BIGINT NOT NULL,                           -- المخزن
  Doc_Id     BIGINT Default 0,                          -- المستند
  Docn       BIGINT,                                   -- رقم الستند
  Docd       DATETIME,                                         -- تاريخ المستند
  Num        BIGINT,                                   -- رقم الوثيقة
  dDate      DATETIME,                                         -- التاريخ
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  Constraint Stor_ChLocMst_PK        Primary Key (Id),
  Constraint Stor_ChLocMst_Uk        Unique      (Period_Id, Stor_Id, Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Stor_ChLocTrn                    -- بنود تعديل موقع مادة في مستودع
( Id          BIGINT Not Null AUTO_INCREMENT,                         -- مفتاح رئيسي
  Mst_Id      BIGINT Not Null,                          -- مفتاح الأب
  Item_Id     BIGINT Not Null,                          -- المادة
  Sics_Id     BIGINT,                                  -- مفتاح الباركود في المستودع
  Ord         MEDIUMINT Default 0,                         -- مسلسل
  OLoc1_Id    BIGINT Default 0,                         -- الموقع 1 السابق
  OLoc2_Id    BIGINT Default 0,                         -- الموقع 2 السابق
  OLoc3_Id    BIGINT Default 0,                         -- الموقع 3 السابق
  NLoc1_Id    BIGINT Default 0,                         -- الموقع 1 الجديد
  NLoc2_Id    BIGINT Default 0,                         -- الموقع 2 الجديد
  NLoc3_Id    BIGINT Default 0,                         -- الموقع 3 الجديد
  Rem         VARCHAR(250),                          -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  Constraint  Stor_ChLocTrn_PK       Primary Key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
