-- Ported from Oracle: db/01-Copy/1100_EMP_FIX_FKEY.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

USE phsoftme_erp_demo;


Alter Table Fix_ResMst Add CONSTRAINT Fix_ResMst_Emp_FK Foreign Key (Emp_Id) References Emp_Emp(Id);
