-- Ported from Oracle: db/01-Copy/1100_EMP_0103_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


Create Table Emp_Att                           -- ملخص الدوام
( Id          BIGINT AUTO_INCREMENT,                             -- مفتاح رئيسي
  dDate       DATETIME,                                   -- التاريخ
  EName       VARCHAR(100),                     -- اسم الموظف
  ENum        INT,                              -- رقم العامل
  nAdd        DECIMAL(25,3) Default 0,                 -- الإضافي
  nAbs        DECIMAL(25,3) Default 0,                 -- الغياب
  nSik        DECIMAL(25,3) Default 0,                 -- المرض
  nDel        DECIMAL(25,3) Default 0,                 -- التأخير
  Rem         VARCHAR(100),                     -- ملاحظات
  Constraint  Emp_Attend_PK     Primary Key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_FngrPrnt                         -- حركات الأجهزة
( Id           BIGINT AUTO_INCREMENT,                            -- مفتاح رئيسي
  nSession     BIGINT,                            -- جلسة العمل
  MNUM         INT,                             -- رقم الجهاز
  ENUM         INT,                             -- رقم العامل
  VMODE        INT,                             -- نمط التدقيق
  OMODE        INT,                             -- نمط الخروج
  IOMODE       INT,                             -- حالة الدخول أو الخروج 1 دخول\2 خروج\3 مطعم
  vTIME        VARCHAR(100),                    -- الوقت
  dDate        DATETIME DEFAULT (NOW()),                  -- التاريخ
  nHour        TINYINT Default 0,                   -- الساعة
  nMinute      TINYINT Default 0,                   -- الدقيقة
  Constraint   Emp_Fngr_PK Primary Key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_FPrint                     -- حركات الأجهزة
( Id            BIGINT AUTO_INCREMENT,                           -- مفتاح رئيسي
  nSession      BIGINT Default 0,                 -- جلسة العمل
  MNum          INT Default 1,                  -- رقم الجهاز
  ENum          INT,                            -- رقم العامل
  VMode         INT Default 0,                  -- نمط التدقيق
  OMode         INT Default 0,                  -- نمط الخروج
  IOMode        INT Default 0,                  -- الحالة 0 غير محدد\1 دخول\2 خروج\3 مطعم
  vTime         VARCHAR(100),                   -- الوقت
  dDate         DATETIME DEFAULT (NOW()),                 -- التاريخ
  nHour         TINYINT Default 0,                  -- الساعة
  nMinute       TINYINT Default 0,                  -- الدقيقة
  Constraint    Emp_FPrint_PK Primary Key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_Day                                -- دليل الأيام
( Id          BIGINT AUTO_INCREMENT,                             -- مفتاح رئيسي
  dDate       DATETIME DEFAULT (NOW()),                   -- التاريخ
  Commit_Id   BIGINT Default 0,                    -- حالة التثبيت
  Rem         VARCHAR(100),                     -- ملاحظات
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  Constraint  Emp_Day_PK      Primary Key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_DayAttFile                  -- ملفات الدوام
( Id          BIGINT AUTO_INCREMENT,                             -- مفتاح رئيسي
  Day_Id      BIGINT NOT NULL,                    -- مفتاح اليوم
  Name        VARCHAR(100),                     -- اسم الملف
  vFile       VARCHAR(100),                     -- اسم الملف
  Rem         VARCHAR(250),                     -- ملاحظات
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  Constraint  Emp_DayAtt_PK      Primary Key (Id  ),
  Constraint  Emp_DayAtt_Name_UK Unique      (Day_Id, Name ),
  Constraint  Emp_DayAtt_File_UK Unique      (Day_Id, vFile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_Ent                             -- ساعات الدخول ليوم
( Id          BIGINT AUTO_INCREMENT,                             -- مفتاح رئيسي
  Day_Id      BIGINT NOT NULL,                    -- مفتاح اليوم
  Emp_Id      BIGINT NOT NULL,                     -- العامل
  nHour       TINYINT Default 0,                    -- الساعة
  nMinute     TINYINT Default 0,                    -- الدقيقة
  Rem         VARCHAR(100),                     -- ملاحظات
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  Constraint  Emp_Ent_PK      Primary Key (Id),
  Constraint  Emp_Ent_Time_UK Unique      (Day_Id, Emp_Id, nHour, nMinute )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_Out                             -- ساعات الخروج ليوم
( Id          BIGINT AUTO_INCREMENT,                             -- مفتاح رئيسي
  Day_Id      BIGINT NOT NULL,                    -- مفتاح اليوم
  Emp_Id      BIGINT NOT NULL,                     -- العامل
  nHour       TINYINT Default 0,                    -- الساعة
  nMinute     TINYINT Default 0,                    -- الدقيقة
  Rem         VARCHAR(100),                     -- ملاحظات
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  Constraint  Emp_Out_PK      Primary Key (Id),
  Constraint  Emp_Out_Time_UK Unique      (Day_Id, Emp_Id, nHour, nMinute)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_EDEO               -- ساعات الدخول و الخروج ليوم
( Id            BIGINT AUTO_INCREMENT,                           -- مفتاح رئيسي
  Emp_Id        BIGINT NOT NULL,                 -- العامل
  Day_Id        BIGINT NOT NULL,                 -- مفتاح اليوم
  WGrp_Id       BIGINT NOT NULL,                 -- مجموعة الدوام
  Audit_Id      BIGINT Default 2,                 -- حالة التدقيق \ 0 غير مدقق \ 1 مدقق
  Excuse_Id     BIGINT Default 2,                 -- حالة السماح أو تبرير أي مخالفة ضمن السطر \ 1 سماح \ 0 حسب المخالفة
  WeekEnd_Id    BIGINT Default 2,                 -- يوم عطلة اسبوعية \ 1 عطلة اسبوعية \ 0 يوم دوام
  HolyDay_Id    BIGINT Default 2,                 -- يوم عطلة \ 1 عطلة \ 0 دوام
  Off_Id        BIGINT Default 2,                 -- يوم غياب \ 1 غياب \ 0 دوام
  Sick_Id       BIGINT Default 2,                 -- يوم مرض \ 1  مرض \ 0 دوام
  Vac_Id        BIGINT Default 2,                 -- يوم إجازة \ 1 إجازة \ 0 دوام
  NPay_Id       BIGINT Default 2,                 -- يوم دون أجر \ 1 دون أجر \ 0 دوام
  VPar_Id       BIGINT Default 2,                 -- يوم أمومة \ 1 أمومة \ 0 دوام
  nHNPay        SMALLINT Default 0,                 -- عدد دقائق الإجازة الساعية دون أجر
  nHPar         SMALLINT Default 0,                 -- عدد دقائق الإجازة الساعية أمومة
  nHVac         SMALLINT Default 0,                 -- عدد دقائق الإجازة الساعية
  nEPun         TINYINT Default 0,                 -- حالة تنفيذ عقوبة الدخول المبكر أو المتأخر
  nOPun         TINYINT Default 0,                 -- حالة تنفيذ عقوبة الخروج المبكر أو المتأخر
  nAddH         TINYINT Default 0,                 -- عدد ساعات العمل المطلوب ليحسب الإضافي بعدها
  nAddM         TINYINT Default 0,                 -- عدد دقائق العمل المطلوب ليحسب الإضافي بعدها
  nAdd          SMALLINT Default 0,                 -- الإضافي
  nRAdd         SMALLINT Default 0,                 -- الإضافي المطلوب
  nAbs          SMALLINT Default 0,                 -- الغياب اليومي
  nHAbs         SMALLINT Default 0,                 -- الغياب الساعي مجموع ساعات
  nHCAbs        SMALLINT Default 0,                 -- الغياب الساعي عدد مرات
  nSik          SMALLINT Default 0,                 -- المرض
  nDel          SMALLINT Default 0,                 -- التأخير
  nErr          TINYINT Default 0,                 -- رمز الخطأ 0 لايوجد خطأ
  nCode         MEDIUMINT Default 0,                 -- رمز الحالة ليتم التجميع عليها في الإحصائيات
  Rem           VARCHAR(100),                   -- ملاحظات
  ARem          VARCHAR(100),                   -- ملاحظات البرنامج
  Ins_User      BIGINT, Ins_Date   DATETIME,
  Upd_User      BIGINT, Upd_Date   DATETIME,
  Constraint    Emp_EDeo_PK          Primary Key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_EDEOF             -- ساعات الدخول و الخروج ليوم
( Id            BIGINT AUTO_INCREMENT,                           -- مفتاح رئيسي
  EDeo_Id       BIGINT NOT NULL,                  -- مفتاح الأب
  nHour         TINYINT Default 0,                  -- ساعة
  nMinute       TINYINT Default 0,                  -- دقيقة
  Type_Id       BIGINT Default 1,                  -- النوع 1 دخول / 2 خروج في الأجهزة التي يمكن تحديد نوع البصمة
  Rem           VARCHAR(100),                   -- ملاحظات
  Ins_User      BIGINT, Ins_Date   DATETIME,
  Upd_User      BIGINT, Upd_Date   DATETIME,
  Constraint    Emp_EDeoF_PK         Primary Key (Id),
  Constraint    Emp_EDeoF_ETime_UK   Unique      (EDeo_Id, nHour, nMinute)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_EDEOM                   -- ساعات الدخول و الخروج ليوم
( Id            BIGINT AUTO_INCREMENT,                           -- مفتاح رئيسي
  EDeo_Id       BIGINT NOT NULL,                 -- مفتاح الأب
  Audit_Id      BIGINT Default 2,                 -- حالة التدقيق \ 0 غير مدقق \ 1 مدقق
  Excuse_Id     BIGINT Default 2,                 -- حالة السماح أو تبرير أي مخالفة ضمن السطر \ 1 سماح \ 0 حسب المخالفة
  Type_Id       BIGINT Default 0,                 -- النوع / 1 دوام / 2 إضافي / 3 إجازة / 4 مرض
  EH            TINYINT Default 0,                 -- ساعة الدخول
  EM            TINYINT Default 0,                 -- دقيقة الدخول
  OH            TINYINT Default 0,                 -- ساعة الخروج
  OM            TINYINT Default 0,                 -- دقيقة الخروج
  Rem           VARCHAR(100),                   -- ملاحظات
  Ins_User      BIGINT, Ins_Date   DATETIME,
  Upd_User      BIGINT, Upd_Date   DATETIME,
  Constraint    Emp_EDeoM_PK        Primary Key (Id),
  Constraint    Emp_EDeoM_ETime_UK  Unique      (EDeo_Id, EH, EM),
  Constraint    Emp_EDeoM_OTime_UK  Unique      (EDeo_Id, OH, OM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Emp_DEO                         -- ساعات الدخول و الخروج ليوم
( Id            BIGINT AUTO_INCREMENT,                           -- مفتاح رئيسي
  Day_Id        BIGINT NOT NULL,                  -- مفتاح اليوم
  Emp_Id        BIGINT NOT NULL,                   -- العامل
  WGrp_Id       BIGINT NOT NULL,                   -- مجموعة الدوام
  Audit_Id      BIGINT Default 2,                  -- حالة التدقيق \ 0 غير مدقق \ 1 مدقق
  Excuse_Id     BIGINT Default 2,                  -- حالة السماح أو تبرير أي مخالفة ضمن السطر \ 1 سماح \ 0 حسب المخالفة
  WeekEnd_Id    BIGINT Default 2,                  -- يوم جمعة \ 1 جمعة \ 0 يوم دوام
  HolyDay_Id    BIGINT Default 2,                  -- يوم عطلة \ 1 عطلة \ 0 دوام
  Vacation_Id   BIGINT Default 2,                  -- إجازة \ 1 إجازة \ 0 دوام
  Mission_Id    BIGINT Default 2,                  -- مهمة \ 1 مهمة \ 0 دوام
  MHour         TINYINT Default 0,                  -- ساعات المهمة
  MMinute       TINYINT Default 0,                  -- دقائق المهمة
  HVacation_Id  BIGINT Default 2,                  -- إجازة ساعية \ 1 إجازة \ 0 دوام
  VHour         TINYINT Default 0,                  -- ساعات الإجازة
  VMinute       TINYINT Default 0,                  -- دقائق الإجازة
  Payed_Id      BIGINT Default 2,                  -- حالة الدفع \ 1 غير مدفوع \ 0 مدفوع
  Sick_Id       BIGINT Default 2,                  -- يوم مرض \ 1 مرض \ 0 دوام
  DayOff_Id     BIGINT Default 2,                  -- يوم غياب \ 1 غياب \ 0 دوام
  EPun_Id       BIGINT Default 2,                  -- حالة تنفيذ عقوبة الدخول المبكر أو المتأخر
  OPun_Id       BIGINT Default 2,                  -- حالة تنفيذ عقوبة الخروج المبكر أو المتأخر
  E1Hour        TINYINT Default 0,                  -- ساعة الدخول1
  E1Minute      TINYINT Default 0,                  -- دقيقة الدخول1
  O1Hour        TINYINT Default 0,                  -- ساعة الخروج1
  O1Minute      TINYINT Default 0,                  -- دقيقة الخروج1
  E2Hour        TINYINT Default 0,                  -- ساعة الدخول2
  E2Minute      TINYINT Default 0,                  -- دقيقة الدخول2
  O2Hour        TINYINT Default 0,                  -- ساعة الخروج2
  O2Minute      TINYINT Default 0,                  -- دقيقة الخروج2
  LEHour        TINYINT Default 0,                  -- ساعة تأخير
  LEMinute      TINYINT Default 0,                  -- دقيقة تأخير
  LOHour        TINYINT Default 0,                  -- ساعة خروج مبكر
  LOMinute      TINYINT Default 0,                  -- دقيقة خروج مبكر
  BEHour        TINYINT Default 0,                  -- ساعة دخول مبكر
  BEMinute      TINYINT Default 0,                  -- دقيقة دخول مبكر
  AOHour        TINYINT Default 0,                  -- ساعة خروج متأخر
  AOMinute      TINYINT Default 0,                  -- دقيقة خروج متأخر
  DAHour        TINYINT Default 0,                  -- ساعة إضافي نهاري
  DAMinute      TINYINT Default 0,                  -- دقيقة إضافي نهاري
  NAHour        TINYINT Default 0,                  -- ساعة إضافي ليلي
  NAMinute      TINYINT Default 0,                  -- دقيقة إضافي ليلي
  AHour         TINYINT Default 0,                  -- ساعة إضافي
  AMinute       TINYINT Default 0,                  -- دقيقة إضافي
  THour         TINYINT Default 0,                  -- مجموع الساعات
  TMinute       TINYINT Default 0,                  -- مجموع الدقائق
  AddH          TINYINT Default 0,                  -- عدد ساعات العمل المطلوب ليحسب الإضافي بعدها
  AddM          TINYINT Default 0,                  -- عدد دقائق العمل المطلوب ليحسب الإضافي بعدها
  nE1H          TINYINT Default 0,                  -- ساعة الدخول1
  nE1M          TINYINT Default 0,                  -- دقيقة الدخول1
  nO1H          TINYINT Default 0,                  -- ساعة الخروج1
  nO1M          TINYINT Default 0,                  -- دقيقة الخروج1
  nE2H          TINYINT Default 0,                  -- ساعة الدخول2
  nE2M          TINYINT Default 0,                  -- دقيقة الدخول2
  nO2H          TINYINT Default 0,                  -- ساعة الخروج2
  nO2M          TINYINT Default 0,                  -- دقيقة الخروج2
  nAdd          SMALLINT Default 0,                  -- الإضافي
  nAddReq       SMALLINT Default 0,                  -- الإضافي المطلوب
  nAbs          SMALLINT Default 0,                  -- الغياب
  nSik          SMALLINT Default 0,                  -- المرض
  nDel          SMALLINT Default 0,                  -- التأخير
  Rem           VARCHAR(100),                   -- ملاحظات
  Ins_User      BIGINT, Ins_Date   DATETIME,
  Upd_User      BIGINT, Upd_Date   DATETIME,
  Constraint    Emp_DEO_PK        Primary Key (Id),
  Constraint    Emp_DEO_ETime1_UK Unique      (Day_Id, Emp_Id, E1Hour, E1Minute),
  Constraint    Emp_DEO_ETime2_UK Unique      (Day_Id, Emp_Id, E2Hour, E2Minute),
  Constraint    Emp_DEO_OTime1_UK Unique      (Day_Id, Emp_Id, O1Hour, O1Minute),
  Constraint    Emp_DEO_OTime2_UK Unique      (Day_Id, Emp_Id, O2Hour, O2Minute)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
