-- Ported from Oracle: db/01-Copy/1401_PUR_0100_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


-- set Pagesize 1000
-- select 'Drop table '   || table_name    || ';' from user_tables    where table_name    like 'PUR%' ;
-- select 'Drop Synonym ' || Synonym_name  || ';' from user_Synonyms  where Synonym_name  like 'PUR%' ;
-- select 'Drop Sequence '|| Sequence_name || ';' from user_Sequences where Sequence_name like 'PUR%' ;
-- select 'Drop View '    || View_name     || ';' from user_Views     where View_name     like 'PUR%' ;
-- --------------------------------------------------------------------------------------------------
Create Table Pur_Cod_Status                        -- جدول ترميز حالة الأمر
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT Pur_Cod_Status_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Pur_Cod_Status_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into Pur_Cod_Status (Id,Name) values (0,'-'       );

Insert into Pur_Cod_Status (Id,Name) values (1,'Commited');

Insert into Pur_Cod_Status (Id,Name) values (2,'Freez'   );

Create Table Pur_MPur                             -- جدول ترويسة الشراء
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                  -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                          -- فترة العمل
  Status_Id  BIGINT Default 0 NOT NULL,                -- الحالة
  Cont_Id    BIGINT NOT NULL,				                  -- المتعامل/المورد
  Curn_Id    BIGINT NOT NULL,                          -- العملة
  Acc_Id     BIGINT NOT NULL,                          -- الحساب
  Doc_Id     BIGINT Default 0 NOT NULL,                -- نوع المستند
  BCurn_Id   BIGINT Default 1,                         -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                      -- سعر الصرف
  Rel_Id     BIGINT,                                  -- مفتاح الأمر المشكل نتيجة تثبيت هذه الحركة
  Fin_Id     BIGINT,                                  -- مفتاح الورقة المالية
  Rate       BIGINT Default 0 NOT NULL,             -- سعر الصرف
  Num        BIGINT Default 0,                        -- الرقم
  dDate      DATETIME NOT NULL,                               -- التاريخ
  DocN       VARCHAR(15),                                -- رقم المستند
  DocD       DATETIME,                                        -- تاريخ المستند
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Pur_MPur_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Pur_TPur                             -- جدول بنود الشراء
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                  -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,				                  -- مفتاح الأب
  Item_Id    BIGINT NOT NULL,				                  -- المادة
  Ord        MEDIUMINT Default 0,                         -- مسلسل
  Qnt        DECIMAL(25,3) Default 0,                      -- الكمية
  WQnt       DECIMAL(25,3) Default 0,                      -- الوزن
  SWQnt      DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price      DECIMAL(25,2) Default 0,                      -- السعر
  CAmt       DECIMAL(25,2) Default 0,                      -- القيمة بالعملة
  Amt        DECIMAL(25,2) Default 0,                      -- القيمة محلي
  BAmt       DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  Vat_Perc   DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value  DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  ICS_Id     BIGINT,                                  -- مفتاح الباركود 
  SICS_Id    BIGINT,                                  -- مفتاح الباركود في المستودع
  Unit_Id    BIGINT Default 0,                         -- الوحدة
  Model_Id   BIGINT Default 0,                         -- الموديل
  Color_Id   BIGINT Default 0,                         -- اللون 
  Size_Id    BIGINT Default 0,                         -- القياس 
  nLength    DECIMAL(25,2) Default 0,                      -- الطول
  nWidth     DECIMAL(25,2) Default 0,                      -- العرض
  nHeight    DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode    VARCHAR(50),                           -- مسطرة الترميز
  LotSer     VARCHAR(50),                           -- طبخة/مسلسل
  SDate      DATETIME,                                        -- تاريخ بداية
  EDate      DATETIME,                                        -- تاريخ نهاية
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Pur_TPur_PK       PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Pur_MRet                               -- جدول ترويسة المرتجع
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                  -- مفتاح رئيسي
  Period_Id  BIGINT NOT NULL,                          -- فترة العمل
  Status_Id  BIGINT Default 0 NOT NULL,                -- الحالة
  Cont_Id    BIGINT NOT NULL,				                  -- المتعامل/المورد
  Curn_Id    BIGINT NOT NULL,                          -- العملة
  Acc_Id     BIGINT NOT NULL,                          -- الحساب
  Doc_Id     BIGINT Default 0 NOT NULL,                -- نوع المستند
  BCurn_Id   BIGINT Default 1,                         -- عملة الأساس
  BCurn_Rate DECIMAL(25,8) Default 1,                      -- سعر الصرف
  Rel_Id     BIGINT,                                  -- مفتاح الأمر المشكل نتيجة تثبيت هذه الحركة
  Fin_Id     BIGINT,                                  -- مفتاح الورقة المالية
  Rate       BIGINT Default 0 NOT NULL,             -- سعر الصرف
  Num        BIGINT Default 0,                        -- الرقم
  dDate      DATETIME NOT NULL,                               -- التاريخ
  DocN       VARCHAR(15),                                -- رقم المستند
  DocD       DATETIME,                                        -- تاريخ المستند
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Pur_MRet_PK      PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Pur_TRet                             -- جدول بنود الشراء
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                  -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,				                  -- مفتاح الأب
  Item_Id    BIGINT NOT NULL,				                  -- المادة
  Ord        MEDIUMINT Default 0,                         -- مسلسل
  Qnt        DECIMAL(25,3) Default 0,                      -- الكمية
  WQnt       DECIMAL(25,3) Default 0,                      -- الوزن
  SWQnt      DECIMAL(25,3) Default 0,                      -- الوزن بوحدة التخزين
  Price      DECIMAL(25,2) Default 0,                      -- السعر
  CAmt       DECIMAL(25,2) Default 0,                      -- القيمة بالعملة
  Amt        DECIMAL(25,2) Default 0,                      -- القيمة محلي
  BAmt       DECIMAL(25,2) Default 0,                      -- القيمة بعملة الأساس
  Vat_Perc   DECIMAL(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value  DECIMAL(25,2) Default 0,                      -- فيمة الVAT
  ICS_Id     BIGINT,                                  -- مفتاح الباركود 
  SICS_Id    BIGINT,                                  -- مفتاح الباركود في المستودع
  Unit_Id    BIGINT Default 0,                         -- الوحدة
  Model_Id   BIGINT Default 0,                         -- الموديل
  Color_Id   BIGINT Default 0,                         -- اللون 
  Size_Id    BIGINT Default 0,                         -- القياس 
  nLength    DECIMAL(25,2) Default 0,                      -- الطول
  nWidth     DECIMAL(25,2) Default 0,                      -- العرض
  nHeight    DECIMAL(25,2) Default 0,                      -- الارتفاع
  Barcode    VARCHAR(50),                           -- مسطرة الترميز
  LotSer     VARCHAR(50),                           -- طبخة/مسلسل
  SDate      DATETIME,                                        -- تاريخ بداية
  EDate      DATETIME,                                        -- تاريخ نهاية
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT Pur_TRet_PK       PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- TODO(port): other has no automatic equivalent (source line 189).
-- Original Oracle statement:
--   ----------------------------------------------------------------------------------------------------
