-- Ported from Oracle: db/01-Copy/1401_POR_0810_Dashboard.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
SET SESSION sql_mode = CONCAT(@@sql_mode, ',NO_AUTO_VALUE_ON_ZERO,PIPES_AS_CONCAT');
USE phsoftme_erp_demo;


-- TODO(port): other has no automatic equivalent (source line 1).
-- Original Oracle statement:
--   -- 1402 POR
--   --DELETE FROM Phs_Dash_Blocks WHERE Menu_Id=1402;
--   --Insert into Phs_Dash_Blocks (ORD , Type_Id, Menu_Id, MCOL, SCOL, METHOD, URL                                     , NAME                            , TITLE                                          , OPTIONS                                                                                    )
--   --values                      (1010, 202    , 1402   , 4   , 3   , 'POST', '/UC/Cpy/UsersView/DashQueryPie'        , 'Users By Permission Groups'    , 'Users By Permission Groups'                   , '{"group":["grpName"],"aggregate":[{"userId":"1"}],"printOptions":{"title":""}}'           );
