-- Ported from Oracle: db/01-Copy/1501_SALES_0199_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


Create Table Sal_samMst    -- ترويسة النماذج والهدايا
( Imst_Id     BIGINT,    -- مفتاح رئيسي
  Imst_Year   BIGINT,    -- السنة
  Imst_Typ    SMALLINT Default 0,  -- أصل الوثيقة
  Bran_Id     BIGINT,    -- الفرع
  Imst_Num    BIGINT,    -- رقم الوثيقة
  Imst_Date   DATETIME,      -- التاريخ
  Imst_Doc    MEDIUMINT,    -- نوع المستند
  Imst_Docn   VARCHAR(10),    -- رقم المستند
  Imst_Docd   DATETIME,      -- تاريخ المستند
  Imst_Commit TINYINT Default 1,  -- حالة التثبيت
  Perm_Grp    TINYINT Default 99,  -- مجموعة العمل
  Perm_Lvl    TINYINT Default 9,  -- المستوى
  GACC_ID     BIGINT,               -- الحساب  
  Cost_ID     BIGINT,               -- مركز الكلفة
  Cont_Id     BIGINT NOT NULL,  -- الزبون
  Curn_Id     BIGINT Default 1,  -- العملة
  Curn_Rate   DECIMAL(17,9),    -- سعر الصرف
  Pric_Num    MEDIUMINT Default 1,  -- نوع سعر البيع
  Regn_Id     BIGINT,    -- المنطقة
  Repr_Id     BIGINT,    -- المندوب
  Imst_Cmt    MEDIUMINT Default -1,  -- نوع العمولة
  Imst_Cmv    DECIMAL(17,3),    -- نسبة العمولة
  Imst_Com    DECIMAL(17,3),    -- العمولة
  Imst_CCom   DECIMAL(17,3),    -- العمولة قطع
  Imst_Rem    VARCHAR(100),    -- ملاحظات
  GMst_Id     BIGINT,    -- سند القيد
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  CONSTRAINT  Sal_SamMst_PK      PRIMARY KEY (Imst_Id ),
  CONSTRAINT  Sal_SamMst_UK      Unique      (Bran_Id,Imst_Year,Imst_Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Sal_SamTrn    -- بنود النماذج والهدايا
( Itrn_Id    BIGINT,    -- مفتاح رئيسي
  Imst_Id    BIGINT,    -- مفتاح الأب
  Itrn_Ord   MEDIUMINT,      -- مسلسل
  Stor_Id    BIGINT,      -- المخزن
  Item_Id    BIGINT,    -- المادة
  Itrn_Size  MEDIUMINT Default 0,  -- القياس
  Itrn_Color MEDIUMINT Default 0,  -- اللون
  Itrn_Qnt   DECIMAL(17,3),    -- الكمية
  Itrn_SQnt  DECIMAL(17,3),    -- الكمية بوحدة التخزين
  Itrn_Unt   MEDIUMINT,      -- الوحدة
  Itrn_Perc  DECIMAL(10,5) Default 1,  -- نسبة الوحدة إلى وحدة التخزين
  Itrn_UPric DECIMAL(17,3),    -- سعر الوحدة
  Itrn_Amt   DECIMAL(17,3),    -- المبلغ
  Itrn_CAmt  DECIMAL(17,3),    -- المبلغ قطع
  Itrn_Cst   DECIMAL(17,3),    -- الكلفة
  Itrn_CCst  DECIMAL(17,3),    -- الكلفة قطع
  Itrn_QDis  DECIMAL(17,3),    -- كمية الحسم/الهدية
  Itrn_SQDis DECIMAL(17,3),    -- كمية الحسم/الهدية بوحدة التخزين
  Itrn_CDis  DECIMAL(17,3),    -- كلفة الحسم/الهدايا
  Itrn_CCDis DECIMAL(17,3),    -- كلفة الحسم قطع/ الهدايا
  Itrn_ADis  DECIMAL(17,3),    -- قيمة الحسم
  Itrn_ACDis DECIMAL(17,3),    -- قيمة الحسم قطع
  Itrn_AAdd  DECIMAL(17,3),    -- القيمة المضافة
  Itrn_ACAdd DECIMAL(17,3),    -- القيمة المضافة قطع
  Itrn_Rem   VARCHAR(100),    -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT Sal_SamTrn_PK      PRIMARY KEY (Itrn_Id ),
  CONSTRAINT Sal_SamTrn_UK      Unique      (Imst_Id,Itrn_ord)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Sal_RetSMst  -- ترويسة مردود هدايا وعينات
( Imst_Id     BIGINT,    -- مفتاح رئيسي
  Imst_Num    BIGINT,    -- رقم الوثيقة
  Imst_Year   BIGINT,    -- السنة
  Bran_Id     BIGINT,    -- الفرع
  Imst_Typ    SMALLINT Default 0,  -- أصل الوثيقة
  Imst_Date   DATETIME,      -- التاريخ
  Imst_Doc    MEDIUMINT,    -- نوع المستند
  Imst_Docn   VARCHAR(10),    -- رقم المستند
  Imst_Docd   DATETIME,      -- تاريخ المستند
  Imst_Commit TINYINT Default 1,  -- حالة التثبيت
  Perm_Grp    TINYINT Default 99,  -- مجموعة العمل
  Perm_Lvl    TINYINT Default 9,  -- المستوى
  GACC_ID     BIGINT,               -- الحساب  
  Cost_ID     BIGINT,               -- مركز الكلفة
  Cont_Id     BIGINT NOT NULL,  -- الزبون
  Curn_Id     BIGINT Default 1,  -- عملة الزبون
  Curn_Rate   DECIMAL(17,9),    -- سعر الصرف
  Pric_Type   MEDIUMINT Default 1,  -- نوع سعر البيع
  Imst_Amt    DECIMAL(17,3),    -- القيمة محلية
  Imst_CAmt   DECIMAL(17,3),    -- القيمة عملة
  Regn_Id     BIGINT,    -- المنطقة
  Repr_Id     BIGINT,    -- المندوب
  Imst_Cmt    MEDIUMINT Default -1,  -- نوع العمولة
  Imst_Cmv    DECIMAL(17,3),    -- نسبة العمولة
  Imst_Com    DECIMAL(17,3),    -- العمولة
  Imst_CCom   DECIMAL(17,3),    -- العمولة قطع
  GMst_Id     BIGINT,    -- سند القيد
  Imst_Rem    VARCHAR(100),    -- ملاحظات
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  CONSTRAINT  Sal_RetSMst_PK      PRIMARY KEY (Imst_Id ),
  CONSTRAINT  Sal_RetSMst_UK      Unique      (Bran_Id,Imst_Year,Imst_Num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table Sal_RetSTrn  -- بنود مردود هدايا وعينات
( Itrn_Id     BIGINT,    -- مفتاح رئيسي
  Imst_Id     BIGINT,    -- مفتاح الأب
  Itrn_Ord    MEDIUMINT,    -- مسلسل
  Stor_Id     BIGINT,    -- المخزن
  Item_Id     BIGINT,    -- المادة
  Itrn_Size   MEDIUMINT Default 0,  -- القياس
  Itrn_Color  MEDIUMINT Default 0,  -- اللون
  Itrn_Qnt    DECIMAL(17,3),    -- الكمية
  Itrn_SQnt   DECIMAL(17,3),    -- الكمية بوحدة التخزين
  Itrn_Unt    MEDIUMINT,    -- الوحدة
  Itrn_Perc   DECIMAL(10,5) Default 1,  -- نسبة الوحدة إلى وحدة التخزين
  Itrn_UPric  DECIMAL(17,3),    -- سعر الوحدة
  Itrn_Amt    DECIMAL(17,3),    -- المبلغ
  Itrn_CAmt   DECIMAL(17,3),    -- المبلغ قطع
  Itrn_Cst    DECIMAL(17,3),    -- الكلفة
  Itrn_CCst   DECIMAL(17,3),    -- الكلفة قطع
  Itrn_QDis   DECIMAL(17,3),    -- كمية الحسم/الهدية
  Itrn_SQDis  DECIMAL(17,3),    -- كمية الحسم/الهدية بوحدة التخزين
  Itrn_CDis   DECIMAL(17,3),    -- كلفة الحسم/الهدايا
  Itrn_CCDis  DECIMAL(17,3),    -- كلفة الحسم قطع/ الهدايا
  Itrn_ADis   DECIMAL(17,3),    -- قيمة الحسم
  Itrn_ACDis  DECIMAL(17,3),    -- قيمة الحسم قطع
  Itrn_AAdd   DECIMAL(17,3),    -- القيمة المضافة
  Itrn_ACAdd  DECIMAL(17,3),    -- القيمة المضافة قطع
  Itrn_Rem    VARCHAR(100),    -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    DATETIME,
  Upd_User    BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT  Sal_RetSTrn_PK      PRIMARY KEY (Itrn_Id ),
  CONSTRAINT  Sal_RetSTrn_UK      Unique      (Imst_Id,Itrn_ord)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
