-- Ported from Oracle: db/01-Copy/7001_CRM_0101_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


-- set Pagesize 1000
-- select 'Drop table '   || table_name                          || ';' from user_tables    where table_name    like 'CRM%' ;
-- select 'Drop Synonym ' || Synonym_name                        || ';' from user_Synonyms  where Synonym_name  like 'CRM%' ;
-- select 'Drop Sequence '|| Sequence_name                       || ';' from user_Sequences where Sequence_name like 'CRM%' ;
-- select 'Drop View '    || View_name                           || ';' from user_Views     where View_name     like 'CRM%' ;
-- select 'Drop '         || OBJECT_TYPE   || ' ' || Object_name || ';' from user_Objects   where Object_name   like 'CRM%' ;
-- --------------------------------------------------------------------------------------------------
Create Table CRM_Cod_Status                               -- جدول ترميز حالة التقرير
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT CRM_Cod_Status_PK     PRIMARY KEY (Id  ),
  CONSTRAINT CRM_Cod_Status_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into CRM_Cod_Status (Id,Name) values (0,'-'     );

Insert into CRM_Cod_Status (Id,Name) values (1,'New'   );

Insert into CRM_Cod_Status (Id,Name) values (2,'Follow');

Insert into CRM_Cod_Status (Id,Name) values (3,'Closed');

-- --------------------------------------------------------------------------------------------------
Create Table CRM_Cod_Type                                 -- جدول ترميز نوع التقرير
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT CRM_Cod_Type_PK     PRIMARY KEY (Id  ),
  CONSTRAINT CRM_Cod_Type_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into CRM_Cod_Type (Id,Name) values (0,'-'     );

Insert into CRM_Cod_Type (Id,Name) values (1,'Visit' );

Insert into CRM_Cod_Type (Id,Name) values (2,'Call'  );

Insert into CRM_Cod_Type (Id,Name) values (3,'Email' );

-- --------------------------------------------------------------------------------------------------
Create Table CRM_Cod_Kind                                 -- جدول ترميز طبيعة التقرير
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT CRM_Cod_Kind_PK     PRIMARY KEY (Id  ),
  CONSTRAINT CRM_Cod_Kind_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into CRM_Cod_Kind (Id,Name) values (0,'-'          );

Insert into CRM_Cod_Kind (Id,Name) values (1,'Report'     );

Insert into CRM_Cod_Kind (Id,Name) values (2,'Opportunity');

-- --------------------------------------------------------------------------------------------------
Create Table CRM_Cod_Clearance                            -- جدول ترميز التخليص الجمركي
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT CRM_Cod_Clearance_PK     PRIMARY KEY (Id  ),
  CONSTRAINT CRM_Cod_Clearance_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into CRM_Cod_Clearance (Id,Name) values (0,'-'  );

Insert into CRM_Cod_Clearance (Id,Name) values (1,'Yes');

Insert into CRM_Cod_Clearance (Id,Name) values (2,'No' );

Create Table CRM_Cod_Grp                                -- جدول ترميز فئات التصنيف
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  FColor     VARCHAR(100),                           -- لون النص
  BColor     VARCHAR(100),                           -- لون الخلفية
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT CRM_Cod_Grp_PK        PRIMARY KEY (Id  ),
  CONSTRAINT CRM_Cod_Grp_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into CRM_Cod_Grp (Id,Name) values (0,'-');

Create Table CRM_Cod_Itm                                 -- جدول ترميز بنود التصنيف
( Id         BIGINT NOT NULL AUTO_INCREMENT,                           -- مفتاح رئيسي
  Grp_Id     BIGINT Default 1,                          -- مجموعة الترميز
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    DATETIME,
  Upd_User   BIGINT,  Upd_Date    DATETIME,
  CONSTRAINT CRM_Cod_Itm_PK        PRIMARY KEY (Id  ),
  CONSTRAINT CRM_Cod_Itm_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into CRM_Cod_Itm (Id,Grp_Id,Name) values (0,0,'-');

-- TODO(port): other has no automatic equivalent (source line 127).
-- Original Oracle statement:
--   ----------------------------------------------------------------------------------------------------
