-- Ported from Oracle: db/01-Copy/7035_PED_0100_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;


Create Table PED_Cod_Pregnancy_Type                        -- جدول ترميز طريقة الحمل     
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                   -- الاسم
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_Cod_Pregnancy_Type_PK        PRIMARY KEY (Id  ),
  CONSTRAINT  PED_Cod_Pregnancy_Type_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into PED_Cod_Pregnancy_Type (Id,Name) values (1,'طبيعي');

Insert into PED_Cod_Pregnancy_Type (Id,Name) values (2,'يعد العلاج');

Create Table PED_Cod_Pregnancy_Condition                  -- جدول ترميز طبيعة فترة الحمل
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                   -- الاسم
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_Cod_Pregnancy_Condition_PK        PRIMARY KEY (Id  ),
  CONSTRAINT  PED_Cod_Pregnancy_Condition_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into PED_Cod_Pregnancy_Condition (Id,Name) values (1,'طبيعية');

Insert into PED_Cod_Pregnancy_Condition (Id,Name) values (2,'غير اعتيادية');

Create Table PED_Cod_Birth_Type                            -- جدول ترميز نوع الولادة
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                   -- الاسم
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_Cod_Birth_Type_PK        PRIMARY KEY (Id  ),
  CONSTRAINT  PED_Cod_Birth_Type_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into PED_Cod_Birth_Type (Id,Name) values (1,'طبيعية');

Insert into PED_Cod_Birth_Type (Id,Name) values (2,'قيصرية');

Create Table PED_Cod_Quality_Perf                   -- جدول ترميز الأداء
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                   -- الاسم
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Cod_Quality_Perf_PK        PRIMARY KEY (Id  ),
  CONSTRAINT PED_Cod_Quality_Perf_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into PED_Cod_Quality_Perf (Id,Name) values (1,'ايجابية');

Insert into PED_Cod_Quality_Perf (Id,Name) values (2,'سلبية');

Insert into PED_Cod_Quality_Perf (Id,Name) values (3,'سلبية متغيرة');

Create Table PED_Cats                                 -- جدول الفئات
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- الحالة
  Name       VARCHAR(100) NOT NULL,                   -- الاسم
  Symbol     VARCHAR(10),                             -- الرمز
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Cats_PK        PRIMARY KEY (Id  ),
  CONSTRAINT PED_Cats_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (1 , 'A', 'معارضة (عند)', 'مشكلة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (2 , 'B', 'مشاكل معرفية', 'مشكلة متوسطة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (3 , 'C', 'حركة زائدة', 'مشكلة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (4 , 'D', 'خجل وقلق', 'درجة عادية');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (5 , 'E', 'الكماليات', 'درجة عادية');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (6 , 'F', 'مهارات اجتماعية', 'مشكلة متوسطة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (7 , 'G', 'أمراض نفس جسمية', 'درجة عادية');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (8 , 'H', 'أعراض الإصابة بـ ADHD', 'مشكلة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (9 , 'I', 'اندفاعية وعدم تركيز', 'مشكلة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (10, 'J', 'مشكلات انفعالية', 'مشكلة متوسطة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (11, 'K', 'مشكلة في التركيز', 'مشكلة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (12, 'L', 'مشكلة في الانتباه', 'مشكلة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (13, 'M', 'مشاكل حركة زائدة', 'مشكلة');

INSERT INTO PED_Cats (Id, Symbol, Name, Rem) VALUES (14, 'N', 'حركة زائدة ونقص تركيز واندفاع', 'مشكلة');

Create Table PED_Test                                      -- جدول الاختبارات
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- الحالة
  Name       VARCHAR(200) NOT NULL,                   -- الاسم
  Version    VARCHAR(50),                             -- الإصدار
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Test_PK        PRIMARY KEY (Id),
  CONSTRAINT PED_Test_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO PED_Test (Id, Status_Id, Name, Version, Rem) VALUES (0,1,'corner','0.0.1','');

Create Table PED_Test_Cats                        -- جدول فئات اختبار
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- الحالة
  Test_Id    BIGINT NOT NULL,                            -- الاختبار
  Cat_Id     BIGINT NOT NULL,                            -- الفئة
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Test_Cats_PK        PRIMARY KEY (Id),
  CONSTRAINT PED_Test_Cats_UK        UNIQUE      (Test_Id, Cat_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Test_Cats_Trn                        -- جدول فئات اختبار
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,                            -- الحالة
  Cat_From   MEDIUMINT NOT NULL,                            -- الاختبار
  Cat_To     MEDIUMINT NOT NULL,                            -- الفئة
  LONGTEXT       VARCHAR(100),                            -- النص
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Test_Cats_Trn_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Test_Question                             -- أسئلة اختبار
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- الحالة
  Test_Id    BIGINT NOT NULL,                            -- الاختبار
  Ord        SMALLINT NOT NULL,                            -- الترتيب
  QText      VARCHAR(256) NOT NULL,                        -- نص السؤال
  IsCatA     TINYINT Default 0 CHECK (IsCatA IN (0,1)),   -- هل يؤثر على الفئة A
  IsCatB     TINYINT Default 0 CHECK (IsCatB IN (0,1)),   -- هل يؤثر على الفئة B
  IsCatC     TINYINT Default 0 CHECK (IsCatC IN (0,1)),   -- هل يؤثر على الفئة C
  IsCatD     TINYINT Default 0 CHECK (IsCatD IN (0,1)),   -- هل يؤثر على الفئة D
  IsCatE     TINYINT Default 0 CHECK (IsCatE IN (0,1)),   -- هل يؤثر على الفئة E
  IsCatF     TINYINT Default 0 CHECK (IsCatF IN (0,1)),   -- هل يؤثر على الفئة F
  IsCatG     TINYINT Default 0 CHECK (IsCatG IN (0,1)),   -- هل يؤثر على الفئة G
  IsCatH     TINYINT Default 0 CHECK (IsCatH IN (0,1)),   -- هل يؤثر على الفئة H
  IsCatI     TINYINT Default 0 CHECK (IsCatI IN (0,1)),   -- هل يؤثر على الفئة I
  IsCatJ     TINYINT Default 0 CHECK (IsCatJ IN (0,1)),   -- هل يؤثر على الفئة J
  IsCatK     TINYINT Default 0 CHECK (IsCatK IN (0,1)),   -- هل يؤثر على الفئة K
  IsCatL     TINYINT Default 0 CHECK (IsCatL IN (0,1)),   -- هل يؤثر على الفئة L
  IsCatM     TINYINT Default 0 CHECK (IsCatM IN (0,1)),   -- هل يؤثر على الفئة M
  IsCatN     TINYINT Default 0 CHECK (IsCatN IN (0,1)),   -- هل يؤثر على الفئة N
  Rem        VARCHAR(100),
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Test_Question_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Ques_Ans                          -- جدول أجوبة الأسئلة
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Test_Id    BIGINT NOT NULL,                            -- الاختبار
  Answer     VARCHAR(50),                                  -- الاجابة
  Mark       TINYINT,                                     -- العلامة
  Rem        VARCHAR(100),
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Ques_Ans_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Test_Key                                  -- جدول مفاتيح اختبار
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Test_Id    BIGINT NOT NULL,                            -- الاختبار
  Gender_Id  BIGINT Default 1 NOT NULL,                  -- الجنس
  Age_From   SMALLINT Default 0 NOT NULL,                  -- العمر من
  Age_To     SMALLINT Default 0 NOT NULL,                  -- العمر إلى
  Degree     SMALLINT Default 0 NOT NULL,                  -- الدرجة
  ACat_From  TINYINT Default -1,                          -- الفئة A من
  ACat_To    TINYINT Default -1,                          -- الفئة A إلى
  BCat_From  TINYINT Default -1,                          -- الفئة B من
  BCat_To    TINYINT Default -1,                          -- الفئة B إلى
  CCat_From  TINYINT Default -1,                          -- الفئة C من
  CCat_To    TINYINT Default -1,                          -- الفئة C إلى
  DCat_From  TINYINT Default -1,                          -- الفئة D من
  DCat_To    TINYINT Default -1,                          -- الفئة D إلى
  ECat_From  TINYINT Default -1,                          -- الفئة E من
  ECat_To    TINYINT Default -1,                          -- الفئة E إلى
  FCat_From  TINYINT Default -1,                          -- الفئة F من
  FCat_To    TINYINT Default -1,                          -- الفئة F إلى
  GCat_From  TINYINT Default -1,                          -- الفئة G من
  GCat_To    TINYINT Default -1,                          -- الفئة G إلى
  HCat_From  TINYINT Default -1,                          -- الفئة H من
  HCat_To    TINYINT Default -1,                          -- الفئة H إلى
  ICat_From  TINYINT Default -1,                          -- الفئة I من
  ICat_To    TINYINT Default -1,                          -- الفئة I إلى
  JCat_From  TINYINT Default -1,                          -- الفئة J من
  JCat_To    TINYINT Default -1,                          -- الفئة J إلى
  KCat_From  TINYINT Default -1,                          -- الفئة K من
  KCat_To    TINYINT Default -1,                          -- الفئة K إلى
  LCat_From  TINYINT Default -1,                          -- الفئة L من
  LCat_To    TINYINT Default -1,                          -- الفئة L إلى
  MCat_From  TINYINT Default -1,                          -- الفئة M من
  MCat_To    TINYINT Default -1,                          -- الفئة M إلى
  NCat_From  TINYINT Default -1,                          -- الفئة N من
  NCat_To    TINYINT Default -1,                          -- الفئة N إلى
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Test_Key_PK        PRIMARY KEY (Id),
  CONSTRAINT PED_Test_Key_Age_Chk   CHECK       (Age_From <= Age_To),
  CONSTRAINT PED_Test_Key_UK        UNIQUE      (Gender_Id, Age_From, Age_To, Degree)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Prog                                   -- البرامج
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- الحالة
  Name       VARCHAR(100) NOT NULL,                   -- الاسم
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Prog_PK        PRIMARY KEY (Id  ),
  CONSTRAINT PED_Prog_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_App                                                                    -- جدول المواعيد
( Id                                                           BIGINT NOT NULL AUTO_INCREMENT,               -- مفتاح رئيسي
  Info_Source                                                  VARCHAR(100),               -- مصدر المعلومات 
  ComingFrom                                                   VARCHAR(100),               -- جهة التحويل   
  Appointment_Date                                             DATETIME,                             -- تاريخ المقابلة  
  Name                                                         VARCHAR(100) NOT NULL,      -- الاسم 
  Gender_Id                                                    BIGINT Default 1 NOT NULL,     -- الجنس
  Date_Of_Birth                                                DATETIME,                             -- تاريخ الميلاد 
  Current_Class                                                VARCHAR(100),               -- الصف الحالي
  Assumed_Class                                                VARCHAR(100),               -- الصف المفترض
  Current_School                                               VARCHAR(100),               -- المدرسة الحالية
  Address                                                      VARCHAR(200),               -- العنوان
  Phone_1                                                      VARCHAR(20),               -- 1 رقم الهاتف 
  Phone_2                                                      VARCHAR(20),               -- 2 رقم الهاتف 
  Father_Name                                                  VARCHAR(100),               -- اسم الأب
  Father_Edu_Qualification                                     VARCHAR(100),               -- المؤهل العلمي للأب
  Father_Jop                                                   VARCHAR(100),               -- وظيفة الأب
  Mother_Name                                                  VARCHAR(100),               -- اسم الأم
  Mother_Edu_Qualification                                     VARCHAR(100),               -- المؤهل العلمي للأم
  Mother_Jop                                                   VARCHAR(100),               -- وظيفة الأم
  Brothers_Number                                              TINYINT,                      -- عدد الإخوة 
  Child_Order                                                  TINYINT,                      -- ترتيب الطفل
  Pathological_Allergies_Id                                    BIGINT Default 2,            -- الحساسية المرضية
  General_Medical_Weakness_Id                                  BIGINT Default 2,            -- الضعف الطبي العام
  Academic_Performance_Weakness_Id                             BIGINT Default 2,            -- ضعف في التحصيل العلمي
  Speech_Problems_Id                                           BIGINT Default 2,            -- مشاكل في النطق
  Wear_Glasses_Id                                              BIGINT Default 2,            -- يرتدي نظارات
  Wear_Hearing_Aid_Id                                          BIGINT Default 2,            -- يرتدي سماعة طبية
  Use_Crutch_Id                                                BIGINT Default 2,            -- يستخدم عكاز   
  Use_Wheelchair_Id                                            BIGINT Default 2,            -- يستخدم كرسي متحرك
  Other_Aids                                                   VARCHAR(200),               -- وسائل مساعدة أخرى
  Problem_Parents_Point_View                                   VARCHAR(200),               -- المشكلة من وجهة نظر الأبوين
  Is_Mother_Smoke_Before_Pregnancy_Id                          BIGINT Default 2,            -- هل كانت الأم تدخن قبل الحمل
  Is_Mother_Smoke_During_Pregnancy_Id                          BIGINT Default 2,            -- هل كانت الأم تدخن أثناء الحمل
  Is_Mother_Smoke_After_Pregnancy_Id                           BIGINT Default 2,            -- هل كانت الأم تدخن بعد الحمل 
  Is_Mother_Non_Smoker_Id                                      BIGINT Default 2,            -- هل كانت الأم غير مدخنة
  Pregnancy_Type_Id                                            BIGINT Default 1,            -- نوع الحمل
  Pregnancy_Duration                                           TINYINT,                      -- مدة الحمل
  Mother_Receive_Radiation_Therapy_During_Pregnancy_Id         BIGINT Default 2,            -- هل تلقت الأم علاجاً إشعاعياً أثناء الحمل
  Mother_Receive_Chemotherapy_During_Pregnancy_Id              BIGINT Default 2,            -- هل تلقت الأم علاجاً كيميائياً أثناء الحمل
  Mother_Use_Hair_Dye_During_Pregnancy_Id                      BIGINT Default 2,            -- هل استخدمت الأم صبغة شعر أثناء الحمل
  Mother_Use_LightFillings_During_Pregnancy_Id                 BIGINT Default 2,            -- حشوات ضوئية
  Mother_Experience_Psychological_Problems_During_Pregnancy_Id BIGINT Default 2,            -- هل عانت الأم من مشاكل نفسية أثناء الحمل
  Pregnancy_Condition_Id                                       BIGINT Default 1,            -- ظروف الحمل
  Pregnancy_Conditions_Notes                                   VARCHAR(200),               -- ملاحظات ظروف الحمل
  Birth_Type_Id                                                BIGINT Default 1,            -- نوع الولادة
  Labor_Period                                                 VARCHAR(50),                -- فترة المخاض
  Enter_Incubator_Id                                           BIGINT Default 2,            -- دخول الحاضنة
  Child_Weight_At_Birth                                        SMALLINT,                        -- وزن الطفل عند الولادة 
  Problems_During_Child_Birth                                  VARCHAR(200),               -- مشاكل أثناء ولادة الطفل
  Breast_Feeding_Id                                            BIGINT Default 1,            -- الرضاعة الطبيعية
  Breast_Feeding_Duration                                      TINYINT,                      -- مدة الرضاعة الطبيعية
  Artificial_Feeding_Id                                        BIGINT Default 2,            -- الرضاعة الصناعية
  Artificial_Feeding_Duration                                  TINYINT,                      -- مدة الرضاعة الصناعية
  Weaning_Conditions                                           VARCHAR(200),               -- ظروف الفطام
  Stool_During_Breast_Feeding                                  VARCHAR(200),               -- براز الطفل أثناء الرضاعة الطبيعية
  Child_Condition_In_First_Three_Months                        VARCHAR(200),               -- حالة الطفل في الأشهر الثلاثة الأولى
  Nerve_Reflexes                                               VARCHAR(200),               -- المنعكسات العصبية
  Medical_Diagnosis                                            VARCHAR(200),               -- التشخيص الطبي
  Medical_Resonant_Image_Id                                    BIGINT Default 2,            -- صورة طبية رنين 
  Medical_Brain_Mapping_Image_Id                               BIGINT Default 2,            -- صورة تخطيط دماغ طبي
  Medical_Blood_Test_Id                                        BIGINT Default 2,            -- تحاليل دم طبية          
  Medical_Food_Allergy_Test_Id                                 BIGINT Default 2,            -- اختبار الحساسية الغذائية
  Medical_Previous_Report_Id                                   BIGINT Default 2,            -- تقارير سابقة طبية
  Medical_Other                                                VARCHAR(200),               -- اختبارات طبية أخرى
  Child_Age_Sitting_Walking_Crawling                           TINYINT,                        -- عمر الطفل في الجلوس والمشي والزحف
  Child_Age_When_Spoke_First_Word                              TINYINT,                        -- عمر الطفل عند نطقه أول كلمة وأول جملة
  Movement_Problems                                            VARCHAR(200),               -- مشاكل في الحركة
  Congenital_Malformations                                     VARCHAR(200),               -- تشوهات خلقية
  Child_Involved_Accidents_Id                                  BIGINT Default 2,            -- تعرض الطفل لحوادث
  Child_Involved_Experience_Fever_Id                           BIGINT Default 2,            -- تعرض الطفل لنوبات حمى 
  Child_Involved_Seizures_Id                                   BIGINT Default 2,            -- تعرض الطفل لنوبات صرع
  Child_Involved_Other                                         VARCHAR(200),               -- تعرض الطفل لأمور أخرى
  Other_Signs_Mention                                          VARCHAR(200),               -- علامات أخرى يذكرها الأبوين
  Personal_Social_Factor_Shyness_Id                            BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - الخجل
  Personal_Social_Factor_Introversion_Id                       BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - الانطواء
  Personal_Social_Factor_Withdrawal_Id                         BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - الانسحاب
  Personal_Social_Factor_Depression_Id                         BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - الاكتئاب
  Personal_Social_Factor_Anxiety_Id                            BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - القلق
  Personal_Social_Factor_Absentmindedness_Id                   BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - شرود الذهن
  Personal_Social_Factor_Hyperactivity_Id                      BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - فرط النشاط
  Personal_Social_Factor_Excessive_Inactivity_Id               BIGINT Default 2,            -- العوامل الشخصية والاجتماعية -الخمول المفرط
  Personal_Social_Factor_Achievement_Motivation_Id             BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - دافع الإنجاز
  Personal_Social_Factor_Impulsiveness_Id                      BIGINT Default 2,            -- العوامل الشخصية والاجتماعية - الاندفاعية
  Brother_Sister_Relationship                                  VARCHAR(200),               -- علاقة الأخوة والأخوات
  Friends_Relationship                                         VARCHAR(200),               -- علاقة الأصدقاء
  Hobbies_Interests                                            VARCHAR(200),               -- الهوايات والاهتمامات
  Acceptance_Taking_Responsibility                             VARCHAR(200),               -- القبول وتحمل المسؤولية
  Child_Entered_Kindergarten_Id                                BIGINT Default 2,            -- دخول الطفل الروضة
  Child_Entered_Kindergarten_Age                               TINYINT,                        -- عمر دخول الطفل الروضة
  Received_Special_Assistance_In_Past_Id                       BIGINT Default 2,            -- تلقي مساعدة خاصة في الماضي
  Bring_Back_Classes_Id                                        BIGINT Default 2,            -- هل أعيد له الصفوف
  Drop_Out_School_Id                                           BIGINT Default 2,            -- هل انقطع عن المدرسة
  School_Teacher_Changed_Id                                    BIGINT Default 2,            -- هل تم تغيير المدرسة والمعلمين
  Quality_Teacher_Report_Perf_Id                               BIGINT Default 1,            -- تقارير المعلمين عن الأداء الدراسي 
  Child_Attitudes_Towards_School                               VARCHAR(200),               -- مواقف الطفل تجاه المدرسة
  Psychological_Counseling                                     VARCHAR(200),               -- استشارات نفسية
  Other_Medical_Consultations                                  VARCHAR(200),               -- استشارات طبية أخرى
  Service_Requested                                            VARCHAR(200),               -- الخدمة المطلوبة من المركز حسب طلب الاهل 
  Recommendations                                              VARCHAR(200),               -- التوصيات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_App_PK                                           PRIMARY KEY (Id),
  CONSTRAINT PED_App_UK                                           UNIQUE      (Name, Appointment_Date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_App_Test                           -- جدول اختبارات مقابلة
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  App_Id     BIGINT  NOT NULL ,                           -- مفتاح الأب  
  Test_Id    BIGINT  NOT NULL,                            -- الاختبار  
  Rem        VARCHAR(100),                             -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_App_Test_PK        PRIMARY KEY (Id  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Cod_Grp                                 -- جدول ترميز المجموعات
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                   -- الاسم
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_Cod_Grp_Type_PK        PRIMARY KEY (Id  ),
  CONSTRAINT  PED_Cod_Grp_Type_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Prog_Itm                               -- جدول بنود البرامج
( Id         BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  Prog_Id    BIGINT NOT NULL,                            -- مفتاح الأب              
  Grp_Id     BIGINT NOT NULL,                            -- المجموعة
  Name       VARCHAR(100),                            -- الاسم
  Ord        TINYINT,                                     -- الترتيب
  Rem        VARCHAR(100),                            -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_Prog_Itm_PK        PRIMARY KEY (Id  ),
  CONSTRAINT  PED_Prog_Itm_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_APP_Quest                  -- جدول تسجيل بنود اختبار مقابلة      
( Id          BIGINT NOT NULL  AUTO_INCREMENT,                            -- مفتاح رئيسي
  App_Test_Id BIGINT NOT NULL ,                            -- مفتاح الأب              
  Quest_Id    BIGINT NOT NULL ,                            -- مفتاح الأب
  Degree      TINYINT DEFAULT 0,                            -- الدرجة
  Answer_Id   BIGINT DEFAULT 0,                            -- الدرجة
  Rem         VARCHAR(100) ,                            -- ملاحظات
  Ins_User    BIGINT, Ins_Date     DATETIME,
  Upd_User    BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_APP_Quest_PK       PRIMARY KEY (Id  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_App_Res                            -- جدول تقييم اختبار
( Id            BIGINT NOT NULL AUTO_INCREMENT,                            -- مفتاح رئيسي
  App_Test_Id   BIGINT NOT NULL,                           -- مفتاح الأب              
  Cat_Id        BIGINT NOT NULL,                            -- المجموعة
  Total_Degree  SMALLINT NOT NULL,                            -- مجموع الدرجات
  Degree        SMALLINT NOT NULL,                            -- الدرجة
  DESCRIPTION   VARCHAR(100),                            -- النص
  Rem           VARCHAR(100),                            -- ملاحظات
  Ins_User      BIGINT, Ins_Date     DATETIME,
  Upd_User      BIGINT, Upd_Date     DATETIME,
  CONSTRAINT  PED_App_Res_PK       PRIMARY KEY (Id  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Lect (
  Id           BIGINT NOT NULL AUTO_INCREMENT,
  Status_Id    BIGINT Default 1,
  Name         VARCHAR(100) NOT NULL,
  Mobile       VARCHAR(20),
  Gender_Id    BIGINT Default 1 NOT NULL,
  Age          SMALLINT Default 0 NOT NULL,
  StudyFld     VARCHAR(100) NOT NULL,
  Rem          VARCHAR(100),
  Ins_User     BIGINT, Ins_Date     DATETIME,
  Upd_User     BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Lect_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Lect_Prog (
  Id           BIGINT NOT NULL AUTO_INCREMENT,
  Lect_Id      BIGINT NOT NULL,
  Prog_Id      BIGINT NOT NULL,
  Status_Id    BIGINT Default 1,
  Rem          VARCHAR(100),
  Ins_User     BIGINT, Ins_Date     DATETIME,
  Upd_User     BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Lect_Prog_PK         PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Std_Lect (
  Id         BIGINT NOT NULL AUTO_INCREMENT,
  App_Id     BIGINT NOT NULL,   
  Prog_Id    BIGINT NOT NULL,
  Lect_Id    BIGINT NOT NULL, 
  Sdate      DATETIME,
  Edate      DATETIME,
  Rem        VARCHAR(100),
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_PED_Std_Lect_PK          PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Std_Sched (
  Id             BIGINT NOT NULL AUTO_INCREMENT,   
  Mst_Id         BIGINT NOT NULL,
  Day_Code       VARCHAR(3),
  Shour          TINYINT,
  Ehour          TINYINT,  
  Sminute        TINYINT,
  Eminute        TINYINT,
  Activity_Desc  VARCHAR(200),
  Rem            VARCHAR(100),
  Ins_User       BIGINT, Ins_Date   DATETIME,
  Upd_User       BIGINT, Upd_Date   DATETIME,
  CONSTRAINT PED_Std_Sched_PK      PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Sched (
  Id             BIGINT NOT NULL AUTO_INCREMENT,
  App_Id         BIGINT NOT NULL,
  Lect_Id        BIGINT NOT NULL,
  dDate          DATETIME,
  Day_Code       VARCHAR(3),
  Shour          TINYINT,
  Ehour          TINYINT,
  Activity_Desc  VARCHAR(200),
  Rem            VARCHAR(100),
  Ins_User       BIGINT, Ins_Date   DATETIME,
  Upd_User       BIGINT, Upd_Date   DATETIME,
  CONSTRAINT PED_Sched_PK      PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table PED_Special                                                                         -- جدول الاختصاصات
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                                                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				                                                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT PED_Special_PK        PRIMARY KEY (Id  ),
  CONSTRAINT PED_Special_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into PED_Special (Id,Name) values (0,'ALL');

CREATE TABLE PED_Doct                                                                          -- جدول الأطباء
( Id          BIGINT NOT NULL AUTO_INCREMENT,                                                                  -- PK
  Name        VARCHAR(100) NOT NULL,                                                         -- Name
  DoB         DATETIME NOT NULL,                                                                       -- Birthdate
  Status_id   BIGINT DEFAULT 1 NOT NULL,                                                         -- Status
  Gender_Id   BIGINT DEFAULT 1 NOT NULL,                                                        -- Gender
  Special_Id  BIGINT DEFAULT 0 NOT NULL,                                                        -- Speciality
  NatNum      VARCHAR(25),                                                                   -- National Id
  Mobile      VARCHAR(100) NOT NULL,                                                         -- Mobile
  Phone1      VARCHAR(25),                                                                   -- Phone 1
  Phone2      VARCHAR(25),                                                                   -- Phone 2
  Email       VARCHAR(75),                                                                   -- Email
  Langs       VARCHAR(100),                                                                  -- Languages Known
  Descr       VARCHAR(100),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   DATETIME,
  Upd_User    BIGINT, Upd_Date   DATETIME,
  CONSTRAINT PED_Doctor_PK         PRIMARY KEY (Id    ),
  CONSTRAINT PED_Doctor_Mobile_UK  UNIQUE      (Mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------------------------------
CREATE TABLE PED_App_Status                                                               -- جدول حالات المواعيد
( Id         BIGINT NOT NULL AUTO_INCREMENT,                                                                   -- PK
  Name       VARCHAR(100) NOT NULL,                                                          -- Name
  BG         VARCHAR(10) DEFAULT '#CCC' NOT NULL,                                            -- Title Background Color
  FG         VARCHAR(10) DEFAULT '#000' NOT NULL,                                            -- Title Text Color
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT PED_App_Status_PK     PRIMARY KEY (Id  ),
  CONSTRAINT PED_App_Status_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into PED_App_Status (Id,Name,BG,FG) values (0,'New','#CCC','#000');

Insert into PED_App_Status (Id,Name,BG,FG) values (1,'Waiting','#CCC','#000');

Insert into PED_App_Status (Id,Name,BG,FG) values (2,'Progress','#CCC','#000');

Insert into PED_App_Status (Id,Name,BG,FG) values (3,'Done','#CCC','#000');

Insert into PED_App_Status (Id,Name,BG,FG) values (4,'Late','#CCC','#000');

Insert into PED_App_Status (Id,Name,BG,FG) values (5,'No Show','#CCC','#000');

CREATE TABLE PED_App_Type                                                                 -- جدول أنواع المواعيد
( Id         BIGINT NOT NULL AUTO_INCREMENT,                                                                   -- PK
  Capacity   SMALLINT DEFAULT 0 NOT NULL,                                                         -- Capacity
  Minutes    SMALLINT DEFAULT 15 NOT NULL,                                                        -- Appointment Minutes
  Name       VARCHAR(100) NOT NULL,                                                          -- Name
  Title_BG   VARCHAR(10) DEFAULT '#CCC' NOT NULL,                                            -- Title Background Color
  Title_FG   VARCHAR(10) DEFAULT '#000' NOT NULL,                                            -- Title Text Color
  Patient_FG VARCHAR(10) DEFAULT '#777' NOT NULL,                                            -- Patient Name Text Color
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME,
  CONSTRAINT PED_App_Type_PK     PRIMARY KEY (Id  ),
  CONSTRAINT PED_App_Type_UK     UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Insert into PED_App_Type (Id,Name) values (0,'-');

CREATE TABLE PED_App_Sched                                                                 -- جدول المواعيد
( Id            BIGINT NOT NULL AUTO_INCREMENT,                                                                  -- PK
  Special_Id    BIGINT DEFAULT 0 NOT NULL,                                                        -- Speciality
  Status_Id     BIGINT DEFAULT 10 NOT NULL,                                                       -- Status
  Type_Id       BIGINT NOT NULL,                                                                  -- Type
  Doctor_Id     BIGINT NOT NULL,                                                                  -- Doctor
  Patient_Name  VARCHAR(256) NOT NULL,                                                         -- Patient
  dDate         DATETIME NOT NULL,                                                                       -- Date
  nHour         SMALLINT DEFAULT 0 NOT NULL,                                                        -- Appointment Hour
  nMinute       SMALLINT DEFAULT 0 NOT NULL,                                                        -- Appointment Minute
  Minutes       INT DEFAULT 15 NOT NULL,                                                       -- Appointment Minutes
  Amt           DECIMAL(25,3) DEFAULT 0 NOT NULL,                                                     -- Payment Amount
  Descr         VARCHAR(512),                                                                  -- Description
  Ins_User      BIGINT, Ins_Date   DATETIME,
  Upd_User      BIGINT, Upd_Date   DATETIME,
  CONSTRAINT  PED_App_Sched_PK         PRIMARY KEY (Id),
  CONSTRAINT  PED_App_Sched_UK         UNIQUE      (Doctor_Id, dDate, nHour, nMinute)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PED_App_Change                                                               -- جدول تبدل حالات موعد
( Id         BIGINT NOT NULL AUTO_INCREMENT,                                                                   -- PK
  App_Id     BIGINT NOT NULL,                                                                   -- Appointment
  Status_Id  BIGINT NOT NULL,                                                                   -- Status
  dDate      DATETIME DEFAULT (NOW()) NOT NULL,                                                        -- Date
  Reason     VARCHAR(256),                                                                   -- Reason
  Ins_User   BIGINT, Ins_Date   DATETIME,
  Upd_User   BIGINT, Upd_Date   DATETIME, 
  CONSTRAINT  PED_App_Change_PK        PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
