-- Ported from Oracle: db/01-Copy/8101_AMS_0102_TBLS.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

SET FOREIGN_KEY_CHECKS = 0;
SET SESSION sql_mode = CONCAT(@@sql_mode, ',NO_AUTO_VALUE_ON_ZERO,PIPES_AS_CONCAT');
USE phsoftme_erp_demo;


Create Table Ams_Bran                           -- جدول ترميز
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- الحالة
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Bran_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Bran_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_Bran (Id, Name) VALUES (0, '-');

Create Table Ams_Colge                                    -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- الحالة
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Name_en    VARCHAR(100),        				           -- الاسم
  Study_Year TINYINT Default 1,                          -- Study Years
  Ext_Year   TINYINT Default 1,                          -- Extension Years
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Coleg_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Coleg_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_Coleg (Id, Name) VALUES (0, '-');

Create Table Ams_Sec                                   -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Coleg_Id   BIGINT Default 0,                          -- الحالة
  Status_Id  BIGINT Default 1,                          -- الحالة
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Name_en    VARCHAR(100),        				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Sec_PK        PRIMARY KEY (Id),
  CONSTRAINT AMS_Sec_UK        UNIQUE      (Coleg_Id, Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_Sec (Id, Coleg_Id, Name) VALUES (0, 0, '-');

Create Table Ams_Spec                                -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Sec_Id     BIGINT Default 0,                          -- الحالة
  Status_Id  BIGINT Default 1,                          -- الحالة
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Name_en    VARCHAR(100),        				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Spec_PK        PRIMARY KEY (Id),
  CONSTRAINT AMS_Spec_UK        UNIQUE      (Sec_Id, Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_Spec (Id, Sec_Id, Name) VALUES (0, 0, '-');

Create Table Ams_AYear                                -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- الحالة
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_AcYear_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_AcYear_UK        UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_AcYear (Id, Sec_Id, Name) VALUES (0, 0, '-');

Create Table Ams_ATerm                             -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  AcYear_Id  BIGINT Default 0,                          -- الحالة
  Term_Id    BIGINT Default 0,                          -- Term/الفصل
  Status_Id  BIGINT Default 1,                          -- الحالة
  SDate      DATETIME NOT NULL,                                -- Start Date
  EDate      DATETIME NOT NULL,                                -- End Date
  RDate      DATETIME,                                         -- Register Date
  DDate      DATETIME,                                         -- Drop Date
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_AcTerm_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_AcTerm_UK        UNIQUE      (AcYear_Id, Term_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_AcTerm (Id, AcYear_Id, SDate, EDate) VALUES (0, 0, STR_TO_DATE('01-01-2000','%d-%m-%Y'), STR_TO_DATE('31-12-2999','%d-%m-%Y'));

Create Table AMS_Item                             -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- الحالة
  Code       VARCHAR(25) NOT NULL,				           -- الرمز
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Name_en    VARCHAR(100),        				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Item_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Item_Code_UK   UNIQUE      (Code),
  CONSTRAINT AMS_Item_NAme_UK   UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_Item (Id, Code, Name) VALUES (0, '0', '-');

Create Table Ams_Price                                    -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- الحالة
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Price_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Price_Name_UK   UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_Price (Id, Name) VALUES (0, '-');

Create Table AMS_Price_Fee                                -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Mst_Id     BIGINT Default 1,                          -- الأب
  Status_Id  BIGINT Default 1,                          -- الحالة
  Bran_Id    BIGINT Default 0,                          -- Branch
  Coleg_Id   BIGINT Default 0,                          -- College
  Sec_Id     BIGINT Default 0,                          -- Section
  Spec_Id    BIGINT Default 0,                          -- Speciality
  Type_Id    BIGINT Default 0,                          -- Type 1 one Time, 2 Per Term, 3 Per Item
  Fee_Id     BIGINT Default 0,                          -- Fee
  Curn1_Id   BIGINT Default 1,                          -- Syrian Currency
  Curn2_Id   BIGINT Default 1,                          -- Syrian Out Currency
  Curn3_Id   BIGINT Default 1,                          -- Others Currency
  Value1     DECIMAL(17,3) Default 0,                       -- Syrian Value
  Value2     DECIMAL(17,3) Default 0,                       -- Syrian Out Value
  Value3     DECIMAL(17,3) Default 0,                       -- Others Value
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Price_Fee_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Price_Fee_UK        UNIQUE      (Mst_Id, Bran_Id, Coleg_Id, Sec_Id, Spec_Id, Type_Id, Fee_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

Create Table AMS_Disc                                 -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- الحالة
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Disc_PK        PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Disc_Name_UK   UNIQUE      (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO AMS_Disc (Id, Name) VALUES (0, '-');

Create Table AMS_Discount_Details                          -- جدول 
( Id         BIGINT NOT NULL AUTO_INCREMENT,				                   -- مفتاح رئيسي
  Mst_Id     BIGINT Default 1,                          -- الأب
  Status_Id  BIGINT Default 1,                          -- الحالة
  Type_Id    BIGINT Default 0,                          -- Type 1 one Time, 2 Per Term, 3 Per Item
  Disc_Id    BIGINT Default 0,                          -- Fee
  AmtType_Id BIGINT Default 1,                          -- Amount Type
  Curn1_Id   BIGINT Default 1,                          -- Syrian Currency
  Curn2_Id   BIGINT Default 1,                          -- Syrian Out Currency
  Curn3_Id   BIGINT Default 1,                          -- Others Currency
  Value1     DECIMAL(17,3) Default 0,                       -- Syrian Value
  Value2     DECIMAL(17,3) Default 0,                       -- Syrian Out Value
  Value3     DECIMAL(17,3) Default 0,                       -- Others Value
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     DATETIME,
  Upd_User   BIGINT, Upd_Date     DATETIME,
  CONSTRAINT AMS_Disc_Detail_PK         PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Disc_Detail_UK         UNIQUE      (Mst_Id, Type_Id, Disc_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- TODO(port): other has no automatic equivalent (source line 270).
-- Original Oracle statement:
--   ----------------------------------------------------------------------------------------------------
