-- Additional Oracle synonyms over an already-renamed table in phsoftme_erp_demo.
-- Emitted as views: nothing foreign-keys them, so a view is safe.

SET FOREIGN_KEY_CHECKS = 0;
USE phsoftme_erp_demo;

CREATE OR REPLACE VIEW Emp_VOTime AS SELECT * FROM Emp_VOtime;
CREATE OR REPLACE VIEW Emp_VAdmCon AS SELECT * FROM Emp_VAdmCons;
CREATE OR REPLACE VIEW Emp_VGradeTemp AS SELECT * FROM Emp_VGradTmplt;
CREATE OR REPLACE VIEW Emp_VGradChange AS SELECT * FROM Emp_VChGrade;
CREATE OR REPLACE VIEW Emp_VEmpDed AS SELECT * FROM Emp_VEDed;
CREATE OR REPLACE VIEW Emp_VEmpCom AS SELECT * FROM Emp_VECom;
CREATE OR REPLACE VIEW Emp_VAddOnSalary AS SELECT * FROM Emp_VAosal;
CREATE OR REPLACE VIEW Emp_VChngeSal AS SELECT * FROM Emp_VCSal;
CREATE OR REPLACE VIEW Emp_VSubFromSalary AS SELECT * FROM Emp_VSfsal;
CREATE OR REPLACE VIEW AMS_Bran AS SELECT * FROM Ams_Bran;
CREATE OR REPLACE VIEW AMS_Coleg AS SELECT * FROM Ams_Colge;
CREATE OR REPLACE VIEW AMS_Sec AS SELECT * FROM Ams_Sec;
CREATE OR REPLACE VIEW AMS_Spec AS SELECT * FROM Ams_Spec;
CREATE OR REPLACE VIEW AMS_AcYear AS SELECT * FROM Ams_AYear;
CREATE OR REPLACE VIEW AMS_AcTerm AS SELECT * FROM Ams_ATerm;
CREATE OR REPLACE VIEW AMS_Price AS SELECT * FROM Ams_Price;
CREATE OR REPLACE VIEW AMS_Disc_Detail AS SELECT * FROM AMS_Price_Fee;
