-- Ported from Oracle: db/01-Admin/0000_Phs_0800_Init.SQL

-- Generated by scripts/db-port/translate.js for mysql.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

USE phsoftme_erp_admin;


Insert Into Phs_Status (Id,Name) Values(1,'Status.Active');

Insert Into Phs_Status (Id,Name) Values(2,'Status.Disabled');

Insert Into Phs_Status (Id,Name) Values(3,'Status.Canceled');

Insert Into Phs_Front (Id,Gid,Status_Id,FDate,Name,Logo,Rem) values (1,'56A6A8851DAF44B388D0C7BA43BB7EB5',1,STR_TO_DATE('01/01/19','%d/%m/%y'),'Web Application',null,null);

Insert Into Phs_Front (Id,Gid,Status_Id,FDate,Name,Logo,Rem) values (2,'F91CDF72ADA34B66B4CF3D60E32D86DE',1,STR_TO_DATE('01/01/19','%d/%m/%y'),'Android Mobile',null,null);

Insert Into Phs_Front (Id,Gid,Status_Id,FDate,Name,Logo,Rem) values (3,'47CE4B4F71D14EAC84B6E8B09D7555F7',1,STR_TO_DATE('01/01/19','%d/%m/%y'),'iOS Mobile',null,null);

Insert Into Phs_Cst (Id,Gid,Status_Id,CDate,Name,Rem) values (0,'218983A1CE8141E9A1F30A0B9925F208',1,STR_TO_DATE('01/01/19','%d/%m/%y'),'Default Customer',null);

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 0, 0, 1, 'Default'            , 'Demo'       , 'none'       , 'C##erpDemo'      , 'PhPass', 'erpDemo.png'            , '0CB00D8E3D1D4F6E8ED225A318491670', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 1, 0, 1, 'NSCC'               , 'nscc'       , 'kobalt'     , 'C##erpNscc'      , 'PhPass', 'Nscc.png'               , '0CB00D8E3D1D4F6E8ED225A318491671', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 2, 0, 1, 'UN'                 , 'un'         , 'h-cyan'     , 'C##erpUN'        , 'PhPass', 'un.png'                 , '0CB00D8E3D1D4F6E8ED225A318491672', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 3, 0, 1, 'Epona'              , 'Epona'      , 'h-cyan'     , 'C##erpEpona'     , 'PhPass', 'epona.png'              , '0CB00D8E3D1D4F6E8ED225A318491673', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 4, 0, 1, 'NIG'                , 'nig'        , 'h-blue'     , 'C##erpNIG'       , 'PhPass', 'nig.png'                , '0CB00D8E3D1D4F6E8ED225A318491674', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 5, 0, 2, 'LRGC'               , 'LRGC'       , 'h-blue'     , 'C##erpLRGC'      , 'PhPass', 'LRGC.png'               , '0CB00D8E3D1D4F6E8ED225A318491662', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 6, 0, 2, 'iCloud'             , 'iCloud'     , 'h-cyan'     , 'C##erpiCloud'    , 'PhPass', 'iCloud.png'             , '0CB00D8E3D1D4F6E8ED225A318491676', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 7, 0, 2, 'Farkad'             , 'Farkad'     , 'h-cyan'     , 'C##erpFarkad'    , 'PhPass', 'Farkad.png'             , '0CB00D8E3D1D4F6E8ED225A318491677', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 8, 0, 1, 'E-Lcom'             , 'ELcom'      , 'h-cyan'     , 'C##erpELcom'     , 'PhPass', 'ELcom.png'              , '0CB00D8E3D1D4F6E8ED225A318491678', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values ( 9, 0, 1, 'Hashemia'           , 'Hashemia'   , 'h-cyan'     , 'C##erpHashemia'  , 'PhPass', 'Hashemia.png'           , '0CB00D8E3D1D4F6E8ED225A318491679', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (10, 0, 1, 'OLEK'               , 'OLEK'       , 'olek'       , 'C##erpOLEK'      , 'PhPass', 'OLEK.png'               , '0CB00D8E3D1D4F6E8ED225A318491680', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (13, 0, 1, 'Transportation'     , 'Trans'      , 'none'       , 'C##erpTrans'     , 'PhPass', 'erp.png'                , '0CB00D8E3D1D4F6E8ED225A318491683', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (14, 0, 1, 'Clinic'             , 'Clinic'     , 'none'       , 'C##erpClinic'    , 'PhPass', 'erpDemo.png'            , '0CB00D8E3D1D4F6E8ED225A318491685', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (21, 0, 2, 'NSCC Demo'          , 'nsccdemo'   , 'nightfall'  , 'C##Nscc'         , 'PhPass', 'Nscc.png'               , '0CB00D8E3D1D4F6E8ED225A318491687', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (22, 0, 2, 'UN Demo'            , 'undemo'     , 'nightfall'  , 'C##UN'           , 'PhPass', 'erpDemo.png'            , '0CB00D8E3D1D4F6E8ED225A318491688', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (24, 0, 1, 'SC'                 , 'SC'         , 'h-blue'     , 'C##erpSabbagh'   , 'PhPass', 'SabbaghChami.png'       , '0CB00D8E3D1D4F6E8ED225A318491690', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (26, 0, 1, 'Edu-Learn'          , 'Edulearn'   , 'h-blue'     , 'C##erpEdulearn'  , 'PhPass', 'Edu-Learn.png'          , '0CB00D8E3D1D4F6E8ED225A318491692', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (27, 0, 1, 'Midani'             , 'Midani'     , 'h-blue'     , 'C##erpMidani'    , 'PhPass', 'erpDemo.png'            , '0CB00D8E3D1D4F6E8ED225A318491693', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (27, 0, 1, 'Midani2026'         , 'Midani 2026', 'h-blue'     , 'C##erpMidani2026', 'PhPass', 'erpDemo.png'            , '0CB00D8E3D1D4F6E8ED225A318491694', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_Cpy (Id, Cst_Id, Status_Id, Name, URL, Theme, Ouser, Opass, Logo, Gid, CDate, EDate) values (29, 0, 1, 'MKM'                , 'AlKamal'    , 'h-blue'     , 'C##erpMKM'       , 'PhPass', 'mkm.png'                , '0CB00D8E3D1D4F6E8ED225A318491695', STR_TO_DATE('01/01/24','%d/%m/%y'), STR_TO_DATE('31/12/99','%d/%m/%y'));

Insert Into Phs_CpyFront (Id,Gid,Cpy_Id,Front_Id,Status_Id,CDate,Rem) values (0,'044F9ADC509C4C3FB46370D930CA599D',0,1,1,STR_TO_DATE('01/01/19','%d/%m/%y'),null);
