-- Ported from Oracle: db/01-Copy/0001_PhS_0112_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


CREATE SEQUENCE IF NOT EXISTS Phs_LogId_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Phs_Log       				                  -- سجل العمليات
( Id          BIGINT NOT NULL,			              -- مفتاح رئيسي
  vType       VARCHAR(50),			                -- النوع
  vText       VARCHAR(1024),				            -- النص
  vUser       VARCHAR(100),				              -- المستخدم
  vIP         VARCHAR(20),				              -- العنوان
  vHost       VARCHAR(64),				              -- الموقع
  vPort       VARCHAR(6),				                -- البوابة
  vRem        VARCHAR(250),			                -- ملاحظات
  dDate       TIMESTAMP Default LOCALTIMESTAMP,                   -- التاريخ والوقت
  CONSTRAINT PhsLog_PK     PRIMARY KEY (Id)
);

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION TBID_Phs_Log_fn() RETURNS TRIGGER AS $$
Declare
Begin
  If NEW.Id IS NULL Then
    Select nextval('Phs_LogId_Seq')
      Into NEW.Id;
  End If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TBID_Phs_Log ON Phs_Log;
CREATE TRIGGER TBID_Phs_Log
  BEFORE INSERT
  ON Phs_Log
  FOR EACH ROW
  EXECUTE FUNCTION TBID_Phs_Log_fn();

-- TODO(port): procedure has no automatic equivalent (source line 31).
-- Original Oracle statement:
--   Create OR Replace Procedure Phs_AddLog (
--     vText Varchar2,
--     vType Varchar2 := 'INFO',
--     vUser Varchar2 := '',
--     vIP   Varchar2 := '',
--     vHost Varchar2 := '',
--     vPort Varchar2 := '',
--     vRem  Varchar2 := '') IS
--   Begin
--     INSERT INTO Phs_Log
--           (Id                   , vType, vText, vUser, vIP, vHost, vPort, vRem)
--     VALUES(Phs_LogId_Seq.NextVal, vType, vText, vUser, vIP, vHost, vPort, vRem);
--   End Phs_AddLog;

CREATE SEQUENCE IF NOT EXISTS Phs_Audit_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Phs_Audit       				                -- سجل العمليات
( Id          BIGINT NOT NULL,			              -- مفتاح رئيسي
  nType       SMALLINT Default 1,			              -- النوع 1=إضافة, 2=تعديل, 3=حذف
  vTable      VARCHAR(50),				              -- الجدول
  User_Id     BIGINT Default 0,                    -- المستخدم
  dDate       TIMESTAMP Default LOCALTIMESTAMP,                   -- التاريخ والوقت
  vNew        VARCHAR(4000),				            -- القيم الجديدة
  vOld        VARCHAR(4000),				            -- القيم القديمة
  CONSTRAINT PhsAudit_PK PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Phs_Log_Exc_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Phs_Log_Exc			                  -- سجل العمليات
( Id          BIGINT NOT NULL,			              -- مفتاح رئيسي
  Type_Id     BIGINT,                             -- نوع الخطأ
  vMEssage    VARCHAR(1024),				            -- النص
  vFunction   VARCHAR(128),				              -- الإجراء
  vCode       VARCHAR(100),				              -- الرمز
  dDate       TIMESTAMP Default LOCALTIMESTAMP,                   -- التاريخ والوقت
  CONSTRAINT Phs_Log_Exc_PK PRIMARY KEY (Id)
);
