-- Ported from Oracle: db/01-Copy/0001_PhS_0611_TRIG.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Phs_TBID_Pref_Struct_fn() RETURNS TRIGGER AS $$
Declare
Begin
  If NEW.Id IS NULL Then
    Select nextval('Phs_Pref_Struct_Seq') Into NEW.Id;
  End If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Phs_TBID_Pref_Struct ON Phs_Pref_Struct;
CREATE TRIGGER Phs_TBID_Pref_Struct
  BEFORE INSERT
  ON Phs_Pref_Struct
  FOR EACH ROW
  EXECUTE FUNCTION Phs_TBID_Pref_Struct_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Phs_TBID_Dash_Blocks_fn() RETURNS TRIGGER AS $$
Declare
Begin
  If NEW.Id IS NULL Then
    Select nextval('Phs_Dash_Blocks_Seq') Into NEW.Id;
  End If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Phs_TBID_Dash_Blocks ON Phs_Dash_Blocks;
CREATE TRIGGER Phs_TBID_Dash_Blocks
  BEFORE INSERT
  ON Phs_Dash_Blocks
  FOR EACH ROW
  EXECUTE FUNCTION Phs_TBID_Dash_Blocks_fn();
