-- Ported from Oracle: db/01-Copy/0010_CPY_0135_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


----------------------------------------------------------------------------------------------------
Create Table Cpy_Cod_Print_Format                       -- جدول ترميز نماذج الطباعة
( Id         BIGINT NOT NULL,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Pkg        VARCHAR(10) NOT NULL,                   -- الموديول
  Grp        VARCHAR(10) NOT NULL,                   -- المجموعة
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  vValue     VARCHAR(100),                           -- القيمة
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Cpy_Cod_Print_Format_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Cpy_Cod_Print_Format_UK     UNIQUE      (Grp, Name)
);

INSERT INTO Cpy_Cod_Print_Format (Id, Pkg, Grp, Name, vValue) VALUES (1, 'FIN', 'INV', 'Invoice', ''   );

INSERT INTO Cpy_Cod_Print_Format (Id, Pkg, Grp, Name, vValue) VALUES (2, 'FIN', 'INV', 'IFR'    , 'IFR');

INSERT INTO Cpy_Cod_Print_Format (Id, Pkg, Grp, Name, vValue) VALUES (3, 'FIN', 'INV', 'LFR'    , 'LFR');

INSERT INTO Cpy_Cod_Print_Format (Id, Pkg, Grp, Name, vValue) VALUES (4, 'FIN', 'INV', 'CLR'    , 'CLR');

CREATE SEQUENCE IF NOT EXISTS Cpy_FDoc_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Cpy_FDoc			                   -- أنواع الوثائق المالية
( Id         BIGINT NOT NULL,                           -- مفتاح رئيسي
  Num        INTEGER Default 0,                          -- رقم
  DBCR_Id    BIGINT Default 1,			                     -- النوع 1 مدينة \ -1 دائنة
  Status_Id  BIGINT Default 1,			                     -- الحالة
  Code       VARCHAR(10) NOT NULL,				           -- الرمز
  Name       VARCHAR(100) NOT NULL,			             -- الاسم
  Rem        VARCHAR(250),			                     -- ملاحظات
  Ins_User   BIGINT, Ins_Date TIMESTAMP,
  Upd_User   BIGINT, Upd_Date TIMESTAMP,
  CONSTRAINT Cpy_FinDoc_PK        Primary Key (Id  ),
  CONSTRAINT Cpy_FinDoc_Num_UK    Unique      (Num ),
  CONSTRAINT Cpy_FinDoc_Cod_UK    Unique      (Code),
  CONSTRAINT Cpy_FinDoc_Nam_UK    Unique      (Name)
);

-- TODO(port): other has no automatic equivalent (source line 49).
-- Original Oracle statement:
--   ----------------------------------------------------------------------------------------------------
