-- Ported from Oracle: db/01-Copy/0020_MNG_0133_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


CREATE SEQUENCE IF NOT EXISTS MNG_Cod_Grp_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table MNG_Cod_Grp                                -- جدول ترميز فئات التصنيف
( Id         BIGINT NOT NULL,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  FColor     VARCHAR(100),                           -- لون النص
  BColor     VARCHAR(100),                           -- لون الخلفية
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT MNG_Cod_Grp_PK        PRIMARY KEY (Id  ),
  CONSTRAINT MNG_Cod_Grp_UK        UNIQUE      (Name)
);

Insert into MNG_Cod_Grp (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS MNG_Cod_Itm_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table MNG_Cod_Itm                                 -- جدول ترميز بنود التصنيف
( Id         BIGINT NOT NULL,                           -- مفتاح رئيسي
  Grp_Id     BIGINT Default 1,                          -- مجموعة الترميز
  Status_Id  BIGINT Default 1,                          -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT MNG_Cod_Itm_PK        PRIMARY KEY (Id  ),
  CONSTRAINT MNG_Cod_Itm_UK        UNIQUE      (Name)
);

Insert into MNG_Cod_Itm (Id,Grp_Id,Name) values (0,0,'-');

CREATE SEQUENCE IF NOT EXISTS MNG_Supp_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table MNG_Supp                                   -- دليل المتعاملين
( Id         BIGINT,                                    -- مفتاح رئيسي
  Cont_Id    BIGINT,                                    -- مفتاح المتعامل
  Num        VARCHAR(15),                            -- الرقم
  Title      VARCHAR(50),                            -- Title
  LName      VARCHAR(200) NOT NULL,                  -- الاسم محلي
  IName      VARCHAR(200),                           -- الاسم الدولي
  Owner      VARCHAR(200),                           -- اسم المالك
  Contact    VARCHAR(200),                           -- اسم شخص الاتصال
  Status_Id  BIGINT Default 1,                          -- الحالة
  SDate      TIMESTAMP,                                         -- تاريخ بداية الإسناد للمندوب
  EDate      TIMESTAMP,                                         -- تاريخ نهاية الإسناد للمندوب
  Phone      VARCHAR(50),                            -- الهاتف
  Phone1     VARCHAR(50),                            -- 1الهاتف
  Mobile     VARCHAR(50),                            -- الموبايل
  Fax        VARCHAR(50),                            -- الفاكس
  POBox      VARCHAR(50),                            -- صندوق البريد
  PCode      VARCHAR(50),                            -- الرمز البريدي
  Email      VARCHAR(50),                            -- البريد الالكتروني
  Website    VARCHAR(50),                            -- الموقع الالكتروني
  Address    VARCHAR(200),                           -- العنوان
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT MNG_Supp_PK         PRIMARY KEY (Id ),
  CONSTRAINT MNG_Supp_Num_UK     Unique      (Num),
  CONSTRAINT MNG_Supp_Name_UK    Unique      (LName    ),
  CONSTRAINT MNG_Supp_Cont_UK    Unique      (Cont_Id  ),
  CONSTRAINT MNG_Supp_Phone_UK   Unique      (Phone    )
);

INSERT INTO MNG_Supp (Id, Num, LName) VALUES (0, '-', '-');

CREATE SEQUENCE IF NOT EXISTS MNG_Supp_Class_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table MNG_Supp_Class                    -- تصنيف المتعاملين
( Id         BIGINT,                                    -- مفتاح رئيسي    
  Supp_Id    BIGINT NOT NULL,                           -- المتعامل
  Grp_Id     BIGINT NOT NULL,                           -- المجموعة
  Itm_Id     BIGINT NOT NULL,                           -- البند
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT MNG_Supp_Class_PK       PRIMARY KEY (Id),
  CONSTRAINT MNG_Supp_Class_UK       Unique      (Supp_Id, Grp_Id, Itm_Id)
);

CREATE SEQUENCE IF NOT EXISTS MNG_Supp_Cont_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table MNG_Supp_Cont                           -- جهات اتصال المتعاملين
( Id         BIGINT,                                    -- مفتاح رئيسي    
  Supp_Id    BIGINT NOT NULL,                           -- المتعامل
  Gender_Id  BIGINT Default 1,                          -- الجنس
  LName      VARCHAR(200),                           -- الاسم محلي
  IName      VARCHAR(200),                           -- الاسم العالمي
  Position   VARCHAR(100),                           -- المنصب
  Title      VARCHAR(50),                            -- الصفة  
  Phone      VARCHAR(50),                            -- الهاتف
  Mobile     VARCHAR(50),                            -- الموبايل
  Fax        VARCHAR(50),                            -- الفاكس
  Email      VARCHAR(50),                            -- البريد الالكتروني
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT MNG_Supp_Cont_PK        PRIMARY KEY (Id),
  CONSTRAINT MNG_Supp_Cont_Name_UK   Unique      (Supp_Id, LName)
);

CREATE SEQUENCE IF NOT EXISTS MNG_Supp_Bran_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table MNG_Supp_Bran                           -- فروع المتعاملين
( Id         BIGINT,                                    -- مفتاح رئيسي
  Supp_Id    BIGINT NOT NULL,                           -- المتعامل
  LName      VARCHAR(100),                           -- الاسم محلي
  IName      VARCHAR(100),                           -- الاسم العالمي
  Phone      VARCHAR(50),                            -- الهاتف
  Mobile     VARCHAR(50),                            -- الموبايل
  Fax        VARCHAR(50),                            -- الفاكس
  POBox      VARCHAR(50),                            -- صندوق البريد
  PCode      VARCHAR(50),                            -- الرمز البريدي
  Email      VARCHAR(50),                            -- البريد الالكتروني
  Address    VARCHAR(200),                           -- العنوان
  Rem        VARCHAR(250),                           -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT MNG_Supp_Bran_PK      PRIMARY KEY (Id),
  CONSTRAINT MNG_Supp_Bran_Name_UK Unique      (Supp_Id, LName)
);
