-- Ported from Oracle: db/01-Copy/0130_FIX_0600_TRIG.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBID_Fixed_fn() RETURNS TRIGGER AS $$
DECLARE
BEGIN
  BEGIN
    If NEW.Id IS NULL THEN
      SELECT nextval('Fix_Fixed_Seq') INTO NEW.Id;
    END If;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBID_Fixed ON Fix_Fixed;
CREATE TRIGGER Fix_TBID_Fixed
  BEFORE INSERT
  ON Fix_Fixed
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBID_Fixed_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBI_InTrn_fn() RETURNS TRIGGER AS $$
DECLARE
BEGIN
  NEW.CQnt := NEW.Qnt;
  If COALESCE(NEW.CQnt,0)<0 THEN
    RAISE EXCEPTION '%', 'No Qnt. For The Item '||NEW.Fixd_Id;
  END If;
  If COALESCE(NEW.CQnt,0)=0 AND COALESCE(NEW.CAmt,0)<>0 THEN
    RAISE EXCEPTION '%', 'Fixd '||NEW.Fixd_Id||' Has Amount Without Quantity';
  END If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBI_InTrn ON Fix_InTrn;
CREATE TRIGGER Fix_TBI_InTrn
  BEFORE INSERT
  ON Fix_InTrn
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBI_InTrn_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBU_InTrn_fn() RETURNS TRIGGER AS $$
DECLARE
BEGIN
  If COALESCE(NEW.CQnt,0)<0 AND COALESCE(NEW.CQnt,0)<COALESCE(OLD.CQnt,0) THEN
    RAISE EXCEPTION '%', 'No Qnt. For The Item '||NEW.Fixd_Id;
  END If;
  If COALESCE(NEW.CQnt,0)=0 AND COALESCE(NEW.CAmt,0)<>0 THEN
    RAISE EXCEPTION '%', 'Fixd '||NEW.Fixd_Id||' Has Amount Without Quantity';
  END If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBU_InTrn ON Fix_InTrn;
CREATE TRIGGER Fix_TBU_InTrn
  BEFORE UPDATE OF CQNT, CAMT
  ON Fix_InTrn
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBU_InTrn_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBI_OuTrn_fn() RETURNS TRIGGER AS $$
DECLARE
  nPrice    NUMERIC := 0;
BEGIN
  SELECT Price
    INTO nPrice
    FROM Fix_InTrn
    WHERE Id=NEW.Trn_Id;
  NEW.UCst := COALESCE(nPrice,0);
  NEW.Cst  := COALESCE(NEW.UCst,0) * COALESCE(NEW.Qnt,0);
  UPDATE Fix_InTrn SET
         CQnt=COALESCE(CQnt,0)-COALESCE(NEW.Qnt,0),
         CAmt=COALESCE(CAmt,0)-COALESCE(NEW.Cst,0)
   WHERE Id=NEW.Trn_Id;
EXCEPTION
  When No_Data_Found THEN
    RAISE EXCEPTION '%', 'Undefined Transaction '||NEW.Trn_Id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBI_OuTrn ON Fix_OuTrn;
CREATE TRIGGER Fix_TBI_OuTrn
  BEFORE INSERT
  ON Fix_OuTrn
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBI_OuTrn_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBU_OuTrn_fn() RETURNS TRIGGER AS $$
DECLARE
  nPrice    NUMERIC := 0;
BEGIN
  SELECT Price
    INTO nPrice
    FROM Fix_InTrn
    WHERE Id=NEW.Trn_Id;
  NEW.UCst := COALESCE(nPrice,0);
  NEW.Cst  := COALESCE(NEW.UCst,0) * COALESCE(NEW.Qnt,0);
  UPDATE Fix_InTrn SET
         CQnt=COALESCE(CQnt,0)+COALESCE(OLD.Qnt,0)-COALESCE(NEW.Qnt,0),
         CAmt=COALESCE(CAmt,0)+COALESCE(OLD.Cst,0)-COALESCE(NEW.Cst,0)
   WHERE Id=NEW.Trn_Id;
EXCEPTION
  WHEN No_Data_Found THEN
    RAISE EXCEPTION '%', 'Undefined Transaction '||NEW.Trn_Id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBU_OuTrn ON Fix_OuTrn;
CREATE TRIGGER Fix_TBU_OuTrn
  BEFORE UPDATE OF QNT
  ON Fix_OuTrn
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBU_OuTrn_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBD_OuTrn_fn() RETURNS TRIGGER AS $$
DECLARE
BEGIN
  UPDATE Fix_InTrn SET
         CQnt=COALESCE(CQnt,0)+COALESCE(OLD.Qnt,0),
         CAmt=COALESCE(CAmt,0)+COALESCE(OLD.Cst,0)
   WHERE Id=OLD.Trn_Id;
EXCEPTION
  WHEN No_Data_Found THEN
    RAISE EXCEPTION '%', 'Undefined Transaction '||OLD.Trn_Id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBD_OuTrn ON Fix_OuTrn;
CREATE TRIGGER Fix_TBD_OuTrn
  BEFORE DELETE
  ON Fix_OuTrn
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBD_OuTrn_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBI_LocTrn_fn() RETURNS TRIGGER AS $$
DECLARE
BEGIN
  UPDATE Fix_Intrn SET
         Loc1_Id=NEW.Loc1_Id,
         Loc2_Id=NEW.Loc2_Id,
         Loc3_Id=NEW.Loc3_Id
   WHERE Id=NEW.FTRN_ID;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBI_LocTrn ON Fix_LocTrn;
CREATE TRIGGER Fix_TBI_LocTrn
  BEFORE INSERT
  ON Fix_LocTrn
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBI_LocTrn_fn();

-- TODO(port): other has no automatic equivalent (source line 131).
-- Original Oracle statement:
--   EXCEPTION
--     When No_Data_Found THEN
--       Raise_Application_Error( -20705, 'Undefined Transaction '||:NEW.FTRN_ID );

-- TODO(port): other has no automatic equivalent (source line 134).
-- Original Oracle statement:
--   END Fix_TBI_LocTrn;

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Fix_TBI_Spctrn_fn() RETURNS TRIGGER AS $$
DECLARE
BEGIN
  UPDATE Fix_Intrn SET
         SPC1_ID  = NEW.SPC1_ID,
         SPC2_ID  = NEW.SPC2_ID,
         SPC3_ID  = NEW.SPC3_ID,
         SPC4_ID  = NEW.SPC4_ID,
         SPC5_ID  = NEW.SPC5_ID,
         SPC6     = NEW.SPC6,
         STATUS_ID= NEW.STATUS_ID
   WHERE Id = NEW.FTRN_ID;
EXCEPTION
  When No_Data_Found THEN
    RAISE EXCEPTION '%', 'Undefined Transaction '||NEW.FTRN_ID;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Fix_TBI_Spctrn ON Fix_Spctrn;
CREATE TRIGGER Fix_TBI_Spctrn
  BEFORE INSERT
  ON Fix_Spctrn
  FOR EACH ROW
  EXECUTE FUNCTION Fix_TBI_Spctrn_fn();
