-- Ported from Oracle: db/01-Copy/0130_FIX_0100_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


CREATE SEQUENCE IF NOT EXISTS FixId_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE SEQUENCE IF NOT EXISTS Fix_TmpLbl_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_TmpLbl
( Id           BIGINT,		                      -- مفتاح الأب 
  Barcode      VARCHAR(30),		                -- الباركود
  Fixd_Id      BIGINT,  		                      -- مفتاح المادة
  Num          BIGINT,  		                    -- رقم المادة
  Name         VARCHAR(100),					        -- اسم المادة
  Serial       VARCHAR(30),					          -- تسلسل
  Qnt          NUMERIC(25,3) Default 1,              -- العدد
  Dummy        SMALLINT Default 0
);

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Spec1_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Spec1                  -- جدول ترميز مواصفات الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Spec1_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Spec1_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Spec1 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Spec2_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Spec2                  -- جدول ترميز مواصفات الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Spec2_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Spec2_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Spec2 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Spec3_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Spec3                  -- جدول ترميز مواصفات الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Spec3_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Spec3_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Spec3 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Spec4_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Spec4                  -- جدول ترميز مواصفات الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Spec4_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Spec4_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Spec4 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Spec5_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Spec5                  -- جدول ترميز مواصفات الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Spec5_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Spec5_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Spec5 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Status_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Status                          -- جدول ترميز الحالة الفنية للموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Status_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Status_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Status (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Loc1_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Loc1                       -- جدول ترميز موقع الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Loc1_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Loc1_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Loc1 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Loc2_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Loc2                       -- جدول ترميز موقع الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Loc2_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Loc2_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Loc2 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Cod_Loc3_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cod_Loc3                       -- جدول ترميز موقع الموجودات
( Id         BIGINT NOT NULL,				              -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				              -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				      -- الاسم
  Rem        VARCHAR(100),          				    -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Cod_Loc3_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Fix_Cod_Loc3_UK     UNIQUE      (Name)
);

Insert into Fix_Cod_Loc3 (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Fix_Fixed_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Fixed					    -- دليل الموجودات الثابتة
( Id         BIGINT,					          -- مفتاح رئيسي
  Num        VARCHAR(25),					  -- رقم المادة
  Spc1_Id    BIGINT Default 0,				  -- تصنيف 1
  Spc2_Id    BIGINT Default 0,				  -- تصنيف 2
  Spc3_Id    BIGINT Default 0,				  -- تصنيف 3
  Spc4_Id    BIGINT Default 0,				  -- تصنيف 4
  Spc5_Id    BIGINT Default 0,				  -- تصنيف 4
  Perc       NUMERIC(6,2) Default 1,				-- نسبة الإهتلاك
  Unit_Id    BIGINT NOT NULL,				  -- الوحدة
  Acc_Id     BIGINT Default 0,         -- حساب مصروف الاهتلاك
  Acc_DId    BIGINT Default 0,         -- حساب الإهتلاك
  Acc_RId    BIGINT Default 0,         -- حساب مخصص الإهتلاك
  Acc_FId    BIGINT Default 0,         -- حساب الأصل الثابت
  Name       VARCHAR(100),					-- اسم المادة
  Rem        VARCHAR(100),					-- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Fix_Fixd_PK        PRIMARY KEY (Id),
  CONSTRAINT Fix_Fixd_Num_Uk    Unique      (Num),
  CONSTRAINT Fix_Fixd_Name_Uk   Unique      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Fix_InMst_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_InMst					    -- ترويسة حركات الإدخال
( Id          BIGINT,					        -- مفتاح رئيسي
  Num         INTEGER,					        -- رقم الوثيقة
  Period_Id   BIGINT,					        -- السنة
  Vhr_Id      BIGINT,						      -- مفتاح الوثيقة المالية
  MDoc_Id     BIGINT,						      -- مفتاح الوثيقة المالية
  Commit_Id   BIGINT Default 1,				-- حالة التثبيت
  Acc_Id      BIGINT,         				  -- الحساب
  dDate       TIMESTAMP Default LOCALTIMESTAMP,				-- تاريخ
  Rem         VARCHAR(100),					-- ملاحظات
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Fix_InMst_PK        PRIMARY KEY (Id),
  CONSTRAINT  Fix_InMst_UK        Unique      (Period_Id,Num)
);

CREATE SEQUENCE IF NOT EXISTS Fix_InTrn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_InTrn					      -- بنود حركات الإدخال
( Id          BIGINT,					          -- مفتاح رئيسي
  Mst_Id      BIGINT,					          -- مفتاح الأب
  Fixd_Id     BIGINT,					          -- المادة
  Curn_Id     BIGINT,         				    -- العملة
  Curn_Rate   NUMERIC(25,9) Default 1,       -- سعر الصرف
  Ord         INTEGER,						        -- مسلسل
  SDate       TIMESTAMP Default LOCALTIMESTAMP,				  -- تاريخ بداية اهتلاك
  EDate       TIMESTAMP Default LOCALTIMESTAMP,				  -- تاريخ نهاية اهتلاك
  Qnt         NUMERIC(25,3) Default 0,				-- الكمية
  CQnt        NUMERIC(25,3) Default 0,				-- الكمية الحالية
  SQnt        NUMERIC(25,3) Default 0,				-- الكمية ضمن المجموعة
  SCQnt       NUMERIC(25,3) Default 0,				-- الكمية الحالية ضمن المجموعة
  Price       NUMERIC(25,3) Default 0,				-- سعر الوحدة
  Amt         NUMERIC(25,3) Default 0,				-- المبلغ
  CAmt        NUMERIC(25,3) Default 0,				-- المبلغ قطع
  Perc        NUMERIC(6,2) Default 0,				-- نسبة الإهتلاك
  FTot        NUMERIC(25,3) Default 0,				-- مجمع سابق
  FAmt        NUMERIC(25,3) Default 0,				-- اهتلاك حالي
  RTot        NUMERIC(25,3) Default 0,				-- احتياطي سابق
  RAmt        NUMERIC(25,3) Default 0,				-- احتياطي حالي
  Loc1_Id     BIGINT Default 0,				  -- الموقع 1
  Loc2_Id     BIGINT Default 0,				  -- الموقع 2
  Loc3_Id     BIGINT Default 0,				  -- الموقع 3
  Status_Id   BIGINT Default 0,				  -- الحالة الفنية
  Spc1_Id     BIGINT Default 0,				  -- تخصيص 1
  Spc2_Id     BIGINT Default 0,				  -- تخصيص 2
  Spc3_Id     BIGINT Default 0,				  -- تخصيص 3
  Spc4_Id     BIGINT Default 0,				  -- تخصيص 4
  Spc5_Id     BIGINT Default 0,				  -- تخصيص 5
  Spc6        VARCHAR(200),					  -- تخصيص 6
  Rem         VARCHAR(100),					  -- ملاحظات
  Ins_User    BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User    BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT  Fix_InTrn_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Fix_OuMst_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_OuMst					  -- ترويسة حركات الإخراج
( Id          BIGINT,					        -- مفتاح رئيسي
  Num         INTEGER,					        -- رقم الوثيقة
  Period_Id   BIGINT,					        -- السنة
  MDoc_Id     BIGINT,						      -- مفتاح الوثيقة المالية
  Vhr_Id      BIGINT,						      -- مفتاح الوثيقة المالية
  Commit_Id   BIGINT Default 1,				-- حالة التثبيت
  Acc_Id      BIGINT,         				  -- الحساب
  dDate       TIMESTAMP Default LOCALTIMESTAMP,				-- تاريخ
  Rem         VARCHAR(100),					-- ملاحظات
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Fix_OuMst_PK        PRIMARY KEY (Id),
  CONSTRAINT  Fix_OuMst_UK        Unique      (Period_Id,Num)
);

CREATE SEQUENCE IF NOT EXISTS Fix_OuTrn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_OuTrn					      -- بنود حركات الإخراج
( Id         BIGINT,					          -- مفتاح رئيسي
  Mst_Id     BIGINT,					          -- مفتاح الأب
  Ord        INTEGER,						          -- مسلسل
  Cost_Id    BIGINT,        				      -- مركز الكلفة  
  Fixd_Id    BIGINT,					            -- المادة
  Trn_Id     BIGINT,					          -- مفتاح بند حركة الإدخال
  Curn_Id    BIGINT,         				    -- العملة
  Curn_Rate  NUMERIC(25,9) Default 1,        -- سعر الصرف
  Qnt        NUMERIC(25,3) Default 0,				-- الكمية
  Price      NUMERIC(25,3) Default 0,				-- سعر الوحدة
  Amt        NUMERIC(25,3) Default 0,				-- المبلغ
  CAmt       NUMERIC(25,3) Default 0,				-- المبلغ قطع
  UCst       NUMERIC(25,3) Default 0,				-- تكلفة الوحدة
  Cst        NUMERIC(25,3) Default 0,				-- الكلفة
  CCst       NUMERIC(25,3) Default 0,				-- الكلفة قطع
  Perc       NUMERIC(6,2) Default 1,				  -- نسبة الإهتلاك
  FTot       NUMERIC(25,3) Default 0,				-- مجمع سابق
  FAmt       NUMERIC(25,3) Default 0,				-- اهتلاك حالي
  RTot       NUMERIC(25,3) Default 0,				-- احتياطي سابق
  RAmt       NUMERIC(25,3) Default 0,				-- احتياطي حالي
  Rem        VARCHAR(100),					  -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Fix_OuTrn_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Fix_ResMst_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_ResMst		-- ترويسة حركات العهدة
( Id          BIGINT,					        -- مفتاح رئيسي
  Num         INTEGER,					        -- رقم الوثيقة
  Period_Id   BIGINT,					        -- السنة
  Emp_Id      BIGINT,					        -- الموظف مستلم العهدة
  Commit_Id   BIGINT Default 1,				-- حالة التثبيت
  dDate       TIMESTAMP Default LOCALTIMESTAMP,				-- تاريخ
  Rem         VARCHAR(100),					-- ملاحظات
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Fix_ResMst_PK      PRIMARY KEY (Id),
  CONSTRAINT  Fix_ResMst_UK      Unique      (Period_Id,Num)
);

CREATE SEQUENCE IF NOT EXISTS Fix_ResTrn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_ResTrn				-- بنود حركات العهدة
( Id         BIGINT,					          -- مفتاح رئيسي
  Mst_Id     BIGINT,					          -- مفتاح الأب
  Ord        INTEGER,						          -- مسلسل
  Fixd_Id    BIGINT,					            -- المادة
  FTrn_Id    BIGINT,					          -- مفتاح بند حركة الإدخال
  Qnt        NUMERIC(25,3) Default 0,				-- الكمية
  Rem        VARCHAR(100),					  -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Fix_ResTrn_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Fix_LocMst_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_LocMst		      -- ترويسة حركات الموقع
( Id          BIGINT,					        -- مفتاح رئيسي
  Num         INTEGER,					        -- رقم الوثيقة
  Period_Id   BIGINT,					        -- السنة
  dDate       TIMESTAMP Default LOCALTIMESTAMP,				-- تاريخ
  Rem         VARCHAR(100),					-- ملاحظات
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Fix_LocMst_PK      PRIMARY KEY (Id),
  CONSTRAINT  Fix_LocMst_UK      Unique      (Period_Id,Num)
);

CREATE SEQUENCE IF NOT EXISTS Fix_LocTrn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_LocTrn				      -- بنود حركات الموقع
( Id         BIGINT,					          -- مفتاح رئيسي
  FMst_Id    BIGINT,					          -- مفتاح الأب
  Ord        INTEGER,						          -- مسلسل
  Fixd_Id    BIGINT,					          -- المادة
  FTrn_Id    BIGINT,					          -- مفتاح بند حركة الإدخال
  oLoc1_Id   BIGINT Default 0,				  -- الموقع 1
  oLoc2_Id   BIGINT Default 0,				  -- الموقع 2
  oLoc3_Id   BIGINT Default 0,				  -- الموقع 3
  Loc1_Id    BIGINT Default 0,				  -- الموقع 1
  Loc2_Id    BIGINT Default 0,				  -- الموقع 2
  Loc3_Id    BIGINT Default 0,				  -- الموقع 3
  Rem        VARCHAR(100),					-- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Fix_LocTrn_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Fix_SpcMst_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_SpcMst		  -- ترويسة حركات المواصفات
( Id          BIGINT,					        -- مفتاح رئيسي
  Num         INTEGER,					        -- رقم الوثيقة
  Period_Id   BIGINT,					        -- السنة
  dDate       TIMESTAMP Default LOCALTIMESTAMP,				-- تاريخ
  Rem         VARCHAR(100),					-- ملاحظات
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Fix_SpcMst_PK      PRIMARY KEY (Id),
  CONSTRAINT  Fix_SpcMst_UK      Unique      (Period_Id,Num)
);

CREATE SEQUENCE IF NOT EXISTS Fix_SpcTrn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_SpcTrn				    -- بنود حركات تعديل المواصفات
( Id           BIGINT,					            -- مفتاح رئيسي
  FMst_Id      BIGINT,					            -- مفتاح الأب
  Ord          INTEGER,						            -- مسلسل
  Fixd_Id      BIGINT,					            -- المادة
  FTrn_Id      BIGINT,					            -- مفتاح بند حركة الإدخال
  OSpc1_Id     BIGINT Default 0,				    -- تخصيص 1
  OSpc2_Id     BIGINT Default 0,				    -- تخصيص 2
  OSpc3_Id     BIGINT Default 0,				    -- تخصيص 3
  OSpc4_Id     BIGINT Default 0,				    -- تخصيص 4
  OSpc5_Id     BIGINT Default 0,				    -- تخصيص 5
  OStatus_Id   BIGINT Default 0,				    -- الحالة الفنية
  OSpc6        VARCHAR(200),					  -- تخصيص 6
  Spc1_Id      BIGINT Default 0,				    -- تخصيص 1
  Spc2_Id      BIGINT Default 0,				    -- تخصيص 2
  Spc3_Id      BIGINT Default 0,				    -- تخصيص 3
  Spc4_Id      BIGINT Default 0,				    -- تخصيص 4
  Spc5_Id      BIGINT Default 0,				    -- تخصيص 5
  Status_Id    BIGINT Default 0,				    -- الحالة الفنية
  Spc6         VARCHAR(200),					  -- تخصيص 6
  Rem          VARCHAR(100),					  -- ملاحظات
  Ins_User     BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User     BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT   Fix_SpcTrn_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Fix_ActMst_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_ActMst		        -- ترويسة حركات الجرد
( Id          BIGINT,					        -- مفتاح رئيسي
  Num         INTEGER,					        -- رقم الوثيقة
  Period_Id   BIGINT,					        -- السنة
  Status_Id   BIGINT Default 1,				-- حالة التثبيت
  dDate       TIMESTAMP Default LOCALTIMESTAMP,				-- تاريخ
  Rem         VARCHAR(100),					-- ملاحظات
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Fix_ActMst_PK      PRIMARY KEY (Id),
  CONSTRAINT  Fix_ActMst_UK      Unique      (Period_Id,Num)
);

CREATE SEQUENCE IF NOT EXISTS Fix_ActTrn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_ActTrn				        -- بنود حركات الجرد
( Id         BIGINT,					          -- مفتاح رئيسي
  FMst_Id    BIGINT,					          -- مفتاح الأب
  Ord        INTEGER,						          -- مسلسل
  Fixd_Id    BIGINT,					            -- المادة
  FTrn_Id    BIGINT,					            -- مفتاح بند حركة الإدخال
  Qnt        NUMERIC(25,3) Default 1,				-- الكمية
  Rem        VARCHAR(100),					  -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Fix_ActTrn_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Fix_Cmt_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Cmt					        -- جدول حالات تثبيت الاهتلااكات
( Id          BIGINT,					            -- مفتاح رئيسي
  Year        SMALLINT,				              -- السنة
  Month       SMALLINT,				              -- الشهر
  Status_Id   BIGINT Default 0,				    -- الحالة
  Rel_Id      BIGINT,					            -- مفتاح الوثيقة المثبتة
  Rem         VARCHAR(100),					    -- ملاحظات
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Fix_Cmt_PK      PRIMARY KEY (Id),
  CONSTRAINT  Fix_Cmt_UK      Unique      (Year,Month)
);

CREATE SEQUENCE IF NOT EXISTS Fix_Tot_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Tot					      -- جدول تجميعات الإهتلاك للسنوات المالية
( Id         BIGINT,					          -- مفتاح رئيسي
  FYear      SMALLINT,				              -- السنة
  FMonth     SMALLINT,				              -- الشهر
  FTrn_Id    BIGINT,					          -- بند الادخال
  Fixd_Id    BIGINT,					            -- المادة
  Vhr_Id     BIGINT,						        -- مفتاح الوثيقة المالية
  Curn_Id    BIGINT,         				    -- العملة
  Curn_Rate  NUMERIC(25,9) Default 1,        -- سعر الصرف
  Qnt        NUMERIC(25,3) Default 0,				-- الكمية
  CQnt       NUMERIC(25,3) Default 0,				-- الكمية الحالية
  Price      NUMERIC(25,3) Default 0,				-- سعر الوحدة
  Amt        NUMERIC(25,3) Default 0,				-- المبلغ
  CAmt       NUMERIC(25,3) Default 0,				-- المبلغ قطع
  Perc       NUMERIC(6,2) Default 1,				  -- نسبة الإهتلاك
  FTot       NUMERIC(25,3) Default 0,				-- مجمع سابق
  FAmt       NUMERIC(25,3) Default 0,				-- اهتلاك حالي
  RTot       NUMERIC(25,3) Default 0,				-- احتياطي سابق
  RAmt       NUMERIC(25,3) Default 0,				-- احتياطي حالي
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Fix_Tot_PK        PRIMARY KEY (Id ),
  CONSTRAINT Fix_Tot_UK        Unique      (FYear,FMonth,FTrn_Id)
);

Create INDEX Fix_Tot_Year_IDX  ON Fix_Tot(FYear);

Create INDEX Fix_Tot_Month_IDX ON Fix_Tot(FMonth);

Create INDEX Fix_Tot_Fixd_IDX  ON Fix_Tot(Fixd_Id);

Create INDEX Fix_Tot_FTrn_IDX  ON Fix_Tot(FTrn_Id);

CREATE SEQUENCE IF NOT EXISTS Fix_Temp_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Fix_Temp				    -- جدول تجميعات الإهتلاك
( Id         BIGINT,					          -- مفتاح رئيسي
  FTrn_IId   BIGINT,					          -- بند الادخال
  FTrn_OId   BIGINT,					          -- بند الافتتاحي
  dDate      TIMESTAMP,						              -- التاريخ
  Cost_Id    BIGINT,					            -- مركز الكلفة
  Acc_Id     BIGINT,					            -- الحساب
  Fixd_Id    BIGINT,					            -- المادة
  Qnt        NUMERIC(25,3) Default 0,				-- الكمية
  CQnt       NUMERIC(25,3) Default 0,				-- الكمية الحالية
  Price      NUMERIC(25,3) Default 0,				-- سعر الوحدة
  Amt        NUMERIC(25,3) Default 0,				-- المبلغ
  Perc       NUMERIC(6,2) Default 1,				  -- نسبة الإهتلاك
  FTot       NUMERIC(25,3) Default 0,				-- مجمع سابق
  FAmt       NUMERIC(25,3) Default 0,				-- اهتلاك حالي
  RTot       NUMERIC(25,3) Default 0,				-- احتياطي سابق
  RAmt       NUMERIC(25,3) Default 0,				-- احتياطي حالي
  nDummy     SMALLINT Default 0
);
