-- Ported from Oracle: db/01-Copy/1100_EMP_0500_TRIG.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBI_Loan_fn() RETURNS TRIGGER AS $$
Declare
Begin
  NEW.BAmt := NEW.TAmt;
  If NEW.MAmt>0 Then
    NEW.EDate:= ADD_MONTHS(NEW.SDate,NEW.TAmt/NEW.MAmt);
  End If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBI_Loan ON Emp_Loan;
CREATE TRIGGER Emp_TBI_Loan
  BEFORE INSERT
  ON Emp_Loan
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBI_Loan_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBU_Loan_fn() RETURNS TRIGGER AS $$
Declare
Begin
  If OLD.TAmt<>NEW.TAmt Then
    NEW.BAmt := NEW.BAmt + (NEW.TAmt-OLD.TAmt);
  End If;
  If OLD.MAmt<>NEW.MAmt And NEW.MAmt>0 Then
    NEW.EDate:= ADD_MONTHS(LOCALTIMESTAMP,NEW.BAmt/NEW.MAmt);
  End If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBU_Loan ON Emp_Loan;
CREATE TRIGGER Emp_TBU_Loan
  BEFORE UPDATE
  ON Emp_Loan
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBU_Loan_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBI_PLoan_fn() RETURNS TRIGGER AS $$
Declare
Begin
  Update Emp_Loan Set
         BAmt = COALESCE(BAmt,0) - COALESCE(NEW.Amt,0)
   Where Id=NEW.Loan_Id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBI_PLoan ON Emp_PLoan;
CREATE TRIGGER Emp_TBI_PLoan
  BEFORE INSERT
  ON Emp_PLoan
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBI_PLoan_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBU_PLoan_fn() RETURNS TRIGGER AS $$
Declare
Begin
  If OLD.Loan_Id<>NEW.Loan_Id Then
    Update Emp_Loan Set
           BAmt = COALESCE(BAmt,0) + COALESCE(OLD.Amt,0)
     Where Id=OLD.Loan_Id;
    Update Emp_Loan Set
           BAmt = COALESCE(BAmt,0) - COALESCE(NEW.Amt,0)
     Where Id=NEW.Loan_Id;
  ElsIf OLD.Amt<>NEW.Amt Then
    Update Emp_Loan Set
           BAmt = COALESCE(BAmt,0) + COALESCE(OLD.Amt,0) - COALESCE(NEW.Amt,0)
     Where Id=NEW.Loan_Id;
  End If;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBU_PLoan ON Emp_PLoan;
CREATE TRIGGER Emp_TBU_PLoan
  BEFORE UPDATE
  ON Emp_PLoan
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBU_PLoan_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBD_PLoan_fn() RETURNS TRIGGER AS $$
Declare
Begin
  Update Emp_Loan Set
         BAmt = COALESCE(BAmt,0) + COALESCE(OLD.Amt,0)
   Where Id=OLD.Id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBD_PLoan ON Emp_PLoan;
CREATE TRIGGER Emp_TBD_PLoan
  BEFORE DELETE
  ON Emp_PLoan
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBD_PLoan_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBI_ChGrade_fn() RETURNS TRIGGER AS $$
Declare
  nODegree   NUMERIC;
Begin
  SELECT TGrad_Id INTO nODegree FROM Emp_Emp WHERE Id=NEW.Emp_Id;
  NEW.TGrad_OId := nODegree;
  UPDATE Emp_Emp Set
         TGrad_Id = NEW.TGrad_NId,
         GradDays = NEW.Days ,
         GradSDate= NEW.SDate,
         GradCons = 0,
         GradPuns = 0
   WHERE Id=NEW.Emp_Id;
Exception
  When Others Then
    NULL;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBI_ChGrade ON Emp_ChGrade;
CREATE TRIGGER Emp_TBI_ChGrade
  BEFORE INSERT
  ON Emp_ChGrade
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBI_ChGrade_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBU_ChGrade_fn() RETURNS TRIGGER AS $$
Declare
  nODegree   NUMERIC;
Begin
  IF NEW.Emp_Id!=OLD.Emp_Id Then
    UPDATE Emp_Emp Set
           TGrad_Id = OLD.TGrad_OId
     WHERE Id=OLD.Emp_Id;
  End If;
  SELECT TGrad_Id INTO nODegree FROM Emp_Emp WHERE Id=NEW.Emp_Id;
  NEW.TGrad_OId := nODegree;
  UPDATE Emp_Emp Set
         TGrad_Id = NEW.TGrad_NId,
         GradDays = NEW.Days ,
         GradSDate= NEW.SDate,
         GradCons = 0,
         GradPuns = 0
   WHERE Id=NEW.Emp_Id;
Exception
  When Others Then
    NULL;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBU_ChGrade ON Emp_ChGrade;
CREATE TRIGGER Emp_TBU_ChGrade
  BEFORE UPDATE
  ON Emp_ChGrade
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBU_ChGrade_fn();

-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Emp_TBD_ChGrade_fn() RETURNS TRIGGER AS $$
Declare
Begin
  UPDATE Emp_Emp Set
         TGrad_Id = OLD.TGrad_OId
   WHERE Id=OLD.Emp_Id;
Exception
  When Others Then
    NULL;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Emp_TBD_ChGrade ON Emp_ChGrade;
CREATE TRIGGER Emp_TBD_ChGrade
  BEFORE DELETE
  ON Emp_ChGrade
  FOR EACH ROW
  EXECUTE FUNCTION Emp_TBD_ChGrade_fn();
