-- Ported from Oracle: db/01-Copy/1401_POR_0100_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


--set Pagesize 1000
--select 'Drop table '   || table_name                          || ';' from user_tables    where table_name    like 'POR%' ;
--select 'Drop Synonym ' || Synonym_name                        || ';' from user_Synonyms  where Synonym_name  like 'POR%' ;
--select 'Drop Sequence '|| Sequence_name                       || ';' from user_Sequences where Sequence_name like 'POR%' ;
--select 'Drop View '    || View_name                           || ';' from user_Views     where View_name     like 'POR%' ;
--select 'Drop '         || OBJECT_TYPE   || ' ' || Object_name || ';' from user_Objects   where Object_name   like 'POR%' ;
----------------------------------------------------------------------------------------------------
Create Table Por_Cod_Status                              -- جدول ترميز حالة الطلب
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				                  -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				          -- الاسم
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_Cod_Status_PK        PRIMARY KEY (Id  ),
  CONSTRAINT Por_Cod_Status_UK        UNIQUE      (Name)
);

Insert into Por_Cod_Status (Id,Name) values (0,'-');

Insert into Por_Cod_Status (Id,Name) values (1,'جديد');

Insert into Por_Cod_Status (Id,Name) values (2,'موافقة مدير');

Insert into Por_Cod_Status (Id,Name) values (3,'موافقة آمر الشراء');

Insert into Por_Cod_Status (Id,Name) values (4,'مرفوض');

Insert into Por_Cod_Status (Id,Name) values (5,'ملغى');

Insert into Por_Cod_Status (Id,Name) values (6,'تم');

CREATE SEQUENCE IF NOT EXISTS Por_MReq_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_MReq                              -- جدول ترويسة الطلب
( Id          BIGINT NOT NULL,				                  -- مفتاح رئيسي
  User_Id     BIGINT Default 1,				                -- المستخدم
  Status_Id   BIGINT Default 1,				                -- الحالة
  Status_Date TIMESTAMP,                                       -- تاريخ الحالة
  Num         BIGINT Default 0,                       -- الرقم
  dDate       TIMESTAMP,                                       -- التاريخ
  Rem         VARCHAR(100),          				        -- ملاحظات
  Ins_User    BIGINT, Ins_Date     TIMESTAMP,
  Upd_User    BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT  Por_MReq_PK        PRIMARY KEY (Id ),
  CONSTRAINT  Por_MReq_UK        UNIQUE      (Num)
);

CREATE SEQUENCE IF NOT EXISTS Por_TReq_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_TReq                              -- جدول بنود الطلب
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,				                  -- مفتاح الأب
  Item_Id    BIGINT NOT NULL,				                  -- المادة
  Qnt        NUMERIC(25,3) Default 0,                      -- الكمية
  Price      NUMERIC(25,2) Default 0,                      -- السعر المتوقع
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_TReq_PK         PRIMARY KEY (Id  ),
  CONSTRAINT Por_TReq_UK         UNIQUE      (Mst_Id, Item_Id)
);

CREATE SEQUENCE IF NOT EXISTS Por_MPurOrd_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_MPurOrd                       -- جدول ترويسة أمر الشراء
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  Req_Id     BIGINT Default 0 NOT NULL,                -- العرض
  User_Id    BIGINT NOT NULL,				                  -- المستخدم
  Cont_Id    BIGINT NOT NULL,				                  -- المتعامل/المورد
  Status_Id  BIGINT Default 1,				                  -- الحالة
  Curn_Id    BIGINT NOT NULL,                          -- العملة
  Num        BIGINT Default 0,                        -- الرقم
  dDate      TIMESTAMP NOT NULL,                               -- التاريخ
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_MPurOrd_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Por_TPurOrd_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_TPurOrd                       -- جدول بنود أمر الشراء
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,				                  -- مفتاح الأب
  TReq_Id    BIGINT,                                   -- بند العرض
  Item_Id    BIGINT NOT NULL,				                  -- المادة
  Qnt        NUMERIC(25,3) Default 0,                      -- الكمية
  CQnt       NUMERIC(25,3) Default 0,                      -- الكمية المستلمة
  Price      NUMERIC(25,2) Default 0,                      -- السعر
  Vat_Perc   NUMERIC(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value  NUMERIC(25,2) Default 0,                      -- فيمة الVAT
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_TPurOrd_PK        PRIMARY KEY (Id  ),
  CONSTRAINT Por_TPurOrd_UK        UNIQUE      (Mst_Id, TReq_Id)
);

CREATE SEQUENCE IF NOT EXISTS Por_MDeliv_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_MDeliv                             -- جدول ترويسة استلام أمر الشراء
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  POrd_Id    BIGINT NOT NULL,                          -- أمر الشراء
  Cont_Id    BIGINT NOT NULL,				                  -- المتعامل/المورد
  Status_Id  BIGINT Default 1,				                  -- الحالة
  Curn_Id    BIGINT NOT NULL,                          -- العملة
  Rate       BIGINT Default 0 NOT NULL,             -- سعر الصرف
  Num        BIGINT Default 0,                        -- الرقم
  dDate      TIMESTAMP NOT NULL,                               -- التاريخ
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_MDeliv_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Por_TDeliv_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_TDeliv                             -- جدول بنود استلام أمر الشراء
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,				                  -- مفتاح الأب
  TOrd_Id    BIGINT,                                   -- بند الأمر
  Item_Id    BIGINT NOT NULL,				                  -- المادة
  Qnt        NUMERIC(25,3) Default 0,                      -- الكمية
  Price      NUMERIC(25,2) Default 0,                      -- السعر
  CAmt       NUMERIC(25,2) Default 0,                      -- القيمة بالعملة
  Amt        NUMERIC(25,2) Default 0,                      -- القيمة محلي
  Vat_Perc   NUMERIC(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value  NUMERIC(25,2) Default 0,                      -- فيمة الVAT
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_TDeliv_PK      PRIMARY KEY (Id),
  CONSTRAINT Por_TDeliv_UK      UNIQUE      (Mst_Id, TOrd_Id)
);

CREATE SEQUENCE IF NOT EXISTS Por_MPor_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_MPur                             -- جدول ترويسة الشراء
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  Cont_Id    BIGINT NOT NULL,				                  -- المتعامل/المورد
  Status_Id  BIGINT Default 1,				                  -- الحالة
  Curn_Id    BIGINT NOT NULL,                          -- العملة
  Rate       BIGINT Default 0 NOT NULL,             -- سعر الصرف
  Num        BIGINT Default 0,                        -- الرقم
  dDate      TIMESTAMP NOT NULL,                               -- التاريخ
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_MPor_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Por_TPor_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Por_TPur                             -- جدول بنود الشراء
( Id         BIGINT NOT NULL,				                  -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,				                  -- مفتاح الأب
  Item_Id    BIGINT NOT NULL,				                  -- المادة
  Qnt        NUMERIC(25,3) Default 0,                      -- الكمية
  Price      NUMERIC(25,2) Default 0,                      -- السعر
  CAmt       NUMERIC(25,2) Default 0,                      -- القيمة بالعملة
  Amt        NUMERIC(25,2) Default 0,                      -- القيمة محلي
  Vat_Perc   NUMERIC(6,2) Default 0,                       -- نسبة الVAT
  Vat_Value  NUMERIC(25,2) Default 0,                      -- فيمة الVAT
  Rem        VARCHAR(100),          				        -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Por_TPor_PK      PRIMARY KEY (Id)
);

-- TODO(port): other has no automatic equivalent (source line 225).
-- Original Oracle statement:
--   ----------------------------------------------------------------------------------------------------
