-- Ported from Oracle: db/01-Copy/7010_PROJ_0300_VIEW.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


CREATE OR REPLACE VIEW Proj_VProject AS
SELECT
       PR.Id             Proj_Id,
       PR.Name           Proj_Name,
       PR.Progress       Proj_Progress,
       PR.SDate          Proj_SDate,
       PR.EDate          Proj_EDate,
       PR.ASDate         Proj_ASDate,
       PR.AEDate         Proj_AEDate,
       PR.Rem            Proj_Rem,
       PR.Descr          Proj_Descr,
       PR.Cust_Id        Proj_Cust_Id,
       CU.Name           Cust_Name,
       CU.Cat_Id         Cust_Cat_Id,
       CCAT.Name         Cust_Cat_Name,
       CU.Class1_Id      Cust_Class1_Id,
       CC1.Name          Cust_Class1_Name,
       CU.Class2_Id      Cust_Class2_Id,
       CC2.Name          Cust_Class2_Name,
       CU.Class3_Id      Cust_Class3_Id,
       CC3.Name          Cust_Class3_Name,
       PR.Type_Id        Proj_Type_Id,
       TY.Name           Type_Name,
       PR.Status_Id      Proj_Status_Id,
       ST.Name           Status_Name,
       PR.Priority_Id    Proj_Priority_Id,
       PRI.Name          Priority_Name,
       PR.Member_Id      Proj_Member_Id,
       TM.Name           Member_Name,
       PR.Class1_Id      Proj_Class1_Id,
       PC1.Name          Proj_Class1_Name,
       PR.Class2_Id      Proj_Class2_Id,
       PC2.Name          Proj_Class2_Name,
       PR.Class3_Id      Proj_Class3_Id,
       PC3.Name          Proj_Class3_Name,
       PR.Curn_Id        Proj_Curn_Id,
       CR.Name           Curn_Name,
       PR.Ins_User       Proj_Ins_User,
       PR.Ins_Date       Proj_Ins_Date,
       PR.Upd_User       Proj_Upd_User,
       PR.Upd_Date       Proj_Upd_Date
  FROM Proj_Proj PR
  LEFT JOIN Proj_Cust              CU   ON PR.Cust_Id     = CU.Id
  LEFT JOIN Proj_Cod_Cust_Cat      CCAT ON CU.Cat_Id      = CCAT.Id
  LEFT JOIN Proj_Cod_Cust_Class1   CC1  ON CU.Class1_Id   = CC1.Id
  LEFT JOIN Proj_Cod_Cust_Class2   CC2  ON CU.Class2_Id   = CC2.Id
  LEFT JOIN Proj_Cod_Cust_Class3   CC3  ON CU.Class3_Id   = CC3.Id
  LEFT JOIN Proj_Cod_Type          TY   ON PR.Type_Id     = TY.Id
  LEFT JOIN Proj_Cod_Status        ST   ON PR.Status_Id   = ST.Id
  LEFT JOIN Proj_Cod_Priority      PRI  ON PR.Priority_Id = PRI.Id
  LEFT JOIN Proj_Team              TM   ON PR.Member_Id   = TM.Id
  LEFT JOIN Proj_Cod_Proj_Class1   PC1  ON PR.Class1_Id   = PC1.Id
  LEFT JOIN Proj_Cod_Proj_Class2   PC2  ON PR.Class2_Id   = PC2.Id
  LEFT JOIN Proj_Cod_Proj_Class3   PC3  ON PR.Class3_Id   = PC3.Id
  LEFT JOIN Mng_Curn               CR   ON PR.Curn_Id     = CR.Id;

CREATE OR REPLACE VIEW Proj_VFollowUp AS
SELECT
       TS.Id             TSheet_Id,
       TS.DDate          TSheet_Date,
       TS.Hours          TSheet_Hours,
       TS.SPrice         TSheet_SPrice,
       TS.CPrice         TSheet_CPrice,
       TS.CAmt           TSheet_CAmt,
       TS.Amt            TSheet_Amt,
       TS.CCst           TSheet_CCst,
       TS.Cst            TSheet_Cst,
       TS.Rem            TSheet_Rem,
       TS.Proj_Id        TSheet_Proj_Id,
       PR.Name           Proj_Name,
       TS.Team_Id        TSheet_Team_Id,
       TM.Name           Team_Name,
       TM.Class1_Id      Team_Class1_Id,
       MC1.Name          Team_Class1_Name,
       TM.Class2_Id      Team_Class2_Id,
       MC2.Name          Team_Class2_Name,
       TM.Class3_Id      Team_Class3_Id,
       MC3.Name          Team_Class3_Name,
       TS.MWItem_Id      TSheet_MWItem_Id,
       MW.Name           MWItem_Name,
       TS.TWItem_Id      TSheet_TWItem_Id,
       TW.Name           TWItem_Name,
       TS.SCurn_Id       TSheet_SCurn_Id,
       SCR.Name          SCurn_Name,
       TS.SCurn_Rate     TSheet_SCurn_Rate,
       TS.CCurn_Id       TSheet_CCurn_Id,
       CCR.Name          CCurn_Name,
       TS.CCurn_Rate     TSheet_CCurn_Rate,
       TS.Ins_User       TSheet_Ins_User,
       TS.Ins_Date       TSheet_Ins_Date,
       TS.Upd_User       TSheet_Upd_User,
       TS.Upd_Date       TSheet_Upd_Date
  FROM Proj_Proj_TSheet TS
  LEFT JOIN Proj_Proj              PR  ON TS.Proj_Id      = PR.Id
  LEFT JOIN Proj_Team              TM  ON TS.Team_Id      = TM.Id
  LEFT JOIN Proj_Cod_Member_Class1 MC1 ON TM.Class1_Id    = MC1.Id
  LEFT JOIN Proj_Cod_Member_Class2 MC2 ON TM.Class2_Id    = MC2.Id
  LEFT JOIN Proj_Cod_Member_Class3 MC3 ON TM.Class3_Id    = MC3.Id
  LEFT JOIN Proj_MWItem            MW  ON TS.MWItem_Id    = MW.Id
  LEFT JOIN Proj_TWItem            TW  ON TS.TWItem_Id    = TW.Id
  LEFT JOIN Mng_Curn               SCR ON TS.SCurn_Id     = SCR.Id
  LEFT JOIN Mng_Curn               CCR ON TS.CCurn_Id     = CCR.Id;

CREATE OR REPLACE VIEW Proj_VExpense AS
SELECT
       EX.Id             Exp_Id,
       EX.DDate          Exp_Date,
       EX.Qnt            Exp_Qnt,
       EX.Price          Exp_Price,
       EX.CAmt           Exp_CAmt,
       EX.Amt            Exp_Amt,
       EX.Billable_Id    Exp_Billable_Id,
       BL.Name           Billable_Name,
       EX.Billed_Id      Exp_Billed_Id,
       BD.Name           Billed_Name,    
       EX.Rem            Exp_Rem,
       EX.Proj_Id        Exp_Proj_Id,
       PR.Name           Proj_Name,
       EX.Serv_Id        Exp_Serv_Id,
       SV.Name           Serv_Name,
       EX.Curn_Id        Exp_Curn_Id,
       CR.Name           Curn_Name,
       EX.Curn_Rate      Exp_Curn_Rate,
       EX.Ins_User       Exp_Ins_User,
       EX.Ins_Date       Exp_Ins_Date,
       EX.Upd_User       Exp_Upd_User,
       EX.Upd_Date       Exp_Upd_Date
  FROM Proj_Proj_Expense EX
  LEFT JOIN Proj_Proj              PR  ON EX.Proj_Id     = PR.Id
  LEFT JOIN Mng_Serv               SV  ON EX.Serv_Id     = SV.Id
  LEFT JOIN Mng_Curn               CR  ON EX.Curn_Id     = CR.Id
  LEFT JOIN Phs_Cod_YesNo          BL  ON EX.Billable_Id = BL.Id
  LEFT JOIN Phs_Cod_YesNo          BD  ON EX.Billed_Id   = BD.Id;

CREATE OR REPLACE VIEW Proj_VInvoice AS
SELECT
       MI.Id             MInv_Id,
       MI.Num            MInv_Num,
       MI.dDate          MInv_Date,
       MI.DueDate        MInv_DueDate,
       MI.Paid_Id        MInv_Paid_Id,
       MI.Paid_Amt       MInv_Paid_Amt,
       MI.Paid_Date      MInv_Paid_Date,
       MI.Rem            MInv_Rem,
       MI.Period_Id      MInv_Period_Id,
       CP.Name           Period_Name,
       MI.Status_Id      MInv_Status_Id,
       ST.Name           Status_Name,
       MI.Cust_Id        MInv_Cust_Id,
       CU.Name           Cust_Name,
       MI.Ins_User       MInv_Ins_User,
       MI.Ins_Date       MInv_Ins_Date,
       MI.Upd_User       MInv_Upd_User,
       MI.Upd_Date       MInv_Upd_Date,
       TI.Id             TInv_Id,
       TI.Mst_Id         TInv_Mst_Id,
       TI.nOrd           TInv_nOrd,
       TI.Qnt            TInv_Qnt,
       TI.Price          TInv_Price,
       TI.CAmt           TInv_CAmt,
       TI.Amt            TInv_Amt,
       TI.Rem            TInv_Rem,
       TI.Proj_Id        TInv_Proj_Id,
       PR.Name           Proj_Name,
       TI.TSheet_Id      TInv_TSheet_Id,
       TI.Type_Id        TInv_Type_Id,
       FCT.Name          Type_Name,
       TI.Unit_Id        TInv_Unit_Id,
       UN.Name           Unit_Name,
       TI.Curn_Id        TInv_Curn_Id,
       CR.Name           Curn_Name,
       TI.Curn_Rate      TInv_Curn_Rate,
       TI.Ins_User       TInv_Ins_User,
       TI.Ins_Date       TInv_Ins_Date,
       TI.Upd_User       TInv_Upd_User,
       TI.Upd_Date       TInv_Upd_Date
  FROM Proj_MInv MI
  JOIN Proj_TInv                 TI  ON MI.Id         = TI.Mst_Id
  LEFT JOIN Proj_Cust            CU  ON MI.Cust_Id    = CU.Id
  LEFT JOIN Proj_Fin_Cod_Status  ST  ON MI.Status_Id  = ST.Id
  LEFT JOIN Cpy_Period           CP  ON MI.Period_Id  = CP.Id
  LEFT JOIN Proj_Proj            PR  ON TI.Proj_Id    = PR.Id
  LEFT JOIN Proj_Fin_Cod_Type    FCT ON TI.Type_Id    = FCT.Id
  LEFT JOIN Cpy_Unit             UN  ON TI.Unit_Id    = UN.Id
  LEFT JOIN Mng_Curn             CR  ON TI.Curn_Id    = CR.Id;
