-- Ported from Oracle: db/01-Copy/7030_CLNC_0500_TRIG.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


-- REVIEW(port): trigger translated mechanically; verify before use.

CREATE OR REPLACE FUNCTION Clnc_TBI_Labor_Receive_fn() RETURNS TRIGGER AS $$
Declare
Begin
  Select      Clinic_Id,      Doctor_Id,      Patient_Id,      Labor_Id
    Into NEW.Clinic_Id, NEW.Doctor_Id, NEW.Patient_Id, NEW.Labor_Id
    From Clnc_Labor_Send
    Where Id=NEW.Send_Id;
Exception
  When No_Data_Found Then
    RAISE EXCEPTION '%', 'Undefined Send Transaction';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS Clnc_TBI_Labor_Receive ON Clnc_Labor_Receive;
CREATE TRIGGER Clnc_TBI_Labor_Receive
  BEFORE INSERT
  ON Clnc_Labor_Receive
  FOR EACH ROW
  EXECUTE FUNCTION Clnc_TBI_Labor_Receive_fn();
