-- Ported from Oracle: db/01-Copy/7030_CLNC_0100_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


--set Pagesize 1000
--select 'Drop table '   || table_name                          || ';' from user_tables    where table_name    like 'CLNC%' ;
--select 'Drop Synonym ' || Synonym_name                        || ';' from user_Synonyms  where Synonym_name  like 'CLNC%' ;
--select 'Drop Sequence '|| Sequence_name                       || ';' from user_Sequences where Sequence_name like 'CLNC%' ;
--select 'Drop View '    || View_name                           || ';' from user_Views     where View_name     like 'CLNC%' ;
--select 'Drop '         || OBJECT_TYPE   || ' ' || Object_name || ';' from user_Objects   where Object_name   like 'CLNC%' ;
----------------------------------------------------------------------------------------------------
CREATE TABLE Clnc_WorkTime                                                                        -- جدول ساعات الدوام
( Id         BIGINT NOT NULL,                                                                   -- PK
  nHour      SMALLINT DEfault 0 NOT NULL,                                                         -- Hour
  nMinute    SMALLINT DEfault 0 NOT NULL,                                                         -- Minute
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Clnc_WorkTime_PK     PRIMARY KEY (Id  )
);

----------------------------------------------------------------------------------------------------
CREATE TABLE Clnc_Cod_Vat                                                                         -- جدول ترميز الVAT
( Id         BIGINT NOT NULL,				                                                           -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Clnc_Cod_Vat_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Cod_Vat_UK     UNIQUE      (Name)
);

Insert into Clnc_Cod_Vat (Id,Name) values (0,'-'      );

Insert into Clnc_Cod_Vat (Id,Name) values (1,'Percent');

Insert into Clnc_Cod_Vat (Id,Name) values (2,'Amount' );

----------------------------------------------------------------------------------------------------
CREATE TABLE Clnc_Cod_Disc                                                                    -- جدول ترميز الحسم
( Id         BIGINT NOT NULL,				                                                           -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Clnc_Cod_Disc_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Cod_Disc_UK     UNIQUE      (Name)
);

Insert into Clnc_Cod_Disc (Id,Name) values (0,'-'      );

Insert into Clnc_Cod_Disc (Id,Name) values (1,'Percent');

Insert into Clnc_Cod_Disc (Id,Name) values (2,'Amount' );

----------------------------------------------------------------------------------------------------
CREATE TABLE Clnc_Pay_Type                                                                     -- جدول طرق الدفع
( Id         BIGINT NOT NULL,				                                                           -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Clnc_Pay_Type_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Pay_Type_UK     UNIQUE      (Name)
);

Insert into Clnc_Pay_Type (Id,Name) values (0,'-'   );

Insert into Clnc_Pay_Type (Id,Name) values (1,'Cash');

----------------------------------------------------------------------------------------------------
CREATE TABLE Clnc_App_Status                                                               -- جدول حالات المواعيد
( Id         BIGINT NOT NULL,                                                                   -- PK
  Name       VARCHAR(100) NOT NULL,                                                          -- Name
  BG         VARCHAR(10) DEFAULT '#CCC' NOT NULL,                                            -- Title Background Color
  FG         VARCHAR(10) DEFAULT '#000' NOT NULL,                                            -- Title Text Color
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_App_Status_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_App_Status_UK     UNIQUE      (Name)
);

Insert into Clnc_App_Status (Id,Name,BG,FG) values (0,'New','#CCC','#000');

Insert into Clnc_App_Status (Id,Name,BG,FG) values (1,'Waiting','#CCC','#000');

Insert into Clnc_App_Status (Id,Name,BG,FG) values (2,'Progress','#CCC','#000');

Insert into Clnc_App_Status (Id,Name,BG,FG) values (3,'Done','#CCC','#000');

Insert into Clnc_App_Status (Id,Name,BG,FG) values (4,'Late','#CCC','#000');

Insert into Clnc_App_Status (Id,Name,BG,FG) values (5,'No Show','#CCC','#000');

----------------------------------------------------------------------------------------------------
CREATE TABLE Clnc_Treat_Status                                                                 -- جدول حالات المعالجة
( Id         BIGINT NOT NULL,                                                                   -- PK
  Name       VARCHAR(100) NOT NULL,                                                          -- Name
  BG         VARCHAR(10) DEFAULT '#CCC' NOT NULL,                                            -- Title Background Color
  FG         VARCHAR(10) DEFAULT '#000' NOT NULL,                                            -- Title Text Color
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Treat_Status_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Treat_Status_UK     UNIQUE      (Name)
);

Insert into Clnc_Treat_Status (Id,Name,BG,FG) values (0,'New','#CCC','#000');

CREATE SEQUENCE IF NOT EXISTS Clnc_List_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_List                                                                            -- جدول قوائم المرضى
( Id         BIGINT NOT NULL,                                                                   -- PK
  Name       VARCHAR(100) NOT NULL,                                                          -- Name
  Color      VARCHAR(10) DEFAULT '#FFFFFF00' NOT NULL,                                       -- Color
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_List_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_List_UK     UNIQUE      (Name)
);

Insert into Clnc_List (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Clnc_Cod_Shift_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Clnc_Cod_Shift                                                                       -- جدول ترميز الورديات
( Id         BIGINT NOT NULL,				                                                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				                                                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Clnc_Cod_Shift_PK        PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Cod_Shift_UK        UNIQUE      (Name)
);

Insert into Clnc_Cod_Shift (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Clnc_Cod_Nat_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Clnc_Cod_Nat                                                                 -- جدول ترميز الجنسيات
( Id         BIGINT NOT NULL,				                                                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				                                                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Clnc_Cod_Nat_PK        PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Cod_Nat_UK        UNIQUE      (Name)
);

Insert into Clnc_Cod_Nat (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Clnc_Special_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Clnc_Special                                                                         -- جدول الاختصاصات
( Id         BIGINT NOT NULL,				                                                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,				                                                           -- حالة الترميز
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT Clnc_Special_PK        PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Special_UK        UNIQUE      (Name)
);

Insert into Clnc_Special (Id,Name) values (0,'ALL');

Insert into Clnc_Special (Id,Name) values (1,'Dental');

Insert into Clnc_Special (Id,Name) values (2,'Ophthalmology');

Insert into Clnc_Special (Id,Name) values (3,'Laser');

CREATE SEQUENCE IF NOT EXISTS Clnc_Cat_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Cat                                                                         -- جدزل فئات الإجراءات
( Id         BIGINT NOT NULL,                                                                   -- PK
  Status_Id  BIGINT Default 1,				                                                           -- حالة الترميز
  Special_Id BIGINT DEFAULT 0 NOT NULL,                                                         -- Speciality
  Name       VARCHAR(100) NOT NULL,				                                                   -- الاسم
  Rem        VARCHAR(100),          				                                                 -- ملاحظات
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Cat_PK         PRIMARY KEY (Id), 
  CONSTRAINT Clnc_Cat_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Proc_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Proc                                                                       -- جدول الإجراءات
( Id       BIGINT NOT NULL,                                                                     -- PK
  Cat_Id   BIGINT NOT NULL,                                                                     -- Category
  Vat_Id   BIGINT DEFAULT 0 NOT NULL,                                                           -- Vat Type
  Code     VARCHAR(10) NOT NULL,                                                             -- Code
  Name     VARCHAR(100) NOT NULL,                                                            -- Name
  Price    NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                        -- Price
  Vat      NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                        -- Vat Percent/Amount
  Ins_User BIGINT, Ins_Date   TIMESTAMP,
  Upd_User BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Proc_PK     PRIMARY KEY (Id),
  CONSTRAINT Clnc_Proc_UK     UNIQUE      (Code)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_App_Type_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_App_Type                                                                 -- جدول أنواع المواعيد
( Id         BIGINT NOT NULL,                                                                   -- PK
  Capacity   SMALLINT DEFAULT 0 NOT NULL,                                                         -- Capacity
  Minutes    SMALLINT DEFAULT 15 NOT NULL,                                                        -- Appointment Minutes
  Name       VARCHAR(100) NOT NULL,                                                          -- Name
  Title_BG   VARCHAR(10) DEFAULT '#CCC' NOT NULL,                                            -- Title Background Color
  Title_FG   VARCHAR(10) DEFAULT '#000' NOT NULL,                                            -- Title Text Color
  Patient_FG VARCHAR(10) DEFAULT '#777' NOT NULL,                                            -- Patient Name Text Color
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_App_Type_PK     PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_App_Type_UK     UNIQUE      (Name)
);

Insert into Clnc_App_Type (Id,Name) values (0,'-');

CREATE SEQUENCE IF NOT EXISTS Clnc_Clinic_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Clinic                                                                          -- جدول العيادات
( Id         BIGINT NOT NULL,                                                                   -- PK
  Status_id  BIGINT DEFAULT 1 NOT NULL,                                                         -- Status
  Name       VARCHAR(100) NOT NULL,                                                          -- Name
  Email      VARCHAR(75),                                                                   -- Email
  Phone1     VARCHAR(30),                                                                   -- Phone 1
  Phone2     VARCHAR(30),                                                                   -- Phone 2
  Phone3     VARCHAR(30),                                                                   -- Phone 3
  Address    VARCHAR(256),                                                                   -- Address
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Clinic_PK         PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Clinic_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_User_Clinic_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_User_Clinic                                                                     -- جدول عيادات مستحدم
( Id         BIGINT NOT NULL,                                                                   -- PK
  User_Id    BIGINT NOT NULL,                                                                   -- User
  Clinic_Id  BIGINT NOT NULL,                                                                   -- Clinic
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_User_Clinic_PK        PRIMARY KEY (Id),
  CONSTRAINT Clnc_User_Clinic_UK        UNIQUE      (User_Id, Clinic_Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Doctor_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Doctor                                                                          -- جدول الأطباء
( Id          BIGINT NOT NULL,                                                                  -- PK
  Name        VARCHAR(100) NOT NULL,                                                         -- Name
  DoB         TIMESTAMP NOT NULL,                                                                       -- Birthdate
  Status_id   BIGINT DEFAULT 1 NOT NULL,                                                         -- Status
  Gender_Id   BIGINT DEFAULT 1 NOT NULL,                                                        -- Gender
  Martial_Id  BIGINT DEFAULT 1 NOT NULL,                                                        -- Martial Status
  IdType_Id   BIGINT DEFAULT 1 NOT NULL,                                                        -- Id Type
  Nat_Id      BIGINT DEFAULT 0 NOT NULL,                                                        -- Nationality
  Special_Id  BIGINT DEFAULT 0 NOT NULL,                                                        -- Speciality
  User_id     BIGINT NOT NULL,                                                                  -- Related User
  IdNum       VARCHAR(30),                                                                   -- Id Number
  NatNum      VARCHAR(25),                                                                   -- National Id
  Mobile      VARCHAR(100) NOT NULL,                                                         -- Mobile
  Phone1      VARCHAR(25),                                                                   -- Phone 1
  Phone2      VARCHAR(25),                                                                   -- Phone 2
  Email       VARCHAR(75),                                                                   -- Email
  Langs       VARCHAR(100),                                                                  -- Languages Known
  Descr       VARCHAR(100),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Doctor_PK         PRIMARY KEY (Id    ),
  CONSTRAINT Clnc_Doctor_Mobile_UK  UNIQUE      (Mobile)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Labor_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Labor                                                                       -- جدول المخابر
( Id          BIGINT NOT NULL,                                                                  -- PK
  Name        VARCHAR(100) NOT NULL,                                                         -- Name
  Mobile      VARCHAR(100),                                                                  -- Mobile
  Phone1      VARCHAR(25),                                                                   -- Phone 1
  Phone2      VARCHAR(25),                                                                   -- Phone 2
  Email       VARCHAR(75),                                                                   -- Email
  Company     VARCHAR(100),                                                                  -- Company Name
  Langs       VARCHAR(100),                                                                  -- Languages Known
  Descr       VARCHAR(100),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Labor_PK         PRIMARY KEY (Id  ),
  CONSTRAINT Clnc_Labor_Mobile_UK  UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Patient_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Patient                                                                         -- جدول المرضى
( Id          BIGINT NOT NULL,                                                                  -- PK
  Clinic_Id   BIGINT NOT NULL,                                                                  -- Patient Clinic
  Name        VARCHAR(100) NOT NULL,                                                         -- Name
  DoB         TIMESTAMP NOT NULL,                                                                       -- Birthdate
  Gender_Id   BIGINT DEFAULT 1 NOT NULL,                                                        -- Gender
  Martial_Id  BIGINT DEFAULT 1 NOT NULL,                                                        -- Martial Status
  IdType_Id   BIGINT DEFAULT 1 NOT NULL,                                                        -- Id Type
  Nat_Id      BIGINT DEFAULT 0 NOT NULL,                                                        -- Nationality
  List_Id     BIGINT DEFAULT 0 NOT NULL,                                                        -- List
  IdNum       VARCHAR(30),                                                                   -- Id Number
  NatNum      VARCHAR(25),                                                                   -- National Id
  Mobile      VARCHAR(100) NOT NULL,                                                         -- Mobile
  Phone1      VARCHAR(25),                                                                   -- Phone 1
  Phone2      VARCHAR(25),                                                                   -- Phone 2
  Email       VARCHAR(75),                                                                   -- Email
  Company     VARCHAR(100),                                                                  -- Company Name
  Langs       VARCHAR(100),                                                                  -- Languages Known
  Descr       VARCHAR(100),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Patient_PK         PRIMARY KEY (Id    ),
  CONSTRAINT Clnc_Patient_Mobile_UK  UNIQUE      (Mobile)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Pat_Note_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Pat_Note                                                                     -- جدول ملاحظات الأطباء للمرضى
( Id         BIGINT NOT NULL,                                                                   -- PK
  Patient_Id BIGINT NOT NULL,                                                                   -- Patient
  Doctor_Id  BIGINT NOT NULL,                                                                   -- Doctor
  dDate      TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,                                                        -- Date Time
  Note       VARCHAR(512) NOT NULL,                                                          -- Note
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Pat_Note_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_App_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_App                                                                      -- جدول المواعيد
( Id          BIGINT NOT NULL,                                                                  -- PK
  Clinic_Id   BIGINT NOT NULL,                                                                  -- Clinic
  Special_Id  BIGINT DEFAULT 0 NOT NULL,                                                        -- Speciality
  Status_Id   BIGINT DEFAULT 10 NOT NULL,                                                       -- Status
  Type_Id     BIGINT NOT NULL,                                                                  -- Type
  Doctor_Id   BIGINT NOT NULL,                                                                  -- Doctor
  Patient_Id  BIGINT NOT NULL,                                                                  -- Patient
  dDate       TIMESTAMP NOT NULL,                                                                       -- Date
  nHour       SMALLINT DEFAULT 0 NOT NULL,                                                        -- Appointment Hour
  nMinute     SMALLINT DEFAULT 0 NOT NULL,                                                        -- Appointment Minute
  Minutes     INTEGER DEFAULT 15 NOT NULL,                                                       -- Appointment Minutes
  Amt         NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Payment Amount
  Descr       VARCHAR(512),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Clnc_App_PK         PRIMARY KEY (Id),
  CONSTRAINT  Clnc_App_UK         UNIQUE      (Doctor_Id, dDate, nHour, nMinute)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_App_Change_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_App_Change                                                               -- جدول تبدل حالات موعد
( Id         BIGINT NOT NULL,                                                                   -- PK
  App_Id     BIGINT NOT NULL,                                                                   -- Appointment
  Status_Id  BIGINT NOT NULL,                                                                   -- Status
  dDate      TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,                                                        -- Date
  Reason     VARCHAR(256),                                                                   -- Reason
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP, 
  CONSTRAINT  Clnc_App_Change_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Invoice_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Invoice                                                                         -- جدول الفواتير
( Id              BIGINT NOT NULL,                                                              -- PK
  Clinic_Id       BIGINT NOT NULL,                                                              -- Clinic
  Patient_Id      BIGINT NOT NULL,                                                              -- Patient
  Num             INTEGER NOT NULL,                                                              -- Number
  dDate           TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,                                                   -- Date
  Disc_Id         BIGINT DEFAULT 0 NOT NULL,                                                    -- Discount Type
  Disc_Val        NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                 -- Discount Percent/Amount
  Disc_Amt        NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                 -- Discount Amount
  Disc_Reason     VARCHAR(100),                                                              -- Discount Reason
  Ins_User        BIGINT, Ins_Date   TIMESTAMP,
  Upd_User        BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Invoice_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Treat_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Treat                                                                        -- جدول المعالجة
( Id         BIGINT NOT NULL,                                                                   -- PK
  Clinic_Id  BIGINT NOT NULL,                                                                   -- Clinic
  Doctor_Id  BIGINT NOT NULL,                                                                   -- Doctor
  Patient_Id BIGINT NOT NULL,                                                                   -- Patient
  Inv_Id     BIGINT,                                                                            -- Invoice
  Status_Id  BIGINT DEFAULT 1 NOT NULL,                                                         -- Status
  dDate      TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,                                                        -- Date
  Descr      VARCHAR(512),                                                                   -- Description 
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Treat_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Treat_Proc_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Treat_Proc                                                             -- جدول إجراءات معالجة
( Id          BIGINT NOT NULL,                                                                  -- PK
  Treat_Id    BIGINT NOT NULL,                                                                  -- Treatment
  Proc_Id     BIGINT NOT NULL,                                                                  -- Procedure
  Vat_Id      BIGINT DEFAULT 0 NOT NULL,                                                        -- Vat Type
  Qnt         NUMERIC(25,3) DEFAULT 1 NOT NULL,                                                     -- Quantity
  Price       NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Price
  Discount    NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Discount
  Amt         NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Amount
  Vat_Value   NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Vat Percent/Amount Type
  Vat_Amt     NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Vat Amount
  dDate       TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,                                                       -- Date
  Descr       VARCHAR(256),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Clnc_Treat_Proc_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Invoice_Treat_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Invoice_Treat                                                               -- جدول فاتورة معالجة
( Id          BIGINT NOT NULL,                                                                  -- PK
  Inv_Id      BIGINT NOT NULL,                                                                  -- Invoices
  Treat_Id    BIGINT NOT NULL,                                                                  -- Treatment
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Clnc_Invoice_Treat_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Disc_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Disc                                                                   -- جدول الحسميات
( Id          BIGINT NOT NULL,                                                                  -- PK
  Clinic_Id   BIGINT NOT NULL,                                                                  -- Clinic
  Patient_Id  BIGINT NOT NULL,                                                                  -- Patient
  dDate       TIMESTAMP NOT NULL,                                                                       -- Date
  Amt         NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Amount
  Descr       VARCHAR(256),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Clnc_Disc_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Pay_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Pay                                                                          -- جدول دفعات الزبائن
( Id          BIGINT NOT NULL,                                                                  -- PK
  Clinic_Id   BIGINT NOT NULL,                                                                  -- Clinic
  Patient_Id  BIGINT NOT NULL,                                                                  -- Patient
  Type_Id     BIGINT DEFAULT 1 NOT NULL,                                                        -- Payment Method
  dDate       TIMESTAMP NOT NULL,                                                                       -- Date
  Amt         NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Amount
  Descr       VARCHAR(256),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Pay_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Refund_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Refund                                                                     -- جدول مرتجع التسديد لمريض
( Id          BIGINT NOT NULL,                                                                  -- PK
  Clinic_Id   BIGINT NOT NULL,                                                                  -- Clinic
  Patient_Id  BIGINT NOT NULL,                                                                  -- Patient
  dDate       TIMESTAMP NOT NULL,                                                                       -- Date
  Amt         NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                     -- Amount
  Descr       VARCHAR(256),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Refund_PK          PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Labor_Send_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Labor_Send                                                                  -- جدول إرسال العينات للمخبر
( Id         BIGINT NOT NULL,                                                                   -- PK
  Clinic_Id  BIGINT NOT NULL,                                                                   -- Clinic
  Doctor_Id  BIGINT NOT NULL,                                                                   -- Doctor
  Patient_Id BIGINT NOT NULL,                                                                   -- Patient
  Labor_Id   BIGINT NOT NULL,                                                                   -- Laboratory
  dDate      TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,                                                        -- Date
  Qnt        NUMERIC(25,3) DEFAULT 1 NOT NULL,                                                      -- Quantity
  CQnt       NUMERIC(25,3) DEFAULT 1 NOT NULL,                                                      -- Current Quantity
  Descr      VARCHAR(512),                                                                   -- Description 
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Labor_Send_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Labor_Receive_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Labor_Receive                                                               -- جدول استلام العينات من المخبر
( Id         BIGINT NOT NULL,                                                                   -- PK
  Clinic_Id  BIGINT NOT NULL,                                                                   -- Clinic
  Doctor_Id  BIGINT NOT NULL,                                                                   -- Doctor
  Patient_Id BIGINT NOT NULL,                                                                   -- Patient
  Labor_Id   BIGINT NOT NULL,                                                                   -- Laboratory
  Send_Id    BIGINT NOT NULL,                                                                   -- Related Send Id
  dDate      TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,                                                        -- Date
  Qnt        NUMERIC(25,3) DEFAULT 1 NOT NULL,                                                      -- Quantity
  Descr      VARCHAR(512),                                                                   -- Description 
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Labor_Receive_PK         PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Offer_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Offer                                                                           -- العروض
( Id          BIGINT NOT NULL,                                                                  -- PK
  Name        VARCHAR(100) NOT NULL,                                                         -- Name
  Status_Id   BIGINT DEFAULT 2 NOT NULL,                                                        -- Status
  SDate       TIMESTAMP NOT NULL,                                                                       -- Start Date
  EDate       TIMESTAMP NOT NULL,                                                                       -- End Date
  Descr       VARCHAR(512),                                                                  -- Description
  Ins_User    BIGINT, Ins_Date   TIMESTAMP,
  Upd_User    BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT  Clnc_Offer_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Offer_Clnc_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Offer_Clnc                                                                     -- عيادات عرض
( Id         BIGINT NOT NULL,                                                                   -- PK
  offer_id   BIGINT NOT NULL,                                                                   -- Offer
  Clinic_Id  BIGINT NOT NULL,                                                                   -- Clinic
  Descr      VARCHAR(512),                                                                   -- Description
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Offer_Clnc_PK        PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_Offer_Proc_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_Offer_Proc                                                                  -- جدول إجراءات عرض
( Id         BIGINT NOT NULL,                                                                   -- PK
  Offer_Id   BIGINT NOT NULL,                                                                   -- Offer
  Proc_Id    BIGINT NOT NULL,                                                                   -- Procedure
  Price      NUMERIC(25,3) DEFAULT 0 NOT NULL,                                                      -- Offer Price
  Descr      VARCHAR(512),                                                                   -- Description
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_Offer_Proc_PK           PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Clnc_User_Shift_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Clnc_User_Shift                                                                      -- جدول دوام مستحدم
( Id         BIGINT NOT NULL,                                                                   -- PK
  User_Id    BIGINT NOT NULL,                                                                   -- User
  dDate      TIMESTAMP,                                                                                 -- Date
  Shift_Id   BIGINT DEFAULT 0 NOT NULL,                                                         -- Type
  STime      INTEGER NOT NULL,                                                                   -- Start Time
  ETime      INTEGER NOT NULL,                                                                   -- End Time
  Ins_User   BIGINT, Ins_Date   TIMESTAMP,
  Upd_User   BIGINT, Upd_Date   TIMESTAMP,
  CONSTRAINT Clnc_User_Shift_PK        PRIMARY KEY (Id),
  CONSTRAINT Clnc_User_Shift_UK        UNIQUE      (dDate, User_Id, Shift_Id)
);
