-- Ported from Oracle: db/01-Copy/7040_AMS_0101_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


CREATE SEQUENCE IF NOT EXISTS Ams_SItem_Status_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_SItem_Status                   -- جدول رموز حالة المادة
( Id             BIGINT NOT NULL,                  -- مفتاح رئيسي
  Status_Id      BIGINT DEFAULT 1,                 -- حالة 
  IsCalculate_Id BIGINT DEFAULT 2 NOT NULL,        -- هل يتم الاحتساب
  IsPass_Id      BIGINT DEFAULT 1 NOT NULL,        -- هل تعتبر ناجح
  Name           VARCHAR(100) NOT NULL,              -- الاسم
  Rem            VARCHAR(100),                  -- ملاحظات
  Ins_User       BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User       BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_SItem_Status_PK              PRIMARY KEY (Id), 
  CONSTRAINT Ams_SItem_Status_UK              UNIQUE      (Name)
);

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(1 , 'N' , 2, 2, '-');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(2 , 'P' , 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(3 , 'F' , 1, 2, 'Fail');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(4 , 'I' , 1, 2, 'Incomplete');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(5 , 'T' , 2, 1, 'Transfer');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(6 , 'Z' , 1, 2, 'Deprived');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(7 , 'W' , 2, 2, 'Withdraw');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(8 , 'A+', 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(9 , 'A' , 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(10, 'A-', 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(11, 'B+', 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(12, 'B' , 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(13, 'B-', 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(14, 'C+', 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(15, 'C' , 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(16, 'C-', 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(17, 'D+', 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(18, 'D' , 1, 1, 'Passed');

INSERT INTO Ams_SItem_Status (Id, Name, IsCalculate_Id, IsPass_Id, Rem) VALUES(19, 'D-', 1, 1, 'Passed');

CREATE SEQUENCE IF NOT EXISTS Ams_Bran_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Bran                          -- جدول الفروع
( Id         BIGINT NOT NULL,                 -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,               -- حالة 
  AR_Name    VARCHAR(256) NOT NULL,        -- الاسم
  EN_Name    VARCHAR(256) Default NULL,    -- الاسم
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Bran_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Bran_UK         UNIQUE      (AR_Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_College_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Colge                            -- جدول الكليات
( Id              BIGINT NOT NULL,               -- مفتاح رئيسي
  Branch_Id       BIGINT  Default 1,             -- الفرع 
  Status_Id       BIGINT  Default 1,             -- حالة 
  AR_Name         VARCHAR(256) NOT NULL,      -- الاسم
  EN_Name         VARCHAR(256) Default NULL,  -- الاسم
  Study_Years     SMALLINT DEFAULT 0 NOT NULL ,    -- سنوات الدراسة
  Extension_Years SMALLINT DEFAULT 0 NOT NULL ,    -- سنوات التمديد
  Rem             VARCHAR(100),               -- ملاحظات
  Ins_User        BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User        BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Colge_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Colge_UK         UNIQUE      (AR_Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Sec_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Sec                       -- جدول الاقسام
( Id         BIGINT NOT NULL,               -- مفتاح رئيسي
  College_Id BIGINT  Default 1,             -- الكليات 
  Status_Id  BIGINT  Default 1,             -- حالة 
  AR_Name    VARCHAR(256) NOT NULL,      -- الاسم
  EN_Name    VARCHAR(256) Default NULL,  -- الاسم
  Rem        VARCHAR(100),               -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Sec_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Sec_UK         UNIQUE      (AR_Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Spec_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Spec                    -- جدول التخصصات
( Id         BIGINT NOT NULL,               -- مفتاح رئيسي
  Section_Id BIGINT  Default 1,             -- الاقسام 
  Status_Id  BIGINT  Default 1,             -- حالة 
  AR_Name    VARCHAR(256) NOT NULL,       -- الاسم
  EN_Name    VARCHAR(256) Default NULL,   -- الاسم
  Rem        VARCHAR(100),               -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Spec_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Spec_UK         UNIQUE      (AR_Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Cert_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Cert                    -- جدول الشهادات
( Id         BIGINT NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,              -- حالة 
  Name       VARCHAR(256) NOT NULL,       -- الاسم
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Cert_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Cert_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Dis_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Dis                       -- جدول الخصومات
( Id         BIGINT NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,              -- حالة 
  Name       VARCHAR(256) NOT NULL,       -- الاسم
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Dis_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Dis_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Fee_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Fee                           -- جدول الرسوم
( Id         BIGINT NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,              -- حالة 
  Name       VARCHAR(256) NOT NULL,       -- الاسم
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Fee_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Fee_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Item_Typ_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Item_Typ                      -- جدول انواع المواد
( Id         BIGINT NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,              -- حالة 
  Name       VARCHAR(256) NOT NULL,       -- الاسم
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Item_Typ_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Item_Typ_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Year_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Year                        -- جدول السنوات
( Id         BIGINT NOT NULL,              -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,            -- حالة 
  Name       VARCHAR(256) NOT NULL,     -- الاسم
  Rem        VARCHAR(100),              -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Year_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Year_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Term_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Term                          -- جدول الفصول
( Id         BIGINT NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,              -- حالة 
  AR_Name    VARCHAR(256) NOT NULL,       -- الاسم
  EN_Name    VARCHAR(256) Default NULL,   -- الاسم
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Term_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Term_UK         UNIQUE      (AR_Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Item_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Item                        -- جدول المواد
( Id         BIGINT NOT NULL,              -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,            -- حالة 
  Code       VARCHAR(256) NOT NULL,     -- الرمز
  AR_Name    VARCHAR(256) NOT NULL,     -- الاسم
  EN_Name    VARCHAR(256) Default NULL, -- الاسم
  Rem        VARCHAR(100),              -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Item_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Item_UK         UNIQUE      (Code)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Teacher_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Teacher                        -- جدول المدرسين
( Id         BIGINT  NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,               -- حالة 
  Name       VARCHAR(256) NOT NULL,        -- الاسم
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Teacher_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Teacher_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AYear_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AYear                   -- جدول السنوات الاكادمية
( Id        BIGINT NOT NULL,                  -- مفتاح رئيسي
  Status_Id BIGINT Default 1,                 -- حالة 
  Name      VARCHAR(100) NOT NULL,         -- الاسم
  Rem       VARCHAR(100),                  -- ملاحظات
  Ins_User  BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User  BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AYear_PK              PRIMARY KEY (Id), 
  CONSTRAINT Ams_AYear_UK              UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_ATerm_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_ATerm                 -- جدول الفصول الاكادمية
( Id              BIGINT NOT NULL,          -- مفتاح رئيسي
  AYear_Id        BIGINT  NOT NULL,         -- مفتاح الأب
  Term_Id         BIGINT  NOT NULL,         -- الفصل
  Status_Id       BIGINT  Default 1,        -- حالة 
  SDate           TIMESTAMP NOT NULL,	             -- تاريخ البداية
  EDate           TIMESTAMP NOT NULL,	             -- تاريخ النهاية
  RegstrationDate TIMESTAMP,         	             -- تاريخ البداية
  DropDate        TIMESTAMP,         	             -- تاريخ النهاية
  Rem             VARCHAR(100),          -- ملاحظات
  Ins_User        BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User        BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_ATerm_PK       PRIMARY KEY (Id), 
  CONSTRAINT Ams_ATerm_UK       UNIQUE      (AYear_Id, Term_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Degree_Lmt_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Degree_Lmt                    -- جدول حدود الدرجات
( Id         BIGINT  NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,               -- حالة 
  Name       VARCHAR(256) NOT NULL,        -- الاسم
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Degree_Lmt_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Degree_Lmt_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Degree_Lmt_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Degree_Lmt_Trn                 -- جدول بنود حدود الدرجات
( Id         BIGINT NOT NULL,                    -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,                    -- مفتاح الأب
  Code_Id    BIGINT NOT NULL,                   -- الطالب
  IsPass_Id  BIGINT Default 2,                   -- هل يعتبر ناجح 
  IsCalc_Id  BIGINT Default 2,                   -- هل تحسب ضمن المعدل
  Name       VARCHAR(100),                    -- الاسم
  Min        NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- الدرجة الدنيا 
  Max        NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- الدرجة العلية 
  Gpa        NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- المكافئ النقطي
  Rem        VARCHAR(100),                    -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Degree_Lmt_Trn_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Degree_Lmt_Trn_UK         UNIQUE      (Mst_Id, Code_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Exam_Lmt_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Exam_Lmt                      -- جدول حدود سقوف الاختبار
( Id         BIGINT  NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,               -- حالة 
  Name       VARCHAR(256) NOT NULL,        -- الاسم
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Exam_Lmt_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Exam_Lmt_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Exam_Lmt_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Exam_Lmt_Trn                      -- جدول بنود حدود سقوف الاختبار
( Id              BIGINT NOT NULL,                  -- مفتاح رئيسي
  Mst_Id          BIGINT NOT NULL,                  -- مفتاح الأب
  Type_Id         BIGINT NOT NULL,                 -- الطالب
  Mark1_Min       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 1 Minimum Required Percentage
  Mark1_Max       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 1 Max Degree
  Mark2_Min       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 2 Minimum Required Percentage
  Mark2_Max       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 2 Max Degree
  Mark3_Min       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 3 Minimum Required Percentag
  Mark3_Max       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 3 Max Degree
  Mark4_Min       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 4 Minimum Required Percentage
  Mark4_Max       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 4 Max Degree
  Mark5_Min       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 5 Minimum Required Percentage
  Mark5_Max       NUMERIC(6,2) DEFAULT 0.00 NOT NULL,   -- Mark 5 Max Degree
  Wrk_Min         NUMERIC(6,2) DEFAULT 50.00 NOT NULL,  -- Work 1-4 Minimum Required Percentage
  MarkT_Wrk       NUMERIC(6,2) DEFAULT 100.00 NOT NULL, -- نسبة درجة الأعمال من المجموع العام
  MarkT_Exm       NUMERIC(6,2) DEFAULT 100.00 NOT NULL, -- نسية الامتحان من المجموع العام
  Rem             VARCHAR(100),                  -- ملاحظات
  Ins_User        BIGINT,  Ins_Date TIMESTAMP,
  Upd_User        BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_Exam_Lmt_Trn_PK      PRIMARY KEY (Id), 
  CONSTRAINT Ams_Exam_Lmt_Trn_UK      UNIQUE      (Mst_Id, Type_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Exam_Lmt_Active_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Exam_Lmt_Active                       -- جدول تفعيل سقف الاختبار   
( Id            BIGINT NOT NULL,                     -- مفتاح رئيسي
  ATerm_Id      BIGINT NOT NULL,                      -- الفصل الاكاديمي
  ExamLmt_Id    BIGINT NOT NULL,                      -- سقف الاختبار
  Num           VARCHAR(100),                      -- الرفم
  dDate         TIMESTAMP Default LOCALTIMESTAMP,                    -- التاريخ
  Rem           VARCHAR(100),                      -- ملاحظات
  Ins_User      BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User      BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Exam_Lmt_Active_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Exam_Lmt_Active_UK         UNIQUE      (Num, ATerm_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_GPA_Lmt_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_GPA_Lmt                       -- جدول حدودالعبئ الدراسي
( Id         BIGINT  NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,               -- حالة 
  Name       VARCHAR(256) NOT NULL,        -- الاسم
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_GPA_Lmt_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_GPA_Lmt_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_GPA_Lmt_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_GPA_Lmt_Trn                  -- جدول بنود حدودالعبئ الدراسي
( Id        BIGINT NOT NULL,                   -- مفتاح رئيسي
  Mst_Id    BIGINT NOT NULL,                   -- مفتاح الأب
  Term_Id   BIGINT NOT NULL,                   -- الفصل
  Min_Gpa   NUMERIC(5,2) DEFAULT 0.00 NOT NULL,    -- GPA Minimum
  Max_Gpa   NUMERIC(5,2) DEFAULT 0.00 NOT NULL,    -- GPA Maximum
  Min_Hour  NUMERIC(5,2) DEFAULT 0.00 NOT NULL,    -- Hour Minimum
  Max_Hour  NUMERIC(5,2) DEFAULT 0.00 NOT NULL,    -- Hour Maximum
  oMin_Gpa  NUMERIC(5,2) DEFAULT 0.00 NOT NULL,    -- Outstanding GPA Minimum
  oMax_Gpa  NUMERIC(5,2) DEFAULT 4.00 NOT NULL,    -- Outstanding GPA Maximum
  oMin_Hour NUMERIC(5,2) DEFAULT 0.00 NOT NULL,    -- Outstanding Minimum
  oMax_Hour NUMERIC(5,2) DEFAULT 0.00 NOT NULL,    -- Outstanding Maximum
  Rem       VARCHAR(100),                   -- ملاحظات
  Ins_User  BIGINT,  Ins_Date TIMESTAMP,
  Upd_User  BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_GPA_Lmt_Trn_PK      PRIMARY KEY (Id), 
  CONSTRAINT Ams_GPA_Lmt_Trn_UK      UNIQUE      (Mst_Id, Term_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Grad_Level_Lmt_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Grad_Level_Lmt          -- جدول حدو درجات التخرج
( Id         BIGINT  NOT NULL,                -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,               -- حالة 
  Name       VARCHAR(256) NOT NULL,        -- الاسم
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Grad_Level_Lmt_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Grad_Level_Lmt_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Grad_Level_Lmt_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Grad_Level_Lmt_Trn     -- جدول بنود حدود درجات التخرج
( Id       BIGINT NOT NULL,                    -- مفتاح رئيسي
  Mst_Id   BIGINT NOT NULL,                    -- مفتاح الأب
  Min_Gpa  NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- Min GPA
  Max_Gpa  NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- Max GPA
  Name     VARCHAR(100),                    -- الاسم
  Rem      VARCHAR(100),                    -- ملاحظات
  Ins_User BIGINT,  Ins_Date TIMESTAMP,
  Upd_User BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_Grad_Level_Lmt_Trn_PK      PRIMARY KEY (Id), 
  CONSTRAINT Ams_Grad_Level_Lmt_Trn_UK      UNIQUE      (Mst_Id,Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Year_Lmt_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Year_Lmt                  -- جدول حدود السنوات الدراسية
( Id         BIGINT  NOT NULL,            -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,           -- حالة 
  Name       VARCHAR(256) NOT NULL,    -- الاسم
  Rem        VARCHAR(100),             -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Year_Lmt_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Year_Lmt_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Year_Lmt_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Year_Lmt_Trn                 -- جدول بنود حدود السنوات الدراسية
( Id       BIGINT NOT NULL,                    -- مفتاح رئيسي
  Mst_Id   BIGINT NOT NULL,                    -- مفتاح الأب
  Year_Id  BIGINT NOT NULL,                    -- مفتاح السنة
  Min      NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- الحد الأدنى للساعات
  Max      NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- الحد الاعلى للساعات
  Rem      VARCHAR(100),                    -- ملاحظات
  Ins_User BIGINT,  Ins_Date TIMESTAMP,
  Upd_User BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_Year_Lmt_Trn_PK      PRIMARY KEY (Id), 
  CONSTRAINT Ams_Year_Lmt_Trn_UK      UNIQUE      (Mst_Id,Year_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Price_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Price                      -- جدول قوائم الاسعار
( Id         BIGINT  NOT NULL,            -- مفتاح رئيسي
  Status_Id  BIGINT  Default 1,           -- حالة 
  Name       VARCHAR(256) NOT NULL,    -- الاسم
  Rem        VARCHAR(100),             -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Price_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Price_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Plan_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Plan                              -- جدول الخطط الدراسية
( Id                  BIGINT NOT NULL,                -- مفتاح رئيسي
  Branch_Id           BIGINT Default 1,               -- الفرع 
  ExamLmt_Id          BIGINT NOT NULL,                -- حدود سقوف الاختبار
  Degreelmt_Id        BIGINT NOT NULL,                -- حدود الدرجات 
  Gpalmt_Id           BIGINT NOT NULL,                -- حدود العبىء الدراسي
  Yearlmt_Id          BIGINT NOT NULL,                -- حدود السنوات
  Gradlevellmt_Id     BIGINT NOT NULL,                -- حدود درجات التخرج
  Price_Id            BIGINT NOT NULL,                -- الاسعار
  isNational_Exam_Id  BIGINT Default 1,               -- هل يوجد امتحان وطني
  Status_Id           BIGINT Default 1,               -- حالة 
  AR_Name             VARCHAR(256) NOT NULL,       -- الاسم
  EN_Name             VARCHAR(256),                -- الاسم
  Total_Hour          SMALLINT,                         -- عدد الساعات الكلي
  Rem                 VARCHAR(100),                -- ملاحظات
  Ins_User            BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User            BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Plan_PK               PRIMARY KEY (Id), 
  CONSTRAINT Ams_Plan_UK               UNIQUE      (AR_Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Plan_Edit_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Plan_Edit                         -- جدول تعديل الخطط الدراسية
( Id                      BIGINT  NOT NULL,           -- مفتاح رئيسي
  Plan_Id                 BIGINT NOT NULL,            -- الخطة الدراسية
  Old_ExamLmt_Id          BIGINT NOT NULL,            -- حدود سقوف الاختبار قديم
  Old_Degreelmt_Id        BIGINT NOT NULL,            -- حدود الدرجات قديم
  Old_Gpalmt_Id           BIGINT NOT NULL,            -- حدود العبىء الدراسي قديم
  Old_Yearlmt_Id          BIGINT NOT NULL,            -- حدود السنوات قديم
  Old_Gradlevellmt_Id     BIGINT NOT NULL,            -- حدود درجات التخرج قديم
  Old_Price_Id            BIGINT NOT NULL,            -- الاسعار قديم
  Old_isNational_Exam_Id  BIGINT Default 1,           -- هل يوجد امتحان وطني قديم
  New_ExamLmt_Id          BIGINT NOT NULL,            -- حدود سقوف الاختبار جديد
  New_Degreelmt_Id        BIGINT NOT NULL,            -- حدود الدرجات جديد
  New_Gpalmt_Id           BIGINT NOT NULL,            -- حدود العبىء الدراسي جديد
  New_Yearlmt_Id          BIGINT NOT NULL,            -- حدود السنوات جديد
  New_Gradlevellmt_Id     BIGINT NOT NULL,            -- حدود درجات التخرج جديد
  New_Price_Id            BIGINT NOT NULL,            -- الاسعار جديد
  New_isNational_Exam_Id  BIGINT Default 1,           -- هل يوجد امتحان وطني جديد
  Status_Id               BIGINT Default 1,           -- حالة 
  Num                     VARCHAR(128) NOT NULL,   -- رقم
  dDate                   TIMESTAMP Default LOCALTIMESTAMP,          -- التاريخ
  Rem                     VARCHAR(100),            -- ملاحظات
  Ins_User                BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User                BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Plan_Edit_PK                   PRIMARY KEY (Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_PItem_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_PItem                   -- جدول مواد الخطة الدراسية
( Id            BIGINT  NOT NULL,              -- مفتاح رئيسي
  Plan_Id       BIGINT NOT NULL,                -- الخطة الدراسية
  Colleg_Id     BIGINT DEFAULT 0 NOT NULL,      -- الكلي
  Section_Id    BIGINT DEFAULT 0 NOT NULL,      -- القسم  
  Speciality_Id BIGINT DEFAULT 0 NOT NULL,      -- التخصص
  Item_Type_Id  BIGINT DEFAULT 0 NOT NULL,      -- نوع المادة
  Year_Id       BIGINT DEFAULT 0 NOT NULL,      -- السنة 
  Term_Id       BIGINT DEFAULT 0 NOT NULL,      -- الفصل
  Item_Id       BIGINT DEFAULT 0 NOT NULL,      -- المادة
  Status_Id     BIGINT DEFAULT 1 NOT NULL,      -- الحالة
  Force_Id      BIGINT DEFAULT 1 NOT NULL,      -- اجباري ,اختياري , بند اختيار
  Kind_Id       BIGINT DEFAULT 1 NOT NULL,      -- عادي , تابع لمتطلب
  Choice_Group  SMALLINT DEFAULT 0 NOT NULL,      -- ترميز اختياري  
  credit        NUMERIC(4,2) DEFAULT 1.00 NOT NULL, -- عدد ساعات المادة
  Min_Req_Hour  SMALLINT DEFAULT 0 NOT NULL,      -- الحد الادنى للساعات لختيار المادة,
  Rem           VARCHAR(100),                -- ملاحظات
  Ins_User      BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User      BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_PItem_PK             PRIMARY KEY (Id), 
  CONSTRAINT Ams_PItem_UK             UNIQUE      (Plan_Id,Colleg_Id,Section_Id,Speciality_Id,Year_Id,Term_Id,Item_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_PItem_Ord_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_PItem_Ord             -- جدول المتطلب السابق لمواد الخطة الدراسية
( Id              BIGINT  NOT NULL,            -- مفتاح رئيسي
  PItem_Id        BIGINT NOT NULL,             -- مادة الخطة الدراسية
  OPItem_Id       BIGINT NOT NULL,             -- مادة الخطة الدراسية متطلب
  Rem             VARCHAR(100),              -- ملاحظات
  Ins_User        BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User        BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_PItem_Ord_PK        PRIMARY KEY (Id), 
  CONSTRAINT Ams_PItem_Ord_UK        UNIQUE      (PItem_Id, OPItem_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Stud_Seq
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE Ams_Stud (                           -- جدول الطلاب
  Id                BIGINT NOT NULL,             -- مفتاح رئيسي
  Nat_Id            BIGINT DEFAULT NULL,          -- الجنسية
  Country_Id        BIGINT DEFAULT NULL,          -- الدولة
  City_Id           BIGINT DEFAULT NULL,          -- المدينة
  Martial_Id        BIGINT DEFAULT NULL,          --FK Martial
  Gender_Id         BIGINT DEFAULT NULL,          --FK Gendeer
  AYear_Id          BIGINT DEFAULT NULL,          --FK Academic Year
  Term_Id           BIGINT DEFAULT NULL,          --FK Term
  Year_Id           BIGINT DEFAULT NULL,          --FK year
  Plan_Id           BIGINT DEFAULT NULL,          --FK Plan
  AStatus_Id        BIGINT DEFAULT NULL,          --FK Academic Status
  Teacher_Id        BIGINT DEFAULT NULL,          --FK Teacher
  Status_Id         BIGINT DEFAULT 1 NOT NULL,    --Status
  Certif_Id         BIGINT DEFAULT NULL,          --FK Certification
  Adjec_Id          BIGINT DEFAULT 1 NOT NULL,    --Student adjective
  Classf_Id         BIGINT DEFAULT 1 NOT NULL,    --Student classification
  NatExam_Status_Id BIGINT DEFAULT 1 NOT NULL,    --Fk, National Exam Status: لايوجد ,ناجح ,غير منجز
  Trn_Grad_Level_Id BIGINT DEFAULT NULL,          --Grad Level
  Grad_ATerm_Id     BIGINT DEFAULT NULL,          --FK Grad Level
  ANum              VARCHAR(100) NOT NULL,     --Academic Numebr
  NNum              VARCHAR(100) DEFAULT NULL, --ID Number
  Insureuns_Number  VARCHAR(128) DEFAULT NULL, --Insurance number
  AR_FName          VARCHAR(100) NOT NULL,     --First Name 
  AR_Father         VARCHAR(100) NOT NULL,     --Father Name
  AR_Mother         VARCHAR(100) NOT NULL,     --Mother Name
  AR_LName          VARCHAR(100) NOT NULL,     --Last Name
  En_FName          VARCHAR(100) DEFAULT NULL, --First Name English
  En_Father         VARCHAR(100) DEFAULT NULL, --Father Name English
  En_Mother         VARCHAR(100) DEFAULT NULL, --Mother Name English
  EN_Lname          VARCHAR(100) DEFAULT NULL, --Last Name English'
  DOB               TIMESTAMP Default LOCALTIMESTAMP,            --'Date Of Birth',
  AR_POB            VARCHAR(100) DEFAULT NULL, --Birth Place
  EN_POB            VARCHAR(100) DEFAULT NULL, --Birth Place English
  Address1          VARCHAR(100) DEFAULT NULL, --Address1
  Address2          VARCHAR(100) DEFAULT NULL, --Address2
  Email             VARCHAR(100) DEFAULT NULL, --Email
  Phone             VARCHAR(100) DEFAULT NULL, --Phone Number
  Mobile            VARCHAR(100) DEFAULT NULL, --Mobile Number
  HKaied            VARCHAR(1024) DEFAULT NULL, --Kaied Header
  PKaied            VARCHAR(100) DEFAULT NULL, --Kaied Place
  NKaied            VARCHAR(100) DEFAULT NULL, --Kaied Number
  Military          VARCHAR(100) DEFAULT NULL, --Military
  Military_Num      BIGINT DEFAULT NULL,
  RDate             TIMESTAMP Default LOCALTIMESTAMP,            --Registration Date
  Cert_Avg          NUMERIC(5,2) DEFAULT NULL,        --Certification Avg
  Cert_Avg_Clear    NUMERIC(5,2) DEFAULT NULL,
  Cert_City         VARCHAR(100) DEFAULT NULL, --FK Certification  City 
  Cert_Num          VARCHAR(100) DEFAULT NULL, --Certification Number
  Cert_Year         VARCHAR(100) DEFAULT NULL, --Certification Year
  Cert_Min          VARCHAR(100) DEFAULT NULL, --Certification Min
  Cert_Max          VARCHAR(100) DEFAULT NULL, --Certification Max
  PassWord          VARCHAR(100) DEFAULT NULL, --Student PassWord
  Transfer          VARCHAR(256) DEFAULT NULL, --Student Transferred
  sImage            VARCHAR(512) DEFAULT NULL, --Image
  NatExam_Mark      NUMERIC(5,2) DEFAULT NULL,        --National Exam Mark
  Grad_Ord_Num      VARCHAR(100) DEFAULT NULL, --Grad Order Number
  Grad_Ord_Date     TIMESTAMP Default LOCALTIMESTAMP,            --Grad Order Date
  Grad_Gpa          NUMERIC(5,2) DEFAULT NULL,        --Grad GPA
  Grad_Avg          NUMERIC(5,2) DEFAULT NULL,        --Grad Avg
  Rem               VARCHAR(100),              -- ملاحظات
  Ins_User          BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User          BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Stud_PK                 PRIMARY KEY (Id), 
  CONSTRAINT Ams_Stud_UK                 UNIQUE      (ANum)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Stud_Plan_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Stud_Plan                        -- جدول مواد الخطة الدراسية
( Id                 BIGINT NOT NULL,           -- مفتاح رئيسي
  Plan_Id            BIGINT NOT NULL,             -- الخطة الدراسية
  Stud_Id            BIGINT NOT NULL,            -- الطلاب
  Colleg_Id          BIGINT DEFAULT 0 NOT NULL,   -- الكلي
  Section_Id         BIGINT DEFAULT 0 NOT NULL,   -- القسم  
  Speciality_Id      BIGINT DEFAULT 0 NOT NULL,   -- التخصص
  ExamLmt_Id         BIGINT NOT NULL,             -- حدود سقوف الاختبار
  Degreelmt_Id       BIGINT NOT NULL,             -- حدود الدرجات 
  Gpalmt_Id          BIGINT NOT NULL,             -- حدود العبىء الدراسي
  Yearlmt_Id         BIGINT NOT NULL,             -- حدود السنوات
  Gradlevellmt_Id    BIGINT NOT NULL,             -- حدود درجات التخرج
  Price_Id           BIGINT NOT NULL,             -- الاسعار
  isNational_Exam_Id BIGINT Default 1,            -- هل يوجد امتحان وطني
  Rem                VARCHAR(100),             -- ملاحظات
  Ins_User           BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User           BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Stud_Plan_PK              PRIMARY KEY (Id), 
  CONSTRAINT Ams_Stud_Plan_UK              UNIQUE      (Plan_Id,Stud_Id,Speciality_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Room_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Room                           -- جدول القعات
( Id         BIGINT NOT NULL,                 -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                -- حالة 
  Num        VARCHAR(100) NOT NULL,        -- الرقم
  Name       VARCHAR(256) NOT NULL,        -- الاسم
  Capacity   VARCHAR(3) NOT NULL,               -- السعة
  Location   VARCHAR(100),                 -- ملاحظات
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Room_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Room_UK         UNIQUE      (Num)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass                  -- جدول الشعب الدراسية
( Id         BIGINT NOT NULL,                -- مفتاح رئيسي
  aTerm_Id   BIGINT NOT NULL,                 -- الفصل الاكاديمي
  Teacher_Id BIGINT NOT NULL,                -- المدرس
  Item_Id    BIGINT NOT NULL,                 -- المادة 
  Status_Id  BIGINT Default 1,                -- حالة 
  Name       VARCHAR(256) NOT NULL,        -- الاسم
  capacity   VARCHAR(3) NOT NULL,          -- السعة
  Rem        VARCHAR(100),                 -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_UK         UNIQUE      (Name, aTerm_Id, Item_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Day_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass_Day           -- جدول أيام الشعب الدراسية
( Id       BIGINT NOT NULL,               -- مفتاح رئيسي
  Mst_Id   BIGINT NOT NULL,               -- مفتاح الأب
  Day_Id   BIGINT NOT NULL,                -- اليوم
  Room_Id  BIGINT DEFAULT 1 NOT NULL,      -- القاعة
  SHour    SMALLINT DEFAULT 8 NOT NULL,      -- ساعة البداية 
  SMinute  SMALLINT DEFAULT 0 NOT NULL,      -- دقيقة البداية
  EHour    SMALLINT DEFAULT 0 NOT NULL,      -- ساعة النهاية
  EMinute  SMALLINT DEFAULT 0 NOT NULL,      -- دقيقة النهاية
  Rem      VARCHAR(100),                -- ملاحظات
  Ins_User BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_Day_PK       PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_Day_UK       UNIQUE      (Mst_Id, Day_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Attend_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass_Attend        -- جدول حضور الشعب الدراسية
( Id         BIGINT NOT NULL,               -- مفتاح رئيسي
  aClass_Id  BIGINT NOT NULL,               -- الشعبة الدراسية
  dDate      TIMESTAMP Default LOCALTIMESTAMP,              -- التاريخ
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_Attend_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_Attend_UK         UNIQUE      (dDate, aClass_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Attend_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass_Attend_Trn         -- جدول بنود حضور الشعب الدراسية
( Id         BIGINT NOT NULL,                      -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,                      -- مفتاح الأب
  Stud_Id    BIGINT NOT NULL,                      -- الطالب
  Status_Id  BIGINT Default 1,                      -- حالة 
  Reason     VARCHAR(100),                       -- السبب
  Rem        VARCHAR(100),                       -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_Attend_Trn_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_Attend_Trn_UK         UNIQUE      (Mst_Id, Stud_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Dep_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass_Dep     -- جدول حرمان الشعب الدراسية
( Id         BIGINT NOT NULL,               -- مفتاح رئيسي
  aClass_Id  BIGINT NOT NULL,               -- الشعبة الدراسية
  Num        VARCHAR(100),                -- الرفم
  dDate      TIMESTAMP Default LOCALTIMESTAMP,              -- التاريخ
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_Dep_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_Dep_UK         UNIQUE      (Num, aClass_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Dep_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass_Dep_Trn      -- جدول بنود حرمان الشعب الدراسية
( Id         BIGINT NOT NULL,                       -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,                       -- مفتاح الأب
  Stud_Id    BIGINT NOT NULL,                       -- الطالب
  Reason     VARCHAR(100),                        -- السبب
  Rem        VARCHAR(100),                        -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_Dep_Trn_PK      PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_Dep_Trn_UK      UNIQUE      (Mst_Id, Stud_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Nomination_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass_Nomination      -- جدول الترشيح للامتحان
( Id         BIGINT NOT NULL,               -- مفتاح رئيسي
  aClass_Id  BIGINT NOT NULL,               -- الشعبة الدراسية
  dDate      TIMESTAMP Default LOCALTIMESTAMP,              -- التاريخ
  Mark4_Min  NUMERIC(6,2) DEFAULT 0.00 NOT NULL, -- Mark 4 Minimum Required Percentage
  Rem        VARCHAR(100),                -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_Nomination_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_Nomination_UK         UNIQUE      (aClass_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_AClass_Nomination_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_AClass_Nomination_Trn    -- جدول بنود لترشيح للامتحان
( Id         BIGINT NOT NULL,                   -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,                   -- مفتاح الأب
  Stud_Id    BIGINT NOT NULL,                   -- الطالب
  Status_Id  BIGINT  Default 1,                  -- حالة 
  Mark1      NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- العلامة 1
  Mark2      NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- العلامة 2
  Mark3      NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- العلامة 3
  Mark4      NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- العلامة 4
  Reason     VARCHAR(100),                    -- السبب
  Rem        VARCHAR(100),                    -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_AClass_Nomination_Trn_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_AClass_Nomination_Trn_UK         UNIQUE      (Mst_Id, Stud_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Stud_Trans_Item_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Stud_Trans_Item          -- جدول المواد المعادلة
( Id        BIGINT NOT NULL,                 -- مفتاح رئيسي
  ATerm_Id  BIGINT NOT NULL,                  -- الفصل الاكاديمي
  Stud_Id   BIGINT NOT NULL,                 -- الطالب 
  PItem_Id  BIGINT NOT NULL,                 -- مادة خطة
  Num       VARCHAR(100),                  -- الرفم
  dDate     TIMESTAMP Default LOCALTIMESTAMP,                -- التاريخ
  Rem       VARCHAR(100),                  -- ملاحظات
  Ins_User  BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User  BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Stud_Trans_Item_PK           PRIMARY KEY (Id), 
  CONSTRAINT Ams_Stud_Trans_Item_UK           UNIQUE      (Stud_Id, PItem_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Stud_Withdraw_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Stud_Withdraw            -- جدول المواد المعادلة
( Id        BIGINT NOT NULL,                  -- مفتاح رئيسي
  ATerm_Id  BIGINT NOT NULL,                   -- الفصل الاكاديمي
  Stud_Id   BIGINT NOT NULL,                  -- الطالب 
  AClass_Id BIGINT NOT NULL,                  -- الصف الدراسي
  Num       VARCHAR(100),                   -- الرفم
  dDate     TIMESTAMP Default LOCALTIMESTAMP,                 -- التاريخ
  Rem       VARCHAR(100),                   -- ملاحظات
  Ins_User  BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User  BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Stud_Withdraw_PK        PRIMARY KEY (Id), 
  CONSTRAINT Ams_Stud_Withdraw_UK        UNIQUE      (Stud_Id, AClass_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Grad_Ord_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Grad_Ord                 -- جدول قرارات التخرج
( Id            BIGINT NOT NULL,              -- مفتاح رئيسي
  ATerm_Id      BIGINT NOT NULL,               -- الفصل الاكاديمي
  Num           VARCHAR(100),               -- الرفم
  dDate         TIMESTAMP Default LOCALTIMESTAMP,             -- التاريخ
  Rem           VARCHAR(100),               -- ملاحظات
  Ins_User      BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User      BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Grad_Ord_PK           PRIMARY KEY (Id), 
  CONSTRAINT Ams_Grad_Ord_UK           UNIQUE      (Num, ATerm_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Grad_Ord_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Grad_Ord_Trn             -- جدول بنود قرارات التخرج
( Id             BIGINT NOT NULL,                -- مفتاح رئيسي
  Mst_Id         BIGINT NOT NULL,                -- مفتاح الأب
  Stud_Id        BIGINT NOT NULL,               -- الطالب 
  Trn_Level_Id   BIGINT NOT NULL,                -- درجة التخرج 
  Gpa_Percentage NUMERIC(5,2) DEFAULT 0.00 NOT NULL, -- النسبة المئوية للمعدل التراكمي
  Gpa            NUMERIC(5,2) DEFAULT 0.00 NOT NULL, --  المعدل التراكمي
  Rem            VARCHAR(100),                -- ملاحظات
  Ins_User       BIGINT,  Ins_Date TIMESTAMP,
  Upd_User       BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_Grad_Ord_Trn_PK       PRIMARY KEY (Id), 
  CONSTRAINT Ams_Grad_Ord_Trn_UK       UNIQUE      (Stud_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Ord_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Ord                            -- جدول القرارات الإدارية
( Id            BIGINT NOT NULL,              -- مفتاح رئيسي
  ATerm_Id      BIGINT NOT NULL,               -- الفصل الاكاديمي
  Type_Id       BIGINT NOT NULL,               -- نوع القرار
  Num           VARCHAR(100),               -- الرفم
  dDate         TIMESTAMP Default LOCALTIMESTAMP,             -- التاريخ
  Rem           VARCHAR(100),               -- ملاحظات
  Ins_User      BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User      BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Ord_PK       PRIMARY KEY (Id), 
  CONSTRAINT Ams_Ord_UK       UNIQUE      (Num, ATerm_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Ord_Trn_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Ord_Trn                  -- جدول بنود القرارات الإدارية
( Id         BIGINT NOT NULL,             -- مفتاح رئيسي
  Mst_Id     BIGINT NOT NULL,              -- مفتاح الأب
  Stud_Id    BIGINT NOT NULL,             -- الطالب 
  Descrption VARCHAR(256),              -- الوصف
  Rem        VARCHAR(100),              -- ملاحظات
  Ins_User   BIGINT,  Ins_Date TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_Ord_Trn_PK      PRIMARY KEY (Id), 
  CONSTRAINT Ams_Ord_Trn_UK      UNIQUE      (Stud_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Stud_Reg_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Stud_Reg               -- جدول تسجيل الطلاب
( Id         BIGINT NOT NULL,                   -- مفتاح رئيسي
  ATerm_Id   BIGINT NOT NULL,                    -- الفصل الدراسي
  Stud_Id    BIGINT NOT NULL,                   -- الطالب 
  Price_Id   BIGINT NOT NULL,                    -- الاسعار 
  FStatus_Id BIGINT DEFAULT 1 NOT NULL,         --Finance Status, 1 Not Paid, 2 Paid
  Status_Id  BIGINT DEFAULT 1 NOT NULL,         --Status, 1 New, 2 Finished, 3 Conditional
  Term_Gpa   NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- المعدل الفصلي
  Total_Gpa  NUMERIC(5,2) DEFAULT 0.00 NOT NULL,     -- المعدل التراكمي
  dDate      TIMESTAMP Default LOCALTIMESTAMP,                  -- التاريخ
  SRem       VARCHAR(100),                    -- ملاحظات الطالب
  Rem        VARCHAR(100),                    -- ملاحظات
  Ins_User   BIGINT,  Ins_Date TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_Stud_Reg_PK       PRIMARY KEY (Id), 
  CONSTRAINT Ams_Stud_Reg_UK       UNIQUE      (ATerm_Id,Stud_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Stud_Reg_Item_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Stud_Reg_Item          -- جدول تسجيل الطلاب
( Id            BIGINT NOT NULL,                -- مفتاح رئيسي
  Mst_Id        BIGINT NOT NULL,                --  مفتاح الأب
  PItem_Id      BIGINT NOT NULL,                -- مادة خطة دراسية 
  AClass_Id     BIGINT NOT NULL,                -- الشعبة الدراسية 
  TrnDegree_Id  BIGINT NOT NULL,                 -- بند حدود الدرجات 
  Mark1         NUMERIC(5,2) DEFAULT 0.00 NOT NULL,  -- العلامة 1
  Mark2         NUMERIC(5,2) DEFAULT 0.00 NOT NULL,  -- العلامة 2
  Mark3         NUMERIC(5,2) DEFAULT 0.00 NOT NULL,  -- العلامة 3
  Mark4         NUMERIC(5,2) DEFAULT 0.00 NOT NULL,  -- العلامة 4
  Mark5         NUMERIC(5,2) DEFAULT 0.00 NOT NULL,  -- العلامة 5
  Rem           VARCHAR(100),                  -- ملاحظات
  Ins_User      BIGINT,  Ins_Date TIMESTAMP,
  Upd_User      BIGINT,  Upd_Date TIMESTAMP,
  CONSTRAINT Ams_Stud_Reg_Item_PK           PRIMARY KEY (Id), 
  CONSTRAINT Ams_Stud_Reg_Item_UK           UNIQUE      (Mst_Id,PItem_Id)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Lib_Author_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Lib_Author                           -- جدول المؤلفون
( Id         BIGINT NOT NULL,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة 
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Lib_Author_PK        PRIMARY KEY (Id  ),
  CONSTRAINT Ams_Lib_Author_UK        UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Lib_Category_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Lib_Category                        -- جدول الفئات
( Id         BIGINT NOT NULL,                           -- مفتاح رئيسي
  Status_Id  BIGINT Default 1,                          -- حالة 
  Name       VARCHAR(100) NOT NULL,                  -- الاسم
  Rem        VARCHAR(100),                           -- ملاحظات
  Ins_User   BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User   BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Lib_Category_PK        PRIMARY KEY (Id  ),
  CONSTRAINT Ams_Lib_Category_UK        UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Lib_Publisher_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Lib_Publisher                   -- جدول الناشرون
( Id        BIGINT NOT NULL,                       -- مفتاح رئيسي
  Status_Id BIGINT Default 1,                      -- حالة  
  Name      VARCHAR(200) NOT NULL,              -- الاسم 
  Rem       VARCHAR(100),                       -- ملاحظات
  Ins_User  BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User  BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Lib_Publisher_PK         PRIMARY KEY (Id), 
  CONSTRAINT Ams_Lib_Publisher_UK         UNIQUE      (Name)
);

CREATE SEQUENCE IF NOT EXISTS Ams_Lib_Document_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table Ams_Lib_Document                        -- جدول الكتب
( Id           BIGINT NOT NULL,                       -- مفتاح رئيسي
  Status_Id    BIGINT Default 1,                       -- حالة 
  Publisher_Id BIGINT NOT NULL,                        -- Publisher
  Author_Id    BIGINT NOT NULL,                        -- Author
  Type_Id      BIGINT NOT NULL,                        -- Type
  Category_Id  BIGINT NOT NULL,                        -- Category
  IsEbook_Id   BIGINT DEFAULT 2 NOT NULL,              -- Is EBook
  IsHbook_Id   BIGINT DEFAULT 1 NOT NULL,              -- is a Hard copy
  Title        VARCHAR(200) NOT NULL,               -- Title
  Qnt          SMALLINT DEFAULT 1 NOT NULL,              -- Copies
  cQnt         SMALLINT DEFAULT 1 NOT NULL,              -- Available Copies
  Rem          VARCHAR(100),                        -- ملاحظات
  Ins_User     BIGINT,  Ins_Date    TIMESTAMP,
  Upd_User     BIGINT,  Upd_Date    TIMESTAMP,
  CONSTRAINT Ams_Lib_Document_PK           PRIMARY KEY (Id)
);
