-- Ported from Oracle: db/01-Copy/8101_AMS_0101_TBLS.SQL

-- Generated by scripts/db-port/translate.js for postgres.

-- Tables carry their Oracle synonym name; see PORTING-REPORT.md.

\connect phsoftme_erp_demo


--set Pagesize 1000
--select 'Drop table '   || table_name                          || ';' from user_tables    where table_name    like 'AMS%' ;
--select 'Drop Synonym ' || Synonym_name                        || ';' from user_Synonyms  where Synonym_name  like 'AMS%' ;
--select 'Drop Sequence '|| Sequence_name                       || ';' from user_Sequences where Sequence_name like 'AMS%' ;
--select 'Drop View '    || View_name                           || ';' from user_Views     where View_name     like 'AMS%' ;
--select 'Drop '         || OBJECT_TYPE   || ' ' || Object_name || ';' from user_Objects   where Object_name   like 'AMS%' ;
----------------------------------------------------------------------------------------------------
Create Table AMS_Cod_Year                                -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Year_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Year_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Year (Id, Name) VALUES (0, '-');

INSERT INTO AMS_Cod_Year (Id, Name) VALUES (1, 'Year 1');

INSERT INTO AMS_Cod_Year (Id, Name) VALUES (2, 'Year 2');

INSERT INTO AMS_Cod_Year (Id, Name) VALUES (3, 'Year 3');

INSERT INTO AMS_Cod_Year (Id, Name) VALUES (4, 'Year 4');

INSERT INTO AMS_Cod_Year (Id, Name) VALUES (5, 'Year 5');

----------------------------------------------------------------------------------------------------
Create Table AMS_Cod_Term                                -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Term_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Term_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Term (Id, Name) VALUES (0, '-');

INSERT INTO AMS_Cod_Term (Id, Name) VALUES (1, 'Term 1');

INSERT INTO AMS_Cod_Term (Id, Name) VALUES (2, 'Term 2');

INSERT INTO AMS_Cod_Term (Id, Name) VALUES (3, 'Term 3');

----------------------------------------------------------------------------------------------------
Create Table AMS_Cod_Price_Type                          -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Price_Type_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Price_Type_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Price_Type (Id, Name) VALUES (0, '-');

INSERT INTO AMS_Cod_Price_Type (Id, Name) VALUES (1, 'One Time');

INSERT INTO AMS_Cod_Price_Type (Id, Name) VALUES (2, 'Per Term');

INSERT INTO AMS_Cod_Price_Type (Id, Name) VALUES (3, 'Per Item');

CREATE SEQUENCE IF NOT EXISTS AMS_Cod_Fee_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table AMS_Cod_Fee                                 -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Fee_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Fee_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Fee (Id, Name) VALUES (0, '-');

INSERT INTO AMS_Cod_Fee (Id, Name) VALUES (1, 'رسم تسجيل');

INSERT INTO AMS_Cod_Fee (Id, Name) VALUES (2, 'رسم مادة');

INSERT INTO AMS_Cod_Fee (Id, Name) VALUES (3, 'رسم امتحان');

CREATE SEQUENCE IF NOT EXISTS AMS_Cod_Disc_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table AMS_Cod_Disc                            -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Disc_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Disc_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Disc (Id, Name) VALUES (0, '-');

INSERT INTO AMS_Cod_Disc (Id, Name) VALUES (1, 'رسم تسجيل');

INSERT INTO AMS_Cod_Disc (Id, Name) VALUES (2, 'رسم مادة');

INSERT INTO AMS_Cod_Disc (Id, Name) VALUES (3, 'رسم امتحان');

CREATE SEQUENCE IF NOT EXISTS AMS_Cod_Cert_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table AMS_Cod_Cert                          -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Cert_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Cert_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Cert (Id, Name) VALUES (0, '-');

CREATE SEQUENCE IF NOT EXISTS AMS_Cod_Country_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table AMS_Cod_Country                            -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Country_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Country_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Country (Id, Name) VALUES (0, '-');

CREATE SEQUENCE IF NOT EXISTS AMS_Cod_City_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table AMS_Cod_City                               -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_City_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_City_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_City (Id, Name) VALUES (0, '-');

CREATE SEQUENCE IF NOT EXISTS AMS_Cod_Stud_Kind_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table AMS_Cod_Stud_Kind                         -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Stud_Kind_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Stud_Kind_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Stud_Kind (Id, Name) VALUES (0, '-');

CREATE SEQUENCE IF NOT EXISTS AMS_Cod_Nat_Seq
  INCREMENT BY 1
  START WITH 1;

Create Table AMS_Cod_Nat                           -- جدول ترميز
( Id         BIGINT NOT NULL,				                   -- مفتاح رئيسي
  Name       VARCHAR(100) NOT NULL,				           -- الاسم
  Rem        VARCHAR(100),          				         -- ملاحظات
  Ins_User   BIGINT, Ins_Date     TIMESTAMP,
  Upd_User   BIGINT, Upd_Date     TIMESTAMP,
  CONSTRAINT AMS_Cod_Nat_PK     PRIMARY KEY (Id  ),
  CONSTRAINT AMS_Cod_Nat_UK     UNIQUE      (Name)
);

INSERT INTO AMS_Cod_Nat (Id, Name) VALUES (0, '-');

-- TODO(port): other has no automatic equivalent (source line 191).
-- Original Oracle statement:
--   ----------------------------------------------------------------------------------------------------
--   
--   AMS_Code_Adm_Order_Type
--   AMS_Code_Astatus
--   AMS_Code_Degree_Type
--   AMS_Code_Grad_Level
--   AMS_Code_Item_Force
--   AMS_Code_Item_Kind
--   AMS_Code_Sitem_Status
--   AMS_Code_Student_Classification
